{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/init(from:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/experimentName","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/identifier","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/isDefault","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/json","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/products"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/encode(to:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/ObservableObject-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/7Combine16ObservableObjectP","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/Se","doc:\/\/org.cocoapods.ApphudSDK\/SE","doc:\/\/org.cocoapods.ApphudSDK\/SQ","doc:\/\/org.cocoapods.ApphudSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPaywall"}]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"Paywalls configured in Apphud Dashboard > Product Hub > Paywalls. Each paywall contains an array of "},{"type":"codeVoice","code":"ApphudProduct"},{"text":" objects that you use for purchase. A paywall is a product array with custom JSON. The array is ordered and may be used to display products on your in-app purchase screen.","type":"text"}],"type":"paragraph"},{"text":"Related Articles:","type":"heading","level":4,"anchor":"Related-Articles"},{"type":"paragraph","inlineContent":[{"text":"To get paywall by identifier :","type":"text"}]},{"syntax":"swift","code":["let paywall = await Apphud.paywall(ApphudPaywallID.onboarding.rawValue)"],"type":"codeListing"},{"type":"aside","name":"Note","style":"note","content":[{"inlineContent":[{"text":"An alternative way of getting ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywalls()"}],"type":"paragraph"}]},{"style":"important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information  - "},{"type":"reference","identifier":"https:\/\/docs.apphud.com\/docs\/paywalls","isActive":true}]}],"name":"Important"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudpaywall"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudpaywall"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall"},"metadata":{"modules":[{"name":"ApphudSDK"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"ApphudPaywall"}],"title":"ApphudPaywall","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPaywall"}],"externalID":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},"abstract":[{"text":"An object associated with purchases container (Paywall).","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ApphudSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/encode(to:)":{"abstract":[],"title":"encode(to:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/encode(to:)","url":"\/documentation\/apphudsdk\/apphudpaywall\/encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"text":"Encoder","preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/isDefault":{"abstract":[{"text":"It’s possible to make a paywall default – it’s a special alias name, that can be assigned to only ONE paywall at a time. There can be no default paywalls at all. It’s up to you whether you want to have them or not.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/isDefault","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isDefault"}],"type":"topic","url":"\/documentation\/apphudsdk\/apphudpaywall\/isdefault","title":"isDefault","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDefault"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","title":"ApphudPaywall","abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudPaywall","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/apphudsdk\/apphudpaywall","navigatorTitle":[{"text":"ApphudPaywall","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/experimentName":{"navigatorTitle":[{"text":"experimentName","kind":"identifier"}],"role":"symbol","title":"experimentName","kind":"symbol","abstract":[{"text":"A\/B test experiment name","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"experimentName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/apphudsdk\/apphudpaywall\/experimentname","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/experimentName"},"doc://org.cocoapods.ApphudSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.ApphudSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","title":"Swift.CVarArg"},"https://docs.apphud.com/docs/paywalls":{"identifier":"https:\/\/docs.apphud.com\/docs\/paywalls","type":"link","url":"https:\/\/docs.apphud.com\/docs\/paywalls","title":"Paywalls Documentation","titleInlineContent":[{"text":"Paywalls Documentation","type":"text"}]},"doc://org.cocoapods.ApphudSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/json":{"kind":"symbol","abstract":[{"type":"text","text":"Insert any parameters you need into custom JSON. It could be titles, descriptions, localisations, font, background and color parameters, URLs to media content, etc. Parameters count are not limited."}],"type":"topic","role":"symbol","title":"json","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"json","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"json","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/json","url":"\/documentation\/apphudsdk\/apphudpaywall\/json"},"doc://org.cocoapods.ApphudSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/products":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/products","title":"products","abstract":[{"text":"Array of products","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"products"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct"},{"kind":"text","text":"]"}],"type":"topic","role":"symbol","url":"\/documentation\/apphudsdk\/apphudpaywall\/products","navigatorTitle":[{"text":"products","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/init(from:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","title":"init(from:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/init(from:)","kind":"symbol","abstract":[],"url":"\/documentation\/apphudsdk\/apphudpaywall\/init(from:)","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/ObservableObject-Implementations":{"type":"topic","url":"\/documentation\/apphudsdk\/apphudpaywall\/observableobject-implementations","title":"ObservableObject Implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/ObservableObject-Implementations","kind":"article"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywalls()":{"title":"paywalls()","role":"symbol","url":"\/documentation\/apphudsdk\/apphud\/paywalls()","kind":"symbol","deprecated":true,"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paywalls"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywalls()","navigatorTitle":[{"kind":"identifier","text":"paywallsWithCompletionHandler:"}],"abstract":[{"text":"Asynchronously retrieves the paywalls configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"text":"s are loaded from the App Store.","type":"text"}]},"doc://org.cocoapods.ApphudSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SE","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/7Combine16ObservableObjectP":{"title":"Combine.ObservableObject","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/7Combine16ObservableObjectP","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/identifier":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/identifier","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","title":"identifier","url":"\/documentation\/apphudsdk\/apphudpaywall\/identifier","abstract":[{"text":"Your custom paywall identifier from Apphud Dashboard","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","url":"\/documentation\/apphudsdk","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"title":"ApphudSDK","type":"topic","role":"collection","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/Se","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ApphudPaywall","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ApphudPaywall"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"ApphudPaywall"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/experimentName","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/identifier","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/isDefault","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/json","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/products"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ApphudPaywall","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1isDefault\/title","value":"isDefault"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1isDefault\/fragments","value":[{"text":"isDefault","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ApphudPaywall","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title"},{"value":[{"kind":"identifier","text":"ApphudPaywall"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1experimentName\/title","value":"experimentName"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1experimentName\/fragments","value":[{"text":"experimentName","kind":"identifier"}]},{"value":"json","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1json\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1json\/fragments","op":"replace","value":[{"kind":"identifier","text":"json"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1products\/title","value":"products"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1products\/fragments","value":[{"text":"products","kind":"identifier"}]},{"value":"paywallsWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywalls()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywalls()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"paywallsWithCompletionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1identifier\/title","op":"replace","value":"identifier"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1identifier\/fragments","op":"replace","value":[{"text":"identifier","kind":"identifier"}]}]}]}