{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/init(_:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"title":"Type Properties","generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/age","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/cohort","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/email","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/gender","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/name","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/phone"]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/SQ","doc:\/\/org.cocoapods.ApphudSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"abstract":[{"type":"text","text":"User property initializer class with reserved property names."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudUserPropertyKey"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphuduserpropertykey"]},{"paths":["\/documentation\/apphudsdk\/apphuduserpropertykey"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"ApphudUserPropertyKey","roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"modules":[{"name":"ApphudSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudUserPropertyKey"}],"role":"symbol","externalID":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"},"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey/age":{"role":"symbol","navigatorTitle":[{"text":"age","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/age","abstract":[],"type":"topic","title":"age","url":"\/documentation\/apphudsdk\/apphuduserpropertykey\/age","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"age","kind":"identifier"},{"kind":"text","text":": "},{"text":"ApphudUserPropertyKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey/name":{"navigatorTitle":[{"text":"name","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"name","abstract":[],"url":"\/documentation\/apphudsdk\/apphuduserpropertykey\/name","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/name","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ApphudUserPropertyKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey/gender":{"url":"\/documentation\/apphudsdk\/apphuduserpropertykey\/gender","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/gender","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"gender","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudUserPropertyKey","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"}],"title":"gender","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gender"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey/cohort":{"role":"symbol","navigatorTitle":[{"text":"cohort","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphuduserpropertykey\/cohort","title":"cohort","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cohort","kind":"identifier"},{"kind":"text","text":": "},{"text":"ApphudUserPropertyKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/cohort","kind":"symbol","abstract":[]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey/email":{"navigatorTitle":[{"text":"email","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"email","abstract":[],"url":"\/documentation\/apphudsdk\/apphuduserpropertykey\/email","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/email","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ApphudUserPropertyKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey/phone":{"role":"symbol","navigatorTitle":[{"text":"phone","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphuduserpropertykey\/phone","title":"phone","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phone","kind":"identifier"},{"kind":"text","text":": "},{"text":"ApphudUserPropertyKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/phone","kind":"symbol","abstract":[]},"doc://org.cocoapods.ApphudSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP"},"doc://org.cocoapods.ApphudSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"},"doc://org.cocoapods.ApphudSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey/init(_:)":{"role":"symbol","navigatorTitle":[{"text":"init:","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphuduserpropertykey\/init(_:)","title":"init(_:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/init(_:)","kind":"symbol","abstract":[{"type":"text","text":"Initialize with custom property key string."},{"type":"text","text":" "},{"text":"Example:","type":"text"}]},"doc://org.cocoapods.ApphudSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SH","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey":{"abstract":[{"type":"text","text":"User property initializer class with reserved property names."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudUserPropertyKey"}],"title":"ApphudUserPropertyKey","url":"\/documentation\/apphudsdk\/apphuduserpropertykey","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","navigatorTitle":[{"text":"ApphudUserPropertyKey","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ApphudUserPropertyKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ApphudUserPropertyKey","kind":"identifier"}]},{"value":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/init(_:)"]},{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/age","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/cohort","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/email","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/gender","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/name","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/phone"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudUserPropertyKey"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"age","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1age\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1age\/fragments","value":[{"kind":"identifier","text":"age"}],"op":"replace"},{"op":"replace","value":"name","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1name\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1name\/fragments","op":"replace","value":[{"text":"name","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1gender\/title","value":"gender","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"gender"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1gender\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1cohort\/title","op":"replace","value":"cohort"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1cohort\/fragments","value":[{"kind":"identifier","text":"cohort"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1email\/title","value":"email"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1email\/fragments","value":[{"kind":"identifier","text":"email"}],"op":"replace"},{"value":"phone","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1phone\/title"},{"value":[{"kind":"identifier","text":"phone"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1phone\/fragments","op":"replace"},{"op":"replace","value":"init:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1init(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"init:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1init(_:)\/fragments"},{"value":"ApphudUserPropertyKey","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ApphudUserPropertyKey"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/fragments"},{"value":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}