{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/onCloseButtonTapped","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/onShouldOpenURL","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/onTransactionCompleted","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/onTransactionStarted","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/paywall","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/shouldAutoDismiss","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/shouldPopOnDismiss","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/state","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/useSystemLoadingIndicator"]},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/viewDidAppear(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/viewWillDisappear(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/ApphudViewDelegate-Implementations","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/WKUIDelegate-Implementations"]}],"metadata":{"symbolKind":"class","title":"ApphudPaywallScreenController","externalID":"c:@M@ApphudSDK@objc(cs)ApphudPaywallScreenController","role":"symbol","modules":[{"name":"ApphudSDK"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ApphudPaywallScreenController","kind":"identifier"}],"navigatorTitle":[{"text":"ApphudPaywallScreenController","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/apphudsdk\/apphudpaywallscreencontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudpaywallscreencontroller"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPaywallScreenController"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)UIViewController"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ApphudSDK\/s8CopyableP","doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/SQ","doc:\/\/org.cocoapods.ApphudSDK\/SH","doc:\/\/org.cocoapods.ApphudSDK\/s8SendableP","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.ApphudSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)WKUIDelegate"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","references":{"doc://org.cocoapods.ApphudSDK/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/s8CopyableP":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.ApphudSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SH"},"doc://org.cocoapods.ApphudSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.ApphudSDK/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIContentContainer"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ApphudPaywallScreenController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudPaywallScreenController"}],"url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller","abstract":[],"title":"ApphudPaywallScreenController","type":"topic","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)UIViewController"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/shouldPopOnDismiss":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldPopOnDismiss","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","abstract":[{"type":"text","text":"Indicates whether controller should pop the navigation stack instead of being dismissed modally."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/shouldPopOnDismiss","title":"shouldPopOnDismiss","type":"topic","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/shouldpopondismiss","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/useSystemLoadingIndicator":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useSystemLoadingIndicator"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","title":"useSystemLoadingIndicator","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/useSystemLoadingIndicator","abstract":[{"text":"Determines whether the SDK should display a system loading indicator during purchase or restore actions.","type":"text"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/usesystemloadingindicator"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/paywall":{"url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/paywall","abstract":[{"type":"text","text":"Apphud paywall object."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"paywall","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier","text":"ApphudPaywall"}],"title":"paywall","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/paywall","type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/onTransactionStarted":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/onTransactionStarted","role":"symbol","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/ontransactionstarted","title":"onTransactionStarted","abstract":[{"type":"text","text":"Called when the user initiates a purchase or starts restoring purchases."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onTransactionStarted","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"ApphudProduct","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/objc(pl)WKUIDelegate":{"type":"unresolvable","title":"WKUIDelegate","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)WKUIDelegate"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/WKUIDelegate-Implementations":{"type":"topic","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/wkuidelegate-implementations","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/WKUIDelegate-Implementations","title":"WKUIDelegate Implementations","kind":"article","abstract":[],"role":"collectionGroup"},"doc://org.cocoapods.ApphudSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.ApphudSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.ApphudSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/ApphudViewDelegate-Implementations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/apphudviewdelegate-implementations","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/ApphudViewDelegate-Implementations","title":"ApphudViewDelegate Implementations","kind":"article","abstract":[]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/onShouldOpenURL":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onShouldOpenURL"},{"kind":"text","text":": (("},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")?"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/onShouldOpenURL","role":"symbol","title":"onShouldOpenURL","abstract":[{"type":"text","text":"A callback that is triggered when the user taps a link that would open an external URL from the paywall."}],"url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/onshouldopenurl"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/onTransactionCompleted":{"kind":"symbol","title":"onTransactionCompleted","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/onTransactionCompleted","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/ontransactioncompleted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"onTransactionCompleted","kind":"identifier"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Called when a purchase or restoration completes, either successfully or with a failure due to user cancellation or another error."}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSCoding"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s8SendableP"},"doc://org.cocoapods.ApphudSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/viewDidAppear(_:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/viewDidAppear(_:)","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/viewdidappear(_:)","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"title":"viewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ApphudSDK/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/viewWillDisappear(_:)":{"kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/viewWillDisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"title":"viewWillDisappear(_:)","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/viewwilldisappear(_:)","type":"topic"},"doc://org.cocoapods.ApphudSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/shouldAutoDismiss":{"role":"symbol","abstract":[{"type":"text","text":"Indicated whether controller should dismiss automatically on close button tap or on successful purchase or restoration. Default is "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldAutoDismiss","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/shouldAutoDismiss","type":"topic","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/shouldautodismiss","title":"shouldAutoDismiss"},"doc://org.cocoapods.ApphudSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/onCloseButtonTapped":{"abstract":[{"text":"Called when the user finishes interacting with the paywall—either by completing a purchase successfully or by closing the paywall manually.","type":"text"}],"kind":"symbol","title":"onCloseButtonTapped","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onCloseButtonTapped","kind":"identifier"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/onCloseButtonTapped","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/onclosebuttontapped"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/state":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/state","kind":"symbol","role":"symbol","title":"state","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/state","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ApphudPaywallScreenState","preciseIdentifier":"s:9ApphudSDK0A18PaywallScreenStateO"}],"abstract":[{"type":"text","text":"Indicates whether the paywall controller has finished loading its content."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"ApphudPaywallScreenController","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ApphudPaywallScreenController"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ApphudPaywallScreenController"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/viewDidAppear(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/viewWillDisappear(_:)"]},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/WKUIDelegate-Implementations"]}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)UIViewController"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)WKUIDelegate"],"type":"conformsTo"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudPaywallScreenController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"value":"ApphudPaywallScreenController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/fragments","value":[{"text":"ApphudPaywallScreenController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/navigatorTitle","op":"replace","value":[{"text":"ApphudPaywallScreenController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController~1viewDidAppear(_:)\/title","op":"replace","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController~1viewWillDisappear(_:)\/fragments"}]}]}