{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudScreenDismissAction"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ApphudSDK@E@ApphudScreenDismissAction","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ApphudScreenDismissAction","kind":"identifier"}],"roleHeading":"Enumeration","title":"ApphudScreenDismissAction","modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"text":"ApphudScreenDismissAction","kind":"identifier"}],"role":"symbol"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/closeOnly","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/none","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/thankAndClose"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/init(rawValue:)"]},{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/Equatable-Implementations","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphudscreendismissaction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudscreendismissaction"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"abstract":[{"text":"These are three types of actions that are returned in ","type":"text"},{"type":"codeVoice","code":"apphudScreenDismissAction(screenName: String, controller: UIViewController)"},{"type":"text","text":" delegate method"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/SQ","doc:\/\/org.cocoapods.ApphudSDK\/SH","doc:\/\/org.cocoapods.ApphudSDK\/SY"],"type":"conformsTo"}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction/closeOnly":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/closeOnly","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"closeOnly","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudScreenDismissActionCloseOnly"}],"abstract":[],"title":"ApphudScreenDismissAction.closeOnly","role":"symbol","kind":"symbol","url":"\/documentation\/apphudsdk\/apphudscreendismissaction\/closeonly","type":"topic"},"doc://org.cocoapods.ApphudSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SY"},"doc://org.cocoapods.ApphudSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SQ"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction/none":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"type":"topic","url":"\/documentation\/apphudsdk\/apphudscreendismissaction\/none","title":"ApphudScreenDismissAction.none","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ApphudScreenDismissActionNone"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/none"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction/thankAndClose":{"url":"\/documentation\/apphudsdk\/apphudscreendismissaction\/thankandclose","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"thankAndClose","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/thankAndClose","title":"ApphudScreenDismissAction.thankAndClose","navigatorTitle":[{"text":"ApphudScreenDismissActionThankAndClose","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/RawRepresentable-Implementations","type":"topic","abstract":[],"url":"\/documentation\/apphudsdk\/apphudscreendismissaction\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction/init(rawValue:)":{"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk\/apphudscreendismissaction\/init(rawvalue:)","abstract":[],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/SH":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/Equatable-Implementations","url":"\/documentation\/apphudsdk\/apphudscreendismissaction\/equatable-implementations","abstract":[],"type":"topic","role":"collectionGroup"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction":{"navigatorTitle":[{"kind":"identifier","text":"ApphudScreenDismissAction"}],"abstract":[{"text":"These are three types of actions that are returned in ","type":"text"},{"code":"apphudScreenDismissAction(screenName: String, controller: UIViewController)","type":"codeVoice"},{"text":" delegate method","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction","url":"\/documentation\/apphudsdk\/apphudscreendismissaction","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudScreenDismissAction"}],"title":"ApphudScreenDismissAction","role":"symbol","type":"topic","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","url":"\/documentation\/apphudsdk","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"title":"ApphudSDK","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ApphudScreenDismissAction"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudScreenDismissAction"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ApphudScreenDismissAction","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/closeOnly","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/none","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/thankAndClose"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudScreenDismissAction"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction~1closeOnly\/title","op":"replace","value":"ApphudScreenDismissActionCloseOnly"},{"value":[{"kind":"identifier","text":"ApphudScreenDismissActionCloseOnly"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction~1closeOnly\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction~1none\/title","op":"replace","value":"ApphudScreenDismissActionNone"},{"value":[{"kind":"identifier","text":"ApphudScreenDismissActionNone"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction~1none\/fragments"},{"value":"ApphudScreenDismissActionThankAndClose","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction~1thankAndClose\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction~1thankAndClose\/fragments","value":[{"text":"ApphudScreenDismissActionThankAndClose","kind":"identifier"}]},{"value":"ApphudScreenDismissAction","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction\/fragments","value":[{"text":"ApphudScreenDismissAction","kind":"identifier"}]}]}]}