{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudkeychain"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudkeychain"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Class for storing user data"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudKeychain"}]}],"kind":"declarations"}],"metadata":{"title":"ApphudKeychain","modules":[{"name":"ApphudSDK"}],"externalID":"c:@M@ApphudSDK@objc(cs)ApphudKeychain","role":"symbol","navigatorTitle":[{"text":"ApphudKeychain","kind":"identifier"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ApphudKeychain","kind":"identifier"}],"roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/SQ","doc:\/\/org.cocoapods.ApphudSDK\/SH"],"kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudKeychain","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ApphudSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ApphudSDK/SH":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudKeychain/init":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudKeychain\/init","abstract":[],"role":"symbol","title":"init","url":"\/documentation\/apphudsdk\/apphudkeychain\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudKeychain":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudKeychain","abstract":[{"text":"Class for storing user data","type":"text"}],"role":"symbol","title":"ApphudKeychain","url":"\/documentation\/apphudsdk\/apphudkeychain","navigatorTitle":[{"text":"ApphudKeychain","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudKeychain"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"ApphudKeychain","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ApphudKeychain","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ApphudKeychain"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudKeychain\/init"]}],"path":"\/topicSections","op":"add"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudKeychain","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"value":"ApphudKeychain","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudKeychain\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudKeychain\/fragments","value":[{"kind":"identifier","text":"ApphudKeychain"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}