{"abstract":[{"type":"text","text":"An object containing all incoming Rule information."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ApphudRule"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudRule","kind":"identifier"}],"symbolKind":"class","title":"ApphudRule","externalID":"c:@M@ApphudSDK@objc(cs)ApphudRule","roleHeading":"Class","role":"symbol","modules":[{"name":"ApphudSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudRule","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudRule\/rule_name","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudRule\/screen_name"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudRule","kind":"identifier"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudrule"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudrule"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/SQ","doc:\/\/org.cocoapods.ApphudSDK\/SH"]}],"references":{"doc://org.cocoapods.ApphudSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"},"doc://org.cocoapods.ApphudSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudRule/screen_name":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"screen_name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"screen_name"}],"role":"symbol","kind":"symbol","title":"screen_name","url":"\/documentation\/apphudsdk\/apphudrule\/screen_name","abstract":[{"type":"text","text":"Screen name that is visible in Apphud Screens Dashboard"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudRule\/screen_name"},"doc://org.cocoapods.ApphudSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SQ"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudRule":{"navigatorTitle":[{"kind":"identifier","text":"ApphudRule"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudRule","abstract":[{"text":"An object containing all incoming Rule information.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphudrule","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudRule"}],"title":"ApphudRule","role":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SH"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudRule/rule_name":{"abstract":[{"type":"text","text":"Rule name that is visible in Apphud Rules Dashboard"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rule_name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/apphudsdk\/apphudrule\/rule_name","kind":"symbol","navigatorTitle":[{"text":"rule_name","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudRule\/rule_name","role":"symbol","title":"rule_name"},"doc://org.cocoapods.ApphudSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject"},"doc://org.cocoapods.ApphudSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ApphudRule"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ApphudRule","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ApphudRule","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudRule\/rule_name","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudRule\/screen_name"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"ApphudRule","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"value":"screen_name","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudRule~1screen_name\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudRule~1screen_name\/fragments","value":[{"kind":"identifier","text":"screen_name"}]},{"value":"ApphudRule","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudRule\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ApphudRule"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudRule\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudRule~1rule_name\/title","op":"replace","value":"rule_name"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudRule~1rule_name\/fragments","value":[{"kind":"identifier","text":"rule_name"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}