{"metadata":{"externalID":"c:@M@ApphudSDK@objc(cs)ApphudError","navigatorTitle":[{"kind":"identifier","text":"ApphudError"}],"modules":[{"name":"ApphudSDK"}],"title":"ApphudError","symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudError","kind":"identifier"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError\/networkIssue()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSError"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSCopying","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSSecureCoding","doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/SQ","doc:\/\/org.cocoapods.ApphudSDK\/s5ErrorP","doc:\/\/org.cocoapods.ApphudSDK\/SH","doc:\/\/org.cocoapods.ApphudSDK\/s8SendableP","doc:\/\/org.cocoapods.ApphudSDK\/s16SendableMetatypeP"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudError"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphuderror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphuderror"]}],"references":{"doc://org.cocoapods.ApphudSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ApphudSDK/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s5ErrorP"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSSecureCoding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSSecureCoding","title":"Foundation.NSSecureCoding"},"doc://org.cocoapods.ApphudSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ApphudSDK/objc(cs)NSError":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSError","type":"unresolvable","title":"NSError"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.ApphudSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.ApphudSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSCoding"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSCopying"},"doc://org.cocoapods.ApphudSDK/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s16SendableMetatypeP"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudError/networkIssue()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError\/networkIssue()","url":"\/documentation\/apphudsdk\/apphuderror\/networkissue()","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkIssue"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","role":"symbol","title":"networkIssue()"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudError":{"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudError"}],"url":"\/documentation\/apphudsdk\/apphuderror","title":"ApphudError","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudError"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError"},"doc://org.cocoapods.ApphudSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s8SendableP"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ApphudError","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ApphudError"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"ApphudError"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSError"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudError","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/title","op":"replace","value":"ApphudError"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/fragments","op":"replace","value":[{"text":"ApphudError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ApphudError"}]}]}]}