{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"abstract":[{"type":"text","text":"This class will contain some utils, more will be added in the future."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/checkRules()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/enableAllLogs()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/enableDebugLogs()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/sdkVersion()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/useStoreKitV2()"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"ApphudUtils","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudUtils"}],"modules":[{"name":"ApphudSDK"}],"symbolKind":"class","externalID":"c:@M@ApphudSDK@objc(cs)ApphudUtils","title":"ApphudUtils","role":"symbol","roleHeading":"Class"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/SQ","doc:\/\/org.cocoapods.ApphudSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudUtils"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudutils"]},{"paths":["\/documentation\/apphudsdk\/apphudutils"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ApphudSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ApphudSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ApphudSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.ApphudSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUtils/enableAllLogs()":{"title":"enableAllLogs()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableAllLogs","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","url":"\/documentation\/apphudsdk\/apphudutils\/enablealllogs()","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/enableAllLogs()","navigatorTitle":[{"kind":"identifier","text":"enableAllLogs"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUtils":{"abstract":[{"text":"This class will contain some utils, more will be added in the future.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudUtils"}],"role":"symbol","kind":"symbol","title":"ApphudUtils","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils","url":"\/documentation\/apphudsdk\/apphudutils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ApphudUtils","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUtils/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol","url":"\/documentation\/apphudsdk\/apphudutils\/init","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/init","abstract":[],"title":"init","type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUtils/useStoreKitV2()":{"navigatorTitle":[{"kind":"identifier","text":"useStoreKitV2"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useStoreKitV2"},{"text":"()","kind":"text"}],"url":"\/documentation\/apphudsdk\/apphudutils\/usestorekitv2()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/useStoreKitV2()","abstract":[],"title":"useStoreKitV2()","type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUtils/sdkVersion()":{"url":"\/documentation\/apphudsdk\/apphudutils\/sdkversion()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sdkVersion","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/sdkVersion()","title":"sdkVersion()","type":"topic","abstract":[],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUtils/enableDebugLogs()":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableDebugLogs","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/enableDebugLogs()","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"enableDebugLogs"}],"url":"\/documentation\/apphudsdk\/apphudutils\/enabledebuglogs()","type":"topic","title":"enableDebugLogs()","abstract":[{"text":"Disables console logging.","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUtils/checkRules()":{"url":"\/documentation\/apphudsdk\/apphudutils\/checkrules()","kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/checkRules()","title":"checkRules()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkRules"},{"text":"()","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"ApphudUtils","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ApphudUtils"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"ApphudUtils","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/enableAllLogs()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/enableDebugLogs()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUtils\/useStoreKitV2()"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudUtils"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUtils~1enableAllLogs()\/title","value":"enableAllLogs"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUtils~1enableAllLogs()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"enableAllLogs"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUtils\/title","value":"ApphudUtils"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUtils\/fragments","value":[{"text":"ApphudUtils","kind":"identifier"}],"op":"replace"},{"value":"useStoreKitV2","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUtils~1useStoreKitV2()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUtils~1useStoreKitV2()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"useStoreKitV2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUtils~1enableDebugLogs()\/title","value":"enableDebugLogs","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"enableDebugLogs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUtils~1enableDebugLogs()\/fragments"}]}]}