{"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/description","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/error","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/isRestoreResult","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/nonRenewingPurchase","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/subscription","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/success","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/transaction","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/userCanceled"],"generated":true,"anchor":"Instance-Properties"}],"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/SQ","doc:\/\/org.cocoapods.ApphudSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","interfaceLanguage":"swift"},"metadata":{"title":"ApphudPurchaseResult","symbolKind":"class","externalID":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","role":"symbol","modules":[{"name":"ApphudSDK"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudPurchaseResult","kind":"identifier"}],"navigatorTitle":[{"text":"ApphudPurchaseResult","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudpurchaseresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudpurchaseresult"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPurchaseResult"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"inlineContent":[{"text":"Using class instead of struct in order to support Objective-C","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://org.cocoapods.ApphudSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPurchaseResult"}],"kind":"symbol","title":"ApphudPurchaseResult","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","navigatorTitle":[{"text":"ApphudPurchaseResult","kind":"identifier"}],"abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphudpurchaseresult"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/SH":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult/error":{"type":"topic","title":"error","url":"\/documentation\/apphudsdk\/apphudpurchaseresult\/error","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"error"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/error","abstract":[{"type":"text","text":"This error can be of three types. Check for error class."}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult/userCanceled":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/userCanceled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"userCanceled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult\/usercanceled","abstract":[{"type":"text","text":"Indicates whether the payment was cancelled by user."}],"type":"topic","title":"userCanceled","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult/success":{"kind":"symbol","title":"success","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/success","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult\/success"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult/transaction":{"kind":"symbol","title":"transaction","navigatorTitle":[{"text":"transaction","kind":"identifier"}],"abstract":[{"text":"Transaction from StoreKit. May be nil, if no transaction made. For example, if couldn’t sign promo offer or couldn’t get App Store receipt.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult\/transaction","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/transaction","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transaction"},{"text":": ","kind":"text"},{"text":"SKPaymentTransaction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKPaymentTransaction"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.ApphudSDK/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult/isRestoreResult":{"title":"isRestoreResult","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRestoreResult"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/isRestoreResult","role":"symbol","url":"\/documentation\/apphudsdk\/apphudpurchaseresult\/isrestoreresult","abstract":[{"type":"text","text":"Indicates whether the purchase result was triggered by a restore action."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult/nonRenewingPurchase":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/nonRenewingPurchase","title":"nonRenewingPurchase","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonRenewingPurchase","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A19NonRenewingPurchaseC","text":"ApphudNonRenewingPurchase"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Standard in-app purchase (non-consumable, consumable or non-renewing subscription) object. May be nil if error occurred or if auto-renewable subscription purchased instead. Nil if "},{"type":"codeVoice","code":"purchaseWithoutValidation"},{"type":"text","text":" method called."}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult\/nonrenewingpurchase","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult/subscription":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/subscription","title":"subscription","kind":"symbol","abstract":[{"type":"text","text":"Autorenewable subscription object. May be nil if error occurred or if non renewing product purchased instead. Nil if "},{"type":"codeVoice","code":"purchaseWithoutValidation"},{"type":"text","text":" method called."}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9ApphudSDK0A12SubscriptionC","text":"ApphudSubscription","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult\/subscription","role":"symbol"},"doc://org.cocoapods.ApphudSDK/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.ApphudSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult/description":{"title":"description","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/description","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","url":"\/documentation\/apphudsdk\/apphudpurchaseresult\/description","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ApphudPurchaseResult","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"ApphudPurchaseResult","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/description","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/error","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/transaction"],"generated":true,"anchor":"Instance-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudPurchaseResult","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title","op":"replace","value":"ApphudPurchaseResult"},{"value":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments"},{"value":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult~1error\/title","op":"replace","value":"error"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult~1error\/fragments","value":[{"text":"error","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult~1transaction\/title","value":"transaction","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult~1transaction\/fragments","value":[{"kind":"identifier","text":"transaction"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult~1description\/title","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult~1description\/fragments"}]}]}