{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudGroup","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ApphudSDK@objc(cs)ApphudGroup","navigatorTitle":[{"kind":"identifier","text":"ApphudGroup"}],"roleHeading":"Class","symbolKind":"class","title":"ApphudGroup","modules":[{"name":"ApphudSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudgroup"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudgroup"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudGroup","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup\/init(from:)"]},{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup\/hasAccess","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup\/name","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup\/products"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup\/encode(to:)"]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/Se","doc:\/\/org.cocoapods.ApphudSDK\/SE","doc:\/\/org.cocoapods.ApphudSDK\/SQ","doc:\/\/org.cocoapods.ApphudSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Apphud class which describes products permission groups"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudGroup/name":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup\/name","title":"name","kind":"symbol","url":"\/documentation\/apphudsdk\/apphudgroup\/name","abstract":[{"type":"text","text":"Name of permission group configured in Apphud Dashboard."}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudGroup/encode(to:)":{"url":"\/documentation\/apphudsdk\/apphudgroup\/encode(to:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup\/encode(to:)","kind":"symbol","type":"topic","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier","text":"Encoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudGroup/hasAccess":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hasAccess","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if this permission group has active subscription. Keep in mind, that this method doesn’t take into account non-renewing purchases."}],"url":"\/documentation\/apphudsdk\/apphudgroup\/hasaccess","kind":"symbol","title":"hasAccess","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup\/hasAccess"},"doc://org.cocoapods.ApphudSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ApphudSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ApphudSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudGroup/init(from:)":{"url":"\/documentation\/apphudsdk\/apphudgroup\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup\/init(from:)","title":"init(from:)","type":"topic","abstract":[],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/Se","title":"Swift.Decodable"},"doc://org.cocoapods.ApphudSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.ApphudSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SE","title":"Swift.Encodable"},"doc://org.cocoapods.ApphudSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudGroup":{"type":"topic","url":"\/documentation\/apphudsdk\/apphudgroup","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ApphudGroup","kind":"identifier"}],"abstract":[{"text":"Apphud class which describes products permission groups","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudGroup"}],"kind":"symbol","title":"ApphudGroup"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudGroup/products":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"products","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct"},{"kind":"text","text":"]"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"You should not operate with products from ApphudGroup directly. Use Paywalls or Paywalls within Placements.","type":"text"}],"title":"products","url":"\/documentation\/apphudsdk\/apphudgroup\/products","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup\/products"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ApphudGroup","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ApphudGroup","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ApphudGroup"}]},{"path":"\/topicSections","op":"replace","value":null},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudGroup","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudGroup\/title","value":"ApphudGroup"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudGroup\/fragments","value":[{"text":"ApphudGroup","kind":"identifier"}],"op":"replace"}]}]}