{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"List of available attribution providers"},{"type":"text","text":" "},{"type":"text","text":"has to make Int in order to support Objective-C"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudAttributionProvider","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudattributionprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudattributionprovider"]}],"sections":[],"metadata":{"modules":[{"name":"ApphudSDK"}],"title":"ApphudAttributionProvider","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ApphudAttributionProvider","kind":"identifier"}],"symbolKind":"enum","navigatorTitle":[{"text":"ApphudAttributionProvider","kind":"identifier"}],"externalID":"c:@M@ApphudSDK@E@ApphudAttributionProvider","role":"symbol"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/adjust","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/appleAdsAttribution","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/appsFlyer","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/custom","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/facebook","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/firebase"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/Equatable-Implementations","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/RawRepresentable-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider"},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/SQ","doc:\/\/org.cocoapods.ApphudSDK\/SH","doc:\/\/org.cocoapods.ApphudSDK\/SY"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/init(rawValue:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/apphudsdk\/apphudattributionprovider\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)","role":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/adjust":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/adjust","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"adjust","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphudattributionprovider\/adjust","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderAdjust"}],"abstract":[],"title":"ApphudAttributionProvider.adjust","role":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","url":"\/documentation\/apphudsdk","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","abstract":[]},"doc://org.cocoapods.ApphudSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SH","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/custom":{"url":"\/documentation\/apphudsdk\/apphudattributionprovider\/custom","navigatorTitle":[{"text":"ApphudAttributionProviderCustom","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Pass custom attribution data to Apphud. Contact your support manager for details."}],"title":"ApphudAttributionProvider.custom","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/custom","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"custom","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/appsFlyer":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/appsFlyer","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appsFlyer"}],"url":"\/documentation\/apphudsdk\/apphudattributionprovider\/appsflyer","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderAppsFlyer"}],"abstract":[],"title":"ApphudAttributionProvider.appsFlyer","role":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/firebase":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"firebase","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/firebase","title":"ApphudAttributionProvider.firebase","type":"topic","url":"\/documentation\/apphudsdk\/apphudattributionprovider\/firebase","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderFirebase"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/apphudsdk\/apphudattributionprovider\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/RawRepresentable-Implementations"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/Equatable-Implementations","abstract":[],"type":"topic","url":"\/documentation\/apphudsdk\/apphudattributionprovider\/equatable-implementations"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider":{"url":"\/documentation\/apphudsdk\/apphudattributionprovider","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider","abstract":[{"type":"text","text":"List of available attribution providers"},{"type":"text","text":" "},{"text":"has to make Int in order to support Objective-C","type":"text"}],"kind":"symbol","type":"topic","title":"ApphudAttributionProvider","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudAttributionProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ApphudAttributionProvider","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SQ","type":"unresolvable"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/ApphudAttributionProviderAppleSearchAds":{"abstract":[],"kind":"symbol","fragments":[{"kind":"identifier","text":"ApphudAttributionProviderAppleSearchAds"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/ApphudAttributionProviderAppleSearchAds","title":"ApphudAttributionProviderAppleSearchAds","type":"topic","url":"\/documentation\/apphudsdk\/apphudattributionprovider\/apphudattributionproviderapplesearchads","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/appleAdsAttribution":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/appleAdsAttribution","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appleAdsAttribution"}],"url":"\/documentation\/apphudsdk\/apphudattributionprovider\/appleadsattribution","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderAppleAdsAttribution"}],"abstract":[],"title":"ApphudAttributionProvider.appleAdsAttribution","role":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/facebook":{"url":"\/documentation\/apphudsdk\/apphudattributionprovider\/facebook","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/facebook","abstract":[],"kind":"symbol","type":"topic","title":"ApphudAttributionProvider.facebook","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"facebook","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderFacebook"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ApphudAttributionProvider"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudAttributionProvider"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ApphudAttributionProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/ApphudAttributionProviderAppleSearchAds","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/adjust","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/appleAdsAttribution","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/appsFlyer","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/custom","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/facebook","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/firebase"],"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudAttributionProvider","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}]}]}},{"value":"ApphudAttributionProviderAdjust","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1adjust\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1adjust\/fragments","op":"replace","value":[{"text":"ApphudAttributionProviderAdjust","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1custom\/title","op":"replace","value":"ApphudAttributionProviderCustom"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1custom\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudAttributionProviderCustom"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1appsFlyer\/title","op":"replace","value":"ApphudAttributionProviderAppsFlyer"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1appsFlyer\/fragments","value":[{"kind":"identifier","text":"ApphudAttributionProviderAppsFlyer"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1firebase\/title","op":"replace","value":"ApphudAttributionProviderFirebase"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1firebase\/fragments","value":[{"text":"ApphudAttributionProviderFirebase","kind":"identifier"}]},{"value":"ApphudAttributionProvider","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/fragments","value":[{"text":"ApphudAttributionProvider","kind":"identifier"}],"op":"replace"},{"value":"ApphudAttributionProviderAppleAdsAttribution","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1appleAdsAttribution\/title"},{"value":[{"kind":"identifier","text":"ApphudAttributionProviderAppleAdsAttribution"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1appleAdsAttribution\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1facebook\/title","value":"ApphudAttributionProviderFacebook"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1facebook\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudAttributionProviderFacebook"}]}]}]}