{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudReceipt"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphudreceipt"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudreceipt"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ApphudSDK\/Se","doc:\/\/org.cocoapods.ApphudSDK\/SE","doc:\/\/org.cocoapods.ApphudSDK\/SQ","doc:\/\/org.cocoapods.ApphudSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"ApphudReceipt"},{"type":"text","text":" is Apphud’s wrapper around StoreKit’s "},{"type":"codeVoice","code":"Receipt"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudReceipt"}],"title":"ApphudReceipt","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ApphudSDK@objc(cs)ApphudReceipt","modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudReceipt"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/applicationVersion","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/bundleId","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/originalApplicationVersion","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/originalPurchaseDate","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/rawJSON","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/receiptCreationDate"]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt/rawJSON":{"role":"symbol","title":"rawJSON","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawJSON"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Raw receipt JSON"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/rawJSON","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rawJSON"}],"url":"\/documentation\/apphudsdk\/apphudreceipt\/rawjson"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk\/apphudreceipt\/init(from:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[{"type":"text","text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SE"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt/receiptCreationDate":{"role":"symbol","title":"receiptCreationDate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiptCreationDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The time the App Store generated the receipt."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/receiptCreationDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"receiptCreationDate"}],"url":"\/documentation\/apphudsdk\/apphudreceipt\/receiptcreationdate"},"doc://org.cocoapods.ApphudSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt/originalPurchaseDate":{"role":"symbol","title":"originalPurchaseDate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalPurchaseDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The time of the original app purchase. Value is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" in StoreKit Testing generated receipts."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/originalPurchaseDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"originalPurchaseDate"}],"url":"\/documentation\/apphudsdk\/apphudreceipt\/originalpurchasedate"},"doc://org.cocoapods.ApphudSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt/applicationVersion":{"role":"symbol","title":"applicationVersion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The app’s version number. The app’s version number corresponds to the value of CFBundleVersion (in iOS) or CFBundleShortVersionString (in macOS) in the Info.plist. In production, this value is the current version of the app on the device based on the receipt_creation_date_ms. In the sandbox, the value is always “1.0”."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/applicationVersion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationVersion"}],"url":"\/documentation\/apphudsdk\/apphudreceipt\/applicationversion"},"doc://org.cocoapods.ApphudSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"},"doc://org.cocoapods.ApphudSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SQ"},"doc://org.cocoapods.ApphudSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/objc(pl)NSObject"},"doc://org.cocoapods.ApphudSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/Se"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt/originalApplicationVersion":{"role":"symbol","title":"originalApplicationVersion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalApplicationVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The version of the app that the user originally purchased. This value does not change, and corresponds to the value of CFBundleVersion (in iOS) or CFBundleShortVersionString (in macOS) in the Info.plist file of the original purchase. In the sandbox environment, the value is always “1.0”."},{"type":"text","text":" "},{"type":"text","text":"Value is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" in StoreKit Testing generated receipts."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/originalApplicationVersion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"originalApplicationVersion"}],"url":"\/documentation\/apphudsdk\/apphudreceipt\/originalapplicationversion"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt/bundleId":{"role":"symbol","title":"bundleId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The bundle identifier for the app to which the receipt belongs."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/bundleId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bundleId"}],"url":"\/documentation\/apphudsdk\/apphudreceipt\/bundleid"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt":{"role":"symbol","title":"ApphudReceipt","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudReceipt"}],"abstract":[{"type":"codeVoice","code":"ApphudReceipt"},{"type":"text","text":" is Apphud’s wrapper around StoreKit’s "},{"type":"codeVoice","code":"Receipt"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudReceipt"}],"url":"\/documentation\/apphudsdk\/apphudreceipt"},"doc://org.cocoapods.ApphudSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/s7CVarArgP"},"doc://org.cocoapods.ApphudSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ApphudReceipt"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ApphudReceipt"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ApphudReceipt"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/applicationVersion","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/bundleId","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/originalApplicationVersion","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/originalPurchaseDate","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/rawJSON","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/receiptCreationDate"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudReceipt"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1rawJSON\/title","value":"rawJSON"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1rawJSON\/fragments","value":[{"kind":"identifier","text":"rawJSON"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1receiptCreationDate\/title","value":"receiptCreationDate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1receiptCreationDate\/fragments","value":[{"kind":"identifier","text":"receiptCreationDate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1originalPurchaseDate\/title","value":"originalPurchaseDate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1originalPurchaseDate\/fragments","value":[{"kind":"identifier","text":"originalPurchaseDate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1applicationVersion\/title","value":"applicationVersion"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1applicationVersion\/fragments","value":[{"kind":"identifier","text":"applicationVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1originalApplicationVersion\/title","value":"originalApplicationVersion"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1originalApplicationVersion\/fragments","value":[{"kind":"identifier","text":"originalApplicationVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1bundleId\/title","value":"bundleId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1bundleId\/fragments","value":[{"kind":"identifier","text":"bundleId"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt\/title","value":"ApphudReceipt"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt\/fragments","value":[{"kind":"identifier","text":"ApphudReceipt"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}