{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudDidFetchStoreKitProducts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"products"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method gets called when products are fetched from App Store. Returns optional Error from StoreKit, if exists."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/apphuddidfetchstorekitproducts(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/apphuddidfetchstorekitproducts(_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidFetchStoreKitProducts(_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Deprecated. Use "},{"type":"codeVoice","code":"func getPaywalls"},{"type":"text","text":" method instead."}],"kind":"symbol","metadata":{"modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"apphudDidFetchStoreKitProducts::"}],"role":"symbol","title":"apphudDidFetchStoreKitProducts(_:_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudDidFetchStoreKitProducts"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(pl)ApphudDelegate(im)apphudDidFetchStoreKitProducts::","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.14.4","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"seeAlsoSections":[{"title":"ApphudDelegate main methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudSubscriptionsUpdated(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudNonRenewingPurchasesUpdated(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidChangeUserID(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudShouldStartAppStoreDirectPurchase(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidObservePurchase(result:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/handleDeferredTransaction(transaction:)"],"generated":true}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudDidFetchStoreKitProducts(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"apphudDidFetchStoreKitProducts::"}],"role":"symbol","title":"apphudDidFetchStoreKitProducts(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudDidFetchStoreKitProducts"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Deprecated. Use "},{"type":"codeVoice","code":"func getPaywalls"},{"type":"text","text":" method instead."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidFetchStoreKitProducts(_:_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/apphudsdk\/apphuddelegate\/apphuddidfetchstorekitproducts(_:_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[{"type":"text","text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/handleDeferredTransaction(transaction:)":{"role":"symbol","title":"handleDeferredTransaction(transaction:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleDeferredTransaction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transaction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SKPaymentTransaction","preciseIdentifier":"c:objc(cs)SKPaymentTransaction"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when Apphud SDK detects a deferred or interrupted purchase, this may happen when SCA confirmation is needed, in the case of parental control and some other cases"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/handleDeferredTransaction(transaction:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleDeferredTransactionWithTransaction:"}],"url":"\/documentation\/apphudsdk\/apphuddelegate\/handledeferredtransaction(transaction:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudDidObservePurchase(result:)":{"navigatorTitle":[{"kind":"identifier","text":"apphudDidObservePurchaseWithResult:"}],"role":"symbol","title":"apphudDidObservePurchase(result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudDidObservePurchase"},{"kind":"text","text":"("},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Called when Apphud SDK detects a purchase that was made outside of Apphud SDK purchase methods. It is also useful to intercept purchases made using Promo Codes for in-app purchases. If user redeems promo code for in-app purchase in the App Store, then opens the app, this delegate method will be called, so you will be able to handle successful payment on your side."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidObservePurchase(result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/apphudsdk\/apphuddelegate\/apphuddidobservepurchase(result:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudSubscriptionsUpdated(_:)":{"navigatorTitle":[{"kind":"identifier","text":"apphudSubscriptionsUpdated:"}],"role":"symbol","title":"apphudSubscriptionsUpdated(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudSubscriptionsUpdated"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ApphudSubscription","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudSubscription"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Returns array of subscriptions that user ever purchased. Empty array means user never purchased a subscription. If you have just one subscription group in your app, you will always receive just one subscription in an array."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudSubscriptionsUpdated(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudsubscriptionsupdated(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudDidChangeUserID(_:)":{"role":"symbol","title":"apphudDidChangeUserID(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudDidChangeUserID"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when user ID has been changed. Use this if you implement integrations with Analytics services."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidChangeUserID(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"apphudDidChangeUserID:"}],"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphuddidchangeuserid(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudShouldStartAppStoreDirectPurchase(_:)":{"role":"symbol","title":"apphudShouldStartAppStoreDirectPurchase(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":") -> (("},{"kind":"typeIdentifier","text":"ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Implements mechanism of purchasing In-App Purchase initiated directly from the App Store page."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudShouldStartAppStoreDirectPurchase(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase:"}],"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudshouldstartappstoredirectpurchase(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudNonRenewingPurchasesUpdated(_:)":{"navigatorTitle":[{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated:"}],"role":"symbol","title":"apphudNonRenewingPurchasesUpdated(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ApphudNonRenewingPurchase","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudNonRenewingPurchase"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Called when any of non renewing purchases changes. Called when purchase is made or has been refunded."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudNonRenewingPurchasesUpdated(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudnonrenewingpurchasesupdated(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"apphudDidFetchStoreKitProducts::"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudDidFetchStoreKitProducts::"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"ApphudDelegate main methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudSubscriptionsUpdated(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudNonRenewingPurchasesUpdated(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidChangeUserID(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudShouldStartAppStoreDirectPurchase(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidObservePurchase(result:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/handleDeferredTransaction(transaction:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"apphudDidFetchStoreKitProducts:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SKProduct *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"products"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudDidFetchStoreKitProducts(_:_:)\/title","value":"apphudDidFetchStoreKitProducts::"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudDidFetchStoreKitProducts(_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudDidFetchStoreKitProducts::"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1handleDeferredTransaction(transaction:)\/title","value":"handleDeferredTransactionWithTransaction:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1handleDeferredTransaction(transaction:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleDeferredTransactionWithTransaction:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudDidObservePurchase(result:)\/title","value":"apphudDidObservePurchaseWithResult:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudDidObservePurchase(result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudDidObservePurchaseWithResult:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudSubscriptionsUpdated(_:)\/title","value":"apphudSubscriptionsUpdated:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudSubscriptionsUpdated(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudSubscriptionsUpdated:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudDidChangeUserID(_:)\/title","value":"apphudDidChangeUserID:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudDidChangeUserID(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudDidChangeUserID:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudShouldStartAppStoreDirectPurchase(_:)\/title","value":"apphudShouldStartAppStoreDirectPurchase:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudShouldStartAppStoreDirectPurchase(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudNonRenewingPurchasesUpdated(_:)\/title","value":"apphudNonRenewingPurchasesUpdated:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudNonRenewingPurchasesUpdated(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}