{"variants":[{"paths":["\/documentation\/apphudsdk\/apphudpurchaseresult\/isrestoreresult"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"title":"isRestoreResult","modules":[{"name":"ApphudSDK"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isRestoreResult","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol","externalID":"s:9ApphudSDK0A14PurchaseResultC09isRestoreD0Sbvp"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/isRestoreResult","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult"]]},"abstract":[{"type":"text","text":"Indicates whether the purchase result was triggered by a restore action."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRestoreResult","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult/isRestoreResult":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isRestoreResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/isRestoreResult","abstract":[{"text":"Indicates whether the purchase result was triggered by a restore action.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult\/isrestoreresult","title":"isRestoreResult","role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","role":"collection","url":"\/documentation\/apphudsdk","abstract":[{"type":"text","text":"Apphud is an all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams make the right decisions based on data and tools."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"type":"topic","title":"ApphudPurchaseResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPurchaseResult"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","navigatorTitle":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"kind":"symbol","abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title","value":"ApphudPurchaseResult"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudPurchaseResult"}]},{"value":[{"text":"ApphudPurchaseResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/navigatorTitle"}]}]}