{"metadata":{"externalID":"s:9ApphudSDK0A14PurchaseResultC13transactionV28StoreKit11TransactionVSgvp","modules":[{"name":"ApphudSDK"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"transactionV2","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Transaction","preciseIdentifier":"s:8StoreKit11TransactionV"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol","title":"transactionV2"},"variants":[{"paths":["\/documentation\/apphudsdk\/apphudpurchaseresult\/transactionv2"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Transaction from StoreKit2. May be nil, if no transaction made."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/transactionV2","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionV2"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8StoreKit11TransactionV","kind":"typeIdentifier","text":"Transaction"},{"text":"?","kind":"text"}]}]}],"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","navigatorTitle":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult","kind":"symbol","abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"title":"ApphudPurchaseResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPurchaseResult"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult/transactionV2":{"type":"topic","url":"\/documentation\/apphudsdk\/apphudpurchaseresult\/transactionv2","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/transactionV2","abstract":[{"text":"Transaction from StoreKit2. May be nil, if no transaction made.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionV2","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8StoreKit11TransactionV","kind":"typeIdentifier","text":"Transaction"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","title":"transactionV2"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title","op":"replace","value":"ApphudPurchaseResult"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments","op":"replace","value":[{"text":"ApphudPurchaseResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ApphudPurchaseResult"}]}]}]}