{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"transaction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SKPaymentTransaction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKPaymentTransaction"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/transaction","interfaceLanguage":"swift"},"abstract":[{"text":"Transaction from StoreKit. May be nil, if no transaction made. For example, if couldn’t sign promo offer or couldn’t get App Store receipt.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudpurchaseresult\/transaction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudpurchaseresult\/transaction"]}],"metadata":{"externalID":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult(py)transaction","role":"symbol","title":"transaction","roleHeading":"Instance Property","modules":[{"name":"ApphudSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"transaction","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SKPaymentTransaction","preciseIdentifier":"c:objc(cs)SKPaymentTransaction"},{"kind":"text","text":"?"}],"symbolKind":"property","navigatorTitle":[{"text":"transaction","kind":"identifier"}]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"type":"topic","url":"\/documentation\/apphudsdk\/apphudpurchaseresult","abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"title":"ApphudPurchaseResult","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPurchaseResult"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","navigatorTitle":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult/transaction":{"navigatorTitle":[{"kind":"identifier","text":"transaction"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult\/transaction","title":"transaction","role":"symbol","url":"\/documentation\/apphudsdk\/apphudpurchaseresult\/transaction","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transaction"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKPaymentTransaction","kind":"typeIdentifier","text":"SKPaymentTransaction"},{"text":"?","kind":"text"}],"abstract":[{"text":"Transaction from StoreKit. May be nil, if no transaction made. For example, if couldn’t sign promo offer or couldn’t get App Store receipt.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"transaction","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"transaction"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SKPaymentTransaction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKPaymentTransaction"},{"kind":"text","text":" * "},{"kind":"identifier","text":"transaction"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title","value":"ApphudPurchaseResult","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments","value":[{"text":"ApphudPurchaseResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult~1transaction\/title","op":"replace","value":"transaction"},{"op":"replace","value":[{"kind":"identifier","text":"transaction"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult~1transaction\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}