{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAttribution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"provider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider","preciseIdentifier":"c:@M@ApphudSDK@E@ApphudAttributionProvider","text":"ApphudAttributionProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"identifer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","text":"ApphudBoolCallback"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Required. Attribution dictionary."}]}]},{"name":"provider","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Required. Attribution provider name. Available values: .appsFlyer. Will be added more soon."}]}]},{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. Identifier that matches Apphud and Attrubution provider. Required for AppsFlyer."}]}]},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. Returns true if successfully sent."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/addattribution(data:from:identifer:callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/addattribution(data:from:identifer:callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Submit attribution data to Apphud from your attribution network provider."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAttribution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudAttributionProvider","preciseIdentifier":"c:@M@ApphudSDK@E@ApphudAttributionProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"identifer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudBoolCallback","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"kind":"text","text":"?)"}],"title":"addAttribution(data:from:identifer:callback:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)addAttributionWithData:from:identifer:callback:","modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addAttributionWithData:from:identifer:callback:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudBoolCallback":{"role":"symbol","title":"ApphudBoolCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudBoolCallback"}],"abstract":[{"type":"text","text":"Public Callback object provide -> Bool"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudBoolCallback"}],"url":"\/documentation\/apphudsdk\/apphudboolcallback"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"role":"symbol","title":"Apphud","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/addAttribution(data:from:identifer:callback:)":{"role":"symbol","title":"addAttribution(data:from:identifer:callback:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAttribution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudAttributionProvider","preciseIdentifier":"c:@M@ApphudSDK@E@ApphudAttributionProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"identifer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudBoolCallback","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Submit attribution data to Apphud from your attribution network provider."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addAttributionWithData:from:identifer:callback:"}],"url":"\/documentation\/apphudsdk\/apphud\/addattribution(data:from:identifer:callback:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider":{"role":"symbol","title":"ApphudAttributionProvider","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudAttributionProvider"}],"abstract":[{"type":"text","text":"List of available attribution providers"},{"type":"text","text":" "},{"type":"text","text":"has to make Int in order to support Objective-C"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProvider"}],"url":"\/documentation\/apphudsdk\/apphudattributionprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"addAttributionWithData:from:identifer:callback:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addAttributionWithData:from:identifer:callback:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addAttributionWithData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"from:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider","preciseIdentifier":"c:@M@ApphudSDK@E@ApphudAttributionProvider","text":"ApphudAttributionProvider"},{"kind":"text","text":")"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"identifer"},{"kind":"text","text":" "},{"kind":"identifier","text":"callback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(_Bool)","preciseIdentifier":"c:BFv(#b)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"kind":"identifier","text":"Apphud"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1addAttribution(data:from:identifer:callback:)\/title","value":"addAttributionWithData:from:identifer:callback:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1addAttribution(data:from:identifer:callback:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addAttributionWithData:from:identifer:callback:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/title","value":"ApphudAttributionProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/fragments","value":[{"kind":"identifier","text":"ApphudAttributionProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}