{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudProductFor","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"product","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8StoreKit7ProductV","kind":"typeIdentifier","text":"Product"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","kind":"typeIdentifier","text":"ApphudProduct"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"product","content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"Product","type":"codeVoice"},{"text":" struct from StoreKit 2.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An optional ","type":"text"},{"code":"ApphudProduct","type":"codeVoice"},{"type":"text","text":" struct that matches the given "},{"type":"codeVoice","code":"Product"},{"type":"text","text":" struct."}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/apphudProductFor(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Retrieves the corresponding "},{"type":"codeVoice","code":"ApphudProduct"},{"text":" for a given StoreKit 2 ","type":"text"},{"type":"codeVoice","code":"Product"},{"type":"text","text":" struct, if it exists."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/apphudproductfor(_:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudProductFor"},{"kind":"text","text":"("},{"text":"Product","kind":"typeIdentifier","preciseIdentifier":"s:8StoreKit7ProductV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","kind":"typeIdentifier","text":"ApphudProduct"},{"text":"?","kind":"text"}],"externalID":"s:9ApphudSDK0A0C16apphudProductForyAA0aD0CSg8StoreKit0D0VFZ","symbolKind":"method","modules":[{"name":"ApphudSDK"}],"role":"symbol","roleHeading":"Type Method","platforms":[{"name":"iOS","introducedAt":"15.0","deprecated":false,"unavailable":false,"beta":false},{"name":"macOS","introducedAt":"12.0","deprecated":false,"beta":false,"unavailable":false},{"deprecated":false,"unavailable":false,"name":"tvOS","beta":false,"introducedAt":"15.0"},{"name":"watchOS","introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false}],"title":"apphudProductFor(_:)"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct":{"navigatorTitle":[{"kind":"identifier","text":"ApphudProduct"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","type":"topic","url":"\/documentation\/apphudsdk\/apphudproduct","kind":"symbol","abstract":[{"type":"text","text":"Apphud’s wrapper around "},{"code":"SKProduct","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudProduct"}],"role":"symbol","title":"ApphudProduct"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/apphudProductFor(_:)":{"title":"apphudProductFor(_:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Retrieves the corresponding "},{"code":"ApphudProduct","type":"codeVoice"},{"text":" for a given StoreKit 2 ","type":"text"},{"code":"Product","type":"codeVoice"},{"type":"text","text":" struct, if it exists."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudProductFor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Product","kind":"typeIdentifier","preciseIdentifier":"s:8StoreKit7ProductV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct"},{"text":"?","kind":"text"}],"url":"\/documentation\/apphudsdk\/apphud\/apphudproductfor(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/apphudProductFor(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ApphudProduct","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/title","op":"replace"},{"value":[{"text":"ApphudProduct","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/fragments","op":"replace"},{"op":"replace","value":"Apphud","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"kind":"identifier","text":"Apphud"}]}]}]}