{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/attributeFromWeb(data:callback:)"},"abstract":[{"type":"text","text":"Web-to-Web flow only. Attempts to attribute the user with the provided attribution data."},{"text":" ","type":"text"},{"type":"text","text":"If the "},{"code":"data","type":"codeVoice"},{"type":"text","text":" parameter contains either "},{"type":"codeVoice","code":"aph_user_id"},{"type":"text","text":", "},{"type":"codeVoice","code":"apphud_user_id"},{"type":"text","text":",  "},{"type":"codeVoice","code":"email"},{"text":" or ","type":"text"},{"code":"apphud_user_email","type":"codeVoice"},{"text":", the SDK will submit this information to the Apphud server.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The server will return a restored web user if found; otherwise, the callback will return "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attributeFromWeb"},{"kind":"text","text":"("},{"text":"data","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ApphudUser","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A4UserV","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUser"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A dictionary containing the attribution data."}]}],"name":"data"},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure that returns a boolean indicating whether the web attribution was successful, and the updated "},{"type":"codeVoice","code":"ApphudUser"},{"type":"text","text":" object."}]}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Important:"}]},{"text":" If the callback returns ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":", it doesn’t mean the user has premium access, you should still call "},{"code":"Apphud.hasPremiumAccess()","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Additionally, the delegate methods ","type":"text"},{"code":"apphudSubscriptionsUpdated","type":"codeVoice"},{"type":"text","text":" and "},{"code":"apphudDidChangeUserID","type":"codeVoice"},{"text":" may be called.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"The callback returns ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the user is successfully attributed via the web and includes the updated "},{"code":"ApphudUser","type":"codeVoice"},{"type":"text","text":" object."},{"text":" ","type":"text"},{"type":"text","text":"After this callback, you can check the "},{"type":"codeVoice","code":"Apphud.hasPremiumAccess()"},{"type":"text","text":" method, which should return "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the user has premium access."}],"type":"paragraph"}]}],"metadata":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attributeFromWeb"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A4UserV","text":"ApphudUser"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:9ApphudSDK0A0C16attributeFromWeb4data8callbackySDys11AnyHashableVypG_ySb_AA0A4UserVSgtctFZ","title":"attributeFromWeb(data:callback:)","symbolKind":"method","modules":[{"name":"ApphudSDK"}],"roleHeading":"Type Method"},"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/attributefromweb(data:callback:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/attributeFromWeb(data:callback:)":{"title":"attributeFromWeb(data:callback:)","type":"topic","abstract":[{"type":"text","text":"Web-to-Web flow only. Attempts to attribute the user with the provided attribution data."},{"type":"text","text":" "},{"text":"If the ","type":"text"},{"type":"codeVoice","code":"data"},{"text":" parameter contains either ","type":"text"},{"code":"aph_user_id","type":"codeVoice"},{"text":", ","type":"text"},{"code":"apphud_user_id","type":"codeVoice"},{"type":"text","text":",  "},{"type":"codeVoice","code":"email"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"apphud_user_email"},{"type":"text","text":", the SDK will submit this information to the Apphud server."},{"type":"text","text":" "},{"text":"The server will return a restored web user if found; otherwise, the callback will return ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/attributeFromWeb(data:callback:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attributeFromWeb"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"ApphudUser","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A4UserV"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"url":"\/documentation\/apphudsdk\/apphud\/attributefromweb(data:callback:)","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"url":"\/documentation\/apphudsdk\/apphud","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","title":"Apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUser":{"title":"ApphudUser","url":"\/documentation\/apphudsdk\/apphuduser","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUser","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ApphudUser","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ApphudUser","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"Apphud","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title"},{"value":[{"text":"Apphud","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","value":[{"kind":"identifier","text":"Apphud"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}