{"metadata":{"navigatorTitle":[{"text":"checkEligibilityForIntroductoryOfferWithProduct:callback:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkEligibilityForIntroductoryOffer"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"product"},{"kind":"text","text":": "},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"text":")","kind":"text"}],"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)checkEligibilityForIntroductoryOfferWithProduct:callback:","modules":[{"name":"ApphudSDK"}],"symbolKind":"method","roleHeading":"Type Method","title":"checkEligibilityForIntroductoryOffer(product:callback:)","role":"symbol"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Checks whether the given product is eligible for an introductory offer, which includes "},{"type":"codeVoice","code":"free trial"},{"text":", ","type":"text"},{"code":"pay as you go","type":"codeVoice"},{"text":", or ","type":"text"},{"type":"codeVoice","code":"pay up front"},{"text":" options.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/checkeligibilityforintroductoryoffer(product:callback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/checkeligibilityforintroductoryoffer(product:callback:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkEligibilityForIntroductoryOffer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"product"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"product","content":[{"inlineContent":[{"type":"text","text":"Required. The "},{"code":"SKProduct","type":"codeVoice"},{"type":"text","text":" object for which you want to check introductory offer eligibility."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"A closure that returns ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if the product is eligible for an introductory offer.","type":"text"}],"type":"paragraph"}],"name":"callback"}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Eligibility criteria:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"New subscribers are always eligible."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Lapsed subscribers who renew are eligible if they haven’t previously used an introductory offer for the given product or any product within the same subscription group."}],"type":"paragraph"}]}],"type":"unorderedList"},{"content":[{"type":"paragraph","inlineContent":[{"text":"This check is essential for offering introductory prices correctly according to Apple’s guidelines.","type":"text"}]}],"style":"note","type":"aside","name":"Note"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudBoolCallback":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback","kind":"symbol","title":"ApphudBoolCallback","abstract":[{"text":"Public Callback object provide -> Bool","type":"text"}],"navigatorTitle":[{"text":"ApphudBoolCallback","kind":"identifier"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphudboolcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudBoolCallback"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"url":"\/documentation\/apphudsdk\/apphud","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","title":"Apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/checkEligibilityForIntroductoryOffer(product:callback:)":{"abstract":[{"type":"text","text":"Checks whether the given product is eligible for an introductory offer, which includes "},{"code":"free trial","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"pay as you go"},{"type":"text","text":", or "},{"type":"codeVoice","code":"pay up front"},{"type":"text","text":" options."}],"title":"checkEligibilityForIntroductoryOffer(product:callback:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"checkEligibilityForIntroductoryOffer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"product"},{"kind":"text","text":": "},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","text":"ApphudBoolCallback"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphud\/checkeligibilityforintroductoryoffer(product:callback:)","navigatorTitle":[{"text":"checkEligibilityForIntroductoryOfferWithProduct:callback:","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"checkEligibilityForIntroductoryOfferWithProduct:callback:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"checkEligibilityForIntroductoryOfferWithProduct:callback:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"checkEligibilityForIntroductoryOfferWithProduct:"},{"text":"(","kind":"text"},{"text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"product"},{"text":" ","kind":"text"},{"text":"callback:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"product","content":[{"inlineContent":[{"type":"text","text":"Required. The "},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":" object for which you want to check introductory offer eligibility."}],"type":"paragraph"}]},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure that returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the product is eligible for an introductory offer."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"value":[{"text":"Apphud","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","op":"replace","value":[{"text":"Apphud","kind":"identifier"}]},{"value":"checkEligibilityForIntroductoryOfferWithProduct:callback:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForIntroductoryOffer(product:callback:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForIntroductoryOffer(product:callback:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"checkEligibilityForIntroductoryOfferWithProduct:callback:","kind":"identifier"}]}]}]}