{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/checkeligibilityforpromotionaloffer(product:callback:)"]},{"paths":["\/documentation\/apphudsdk\/apphud\/checkeligibilityforpromotionaloffer(product:callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"metadata":{"roleHeading":"Type Method","title":"checkEligibilityForPromotionalOffer(product:callback:)","navigatorTitle":[{"text":"checkEligibilityForPromotionalOfferWithProduct:callback:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)checkEligibilityForPromotionalOfferWithProduct:callback:","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkEligibilityForPromotionalOffer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"product"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"text":")","kind":"text"}],"modules":[{"name":"ApphudSDK"}]},"abstract":[{"text":"Checks whether the given product is eligible for any of its promotional offers.","type":"text"}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkEligibilityForPromotionalOffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","text":"ApphudBoolCallback"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"product","content":[{"type":"paragraph","inlineContent":[{"text":"Required. The ","type":"text"},{"code":"SKProduct","type":"codeVoice"},{"type":"text","text":" object for which you want to check promotional offer eligibility."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A closure that returns ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if the product is eligible for any of its promotional offers.","type":"text"}]}],"name":"callback"}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Eligibility criteria:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Only customers who have already purchased a subscription are eligible for promotional offers for the given product or any product within the same subscription group."}],"type":"paragraph"}]}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this method to determine if a user can be offered a discount on a subscription renewal or upgrade."}]}],"type":"aside","name":"Note"}]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/checkEligibilityForPromotionalOffer(product:callback:)":{"kind":"symbol","title":"checkEligibilityForPromotionalOffer(product:callback:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)","abstract":[{"type":"text","text":"Checks whether the given product is eligible for any of its promotional offers."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"checkEligibilityForPromotionalOfferWithProduct:callback:"}],"url":"\/documentation\/apphudsdk\/apphud\/checkeligibilityforpromotionaloffer(product:callback:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"checkEligibilityForPromotionalOffer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"product"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"text":"ApphudBoolCallback","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudBoolCallback":{"abstract":[{"text":"Public Callback object provide -> Bool","type":"text"}],"kind":"symbol","role":"symbol","title":"ApphudBoolCallback","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback","type":"topic","url":"\/documentation\/apphudsdk\/apphudboolcallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ApphudBoolCallback","kind":"identifier"}],"navigatorTitle":[{"text":"ApphudBoolCallback","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"checkEligibilityForPromotionalOfferWithProduct:callback:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"checkEligibilityForPromotionalOfferWithProduct:callback:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"checkEligibilityForPromotionalOfferWithProduct:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":" *) ","kind":"text"},{"text":"product","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"callback:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#b)","text":"void (^)(_Bool)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"Apphud","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","op":"replace","value":[{"kind":"identifier","text":"Apphud"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForPromotionalOffer(product:callback:)\/title","op":"replace","value":"checkEligibilityForPromotionalOfferWithProduct:callback:"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForPromotionalOffer(product:callback:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"checkEligibilityForPromotionalOfferWithProduct:callback:","kind":"identifier"}],"op":"replace"}]}]}