{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/checkeligibilitiesforintroductoryoffers(products:callback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/checkeligibilitiesforintroductoryoffers(products:callback:)"]}],"abstract":[{"text":"Checks the eligibility for introductory offers for multiple products simultaneously.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilitiesForIntroductoryOffers(products:callback:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)checkEligibilitiesForIntroductoryOffersWithProducts:callback:","title":"checkEligibilitiesForIntroductoryOffers(products:callback:)","modules":[{"name":"ApphudSDK"}],"role":"symbol","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkEligibilitiesForIntroductoryOffers","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"products"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9ApphudSDK0A19EligibilityCallbacka","text":"ApphudEligibilityCallback","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"checkEligibilitiesForIntroductoryOffersWithProducts:callback:"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"checkEligibilitiesForIntroductoryOffers","kind":"identifier"},{"text":"(","kind":"text"},{"text":"products","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudEligibilityCallback","text":"ApphudEligibilityCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A19EligibilityCallbacka"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Required. An array of ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":" objects for which you want to check introductory offers eligibility."}],"type":"paragraph"}],"name":"products"},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure that returns a dictionary with product identifiers as keys and boolean values indicating eligibility."}]}]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"Use this method to efficiently determine introductory offer eligibility for a range of products, aiding in dynamic pricing and offer strategies."}],"type":"paragraph"}],"name":"Note","style":"note"}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/checkEligibilitiesForIntroductoryOffers(products:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilitiesForIntroductoryOffers(products:callback:)","url":"\/documentation\/apphudsdk\/apphud\/checkeligibilitiesforintroductoryoffers(products:callback:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkEligibilitiesForIntroductoryOffers","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"products"},{"kind":"text","text":": ["},{"text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudEligibilityCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A19EligibilityCallbacka"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"text":"Checks the eligibility for introductory offers for multiple products simultaneously.","type":"text"}],"kind":"symbol","type":"topic","title":"checkEligibilitiesForIntroductoryOffers(products:callback:)","navigatorTitle":[{"text":"checkEligibilitiesForIntroductoryOffersWithProducts:callback:","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudEligibilityCallback":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudEligibilityCallback","title":"ApphudEligibilityCallback","role":"symbol","abstract":[{"text":"Public Callback object provide -> [String: Bool]","type":"text"}],"kind":"symbol","url":"\/documentation\/apphudsdk\/apphudeligibilitycallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudEligibilityCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudEligibilityCallback"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"checkEligibilitiesForIntroductoryOffersWithProducts:callback:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"checkEligibilitiesForIntroductoryOffersWithProducts:callback:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"checkEligibilitiesForIntroductoryOffersWithProducts:"},{"kind":"text","text":"("},{"text":"NSArray<SKProduct *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"products"},{"kind":"text","text":" "},{"text":"callback:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(NSDictionary<NSString *,NSNumber *> *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSDictionary)"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"checkEligibilitiesForIntroductoryOffersWithProducts:callback:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilitiesForIntroductoryOffers(products:callback:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilitiesForIntroductoryOffers(products:callback:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"checkEligibilitiesForIntroductoryOffersWithProducts:callback:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud","op":"replace"},{"value":[{"text":"Apphud","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}