{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkEligibilitiesForPromotionalOffers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"products"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudEligibilityCallback","preciseIdentifier":"s:9ApphudSDK0A19EligibilityCallbacka","text":"ApphudEligibilityCallback"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"products","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Required. This is an array of "},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":" objects for which you want to check promo offers eligibilities."}]}]},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns dictionary with product identifiers and boolean values."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/checkeligibilitiesforpromotionaloffers(products:callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/checkeligibilitiesforpromotionaloffers(products:callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilitiesForPromotionalOffers(products:callback:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Checks promotional offers eligibility for multiple products at once."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkEligibilitiesForPromotionalOffers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"products"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudEligibilityCallback","preciseIdentifier":"s:9ApphudSDK0A19EligibilityCallbacka"},{"kind":"text","text":")"}],"title":"checkEligibilitiesForPromotionalOffers(products:callback:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)checkEligibilitiesForPromotionalOffersWithProducts:callback:","modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"checkEligibilitiesForPromotionalOffersWithProducts:callback:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudEligibilityCallback":{"role":"symbol","title":"ApphudEligibilityCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudEligibilityCallback"}],"abstract":[{"type":"text","text":"Public Callback object provide -> [String: Bool]"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudEligibilityCallback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudEligibilityCallback"}],"url":"\/documentation\/apphudsdk\/apphudeligibilitycallback"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[{"type":"text","text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"role":"symbol","title":"Apphud","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/checkEligibilitiesForPromotionalOffers(products:callback:)":{"role":"symbol","title":"checkEligibilitiesForPromotionalOffers(products:callback:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkEligibilitiesForPromotionalOffers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"products"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudEligibilityCallback","preciseIdentifier":"s:9ApphudSDK0A19EligibilityCallbacka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Checks promotional offers eligibility for multiple products at once."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilitiesForPromotionalOffers(products:callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkEligibilitiesForPromotionalOffersWithProducts:callback:"}],"url":"\/documentation\/apphudsdk\/apphud\/checkeligibilitiesforpromotionaloffers(products:callback:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"checkEligibilitiesForPromotionalOffersWithProducts:callback:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"checkEligibilitiesForPromotionalOffersWithProducts:callback:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"checkEligibilitiesForPromotionalOffersWithProducts:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SKProduct *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"products"},{"kind":"text","text":" "},{"kind":"identifier","text":"callback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSDictionary<NSString *,NSNumber *> *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSDictionary)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"kind":"identifier","text":"Apphud"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilitiesForPromotionalOffers(products:callback:)\/title","value":"checkEligibilitiesForPromotionalOffersWithProducts:callback:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilitiesForPromotionalOffers(products:callback:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"checkEligibilitiesForPromotionalOffersWithProducts:callback:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}