{"metadata":{"role":"symbol","title":"didUpdateNotification()","navigatorTitle":[{"kind":"identifier","text":"didUpdateNotification"}],"symbolKind":"method","modules":[{"name":"ApphudSDK"}],"roleHeading":"Type Method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)didUpdateNotification","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didUpdateNotification"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10Foundation12NotificationV4Namea","text":"Name","kind":"typeIdentifier"}]},"abstract":[{"type":"text","text":"Notification triggered when any subscription or non-renewing purchase is purchased or updated. The SDK also checks for updates when the app becomes active. This notification can be used to update the UI in response to purchase changes and is also useful in SwiftUI contexts."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateNotification","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The notification name for subscription or non-renewing purchase updates.","type":"text"}],"type":"paragraph"}]}],"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/didupdatenotification()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/didupdatenotification()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/didUpdateNotification()"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/didUpdateNotification()":{"abstract":[{"type":"text","text":"Notification triggered when any subscription or non-renewing purchase is purchased or updated. The SDK also checks for updates when the app becomes active. This notification can be used to update the UI in response to purchase changes and is also useful in SwiftUI contexts."}],"type":"topic","url":"\/documentation\/apphudsdk\/apphud\/didupdatenotification()","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateNotification"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10Foundation12NotificationV4Namea","text":"Name","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"didUpdateNotification","kind":"identifier"}],"title":"didUpdateNotification()","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/didUpdateNotification()"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","url":"\/documentation\/apphudsdk","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"title":"ApphudSDK","type":"topic","role":"collection","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"type":"topic","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud","abstract":[{"text":"Entry point of the Apphud SDK. It provides access to all its features.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Apphud"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"didUpdateNotification","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"didUpdateNotification"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"didUpdateNotification","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"didUpdateNotification","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1didUpdateNotification()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1didUpdateNotification()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"didUpdateNotification"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"text":"Apphud","kind":"identifier"}]}]}]}