{"abstract":[{"text":"Retrieves the placements configured in Mission control > Targetings, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"text":"s are loaded from the App Store.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchPlacements","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxAttempts","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = APPHUD_DEFAULT_RETRIES, ","kind":"text"},{"text":"forceRefresh","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ([","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPlacement","text":"ApphudPlacement","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A9PlacementC"},{"text":"], ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError","text":"ApphudError","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"name":"maxAttempts","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Number of request attempts before throwing an error. Must be between 1 and 10. Default value is 3."}]}]},{"name":"forceRefresh","content":[{"inlineContent":[{"text":"When set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", forces Apphud to refresh user data and reload placements from the server before returning the result. Use this when you need to apply updated audience segmentation or A\/B test assignments (for example, after changing user properties that affect placement targeting).","type":"text"}],"type":"paragraph"}]},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"text":"A closure that takes an array of ","type":"text"},{"code":"ApphudPlacement","type":"codeVoice"},{"text":" objects and returns void.","type":"text"}]}]}]},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"A placement is a specific location within a user’s journey (such as onboarding, settings, etc.) where its internal paywall is intended to be displayed.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"For immediate access without awaiting "},{"code":"SKProduct","type":"codeVoice"},{"type":"text","text":"s, use "},{"code":"ApphudDelegate","type":"codeVoice"},{"type":"text","text":"’s "},{"code":"userDidLoad","type":"codeVoice"},{"type":"text","text":" method or the callback in "},{"code":"Apphud.start(...)","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"role":"symbol","symbolKind":"method","externalID":"s:9ApphudSDK0A0C15fetchPlacements11maxAttempts12forceRefresh_ySi_SbySayAA0A9PlacementCG_AA0A5ErrorCSgtctFZ","title":"fetchPlacements(maxAttempts:forceRefresh:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchPlacements","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxAttempts","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forceRefresh","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ([","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A9PlacementC","text":"ApphudPlacement","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError","text":"ApphudError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"modules":[{"name":"ApphudSDK"}],"roleHeading":"Type Method"},"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/fetchplacements(maxattempts:forcerefresh:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchPlacements(maxAttempts:forceRefresh:_:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud","title":"Apphud","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/fetchPlacements(maxAttempts:forceRefresh:_:)":{"url":"\/documentation\/apphudsdk\/apphud\/fetchplacements(maxattempts:forcerefresh:_:)","kind":"symbol","role":"symbol","abstract":[{"text":"Retrieves the placements configured in Mission control > Targetings, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"code":"SKProduct","type":"codeVoice"},{"type":"text","text":"s are loaded from the App Store."}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchPlacements","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxAttempts","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forceRefresh","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ([","kind":"text"},{"text":"ApphudPlacement","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A9PlacementC"},{"text":"], ","kind":"text"},{"text":"ApphudError","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchPlacements(maxAttempts:forceRefresh:_:)","title":"fetchPlacements(maxAttempts:forceRefresh:_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudError":{"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudError"}],"url":"\/documentation\/apphudsdk\/apphuderror","title":"ApphudError","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudError"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPlacement":{"role":"symbol","title":"ApphudPlacement","navigatorTitle":[{"text":"ApphudPlacement","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPlacement","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPlacement"}],"url":"\/documentation\/apphudsdk\/apphudplacement","abstract":[{"text":"A placement is a specific location within a user’s journey (such as onboarding, settings, etc.) where its internal paywall is intended to be displayed.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"Apphud","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","op":"replace","value":[{"kind":"identifier","text":"Apphud"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Apphud"}]},{"value":"ApphudError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/fragments","value":[{"kind":"identifier","text":"ApphudError"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/navigatorTitle","value":[{"kind":"identifier","text":"ApphudError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}