{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/fetchrawreceiptinfo(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/fetchrawreceiptinfo(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchRawReceiptInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudReceipt","text":"ApphudReceipt","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"text":"A closure that is called with the ApphudReceipt object containing the receipt information.","type":"text"}],"type":"paragraph"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"fetchRawReceiptInfo:"}],"role":"symbol","modules":[{"name":"ApphudSDK"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchRawReceiptInfo","kind":"identifier"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"ApphudReceipt","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudReceipt"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)fetchRawReceiptInfo:","roleHeading":"Type Method","title":"fetchRawReceiptInfo(_:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchRawReceiptInfo(_:)"},"abstract":[{"type":"text","text":"Fetches raw receipt information in an ApphudReceipt model class. This is useful for accessing details like the original_application_version."}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/fetchRawReceiptInfo(_:)":{"kind":"symbol","navigatorTitle":[{"text":"fetchRawReceiptInfo:","kind":"identifier"}],"title":"fetchRawReceiptInfo(_:)","url":"\/documentation\/apphudsdk\/apphud\/fetchrawreceiptinfo(_:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchRawReceiptInfo(_:)","type":"topic","role":"symbol","abstract":[{"text":"Fetches raw receipt information in an ApphudReceipt model class. This is useful for accessing details like the original_application_version.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fetchRawReceiptInfo","kind":"identifier"},{"kind":"text","text":"(("},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudReceipt","kind":"typeIdentifier","text":"ApphudReceipt"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"type":"topic","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud","abstract":[{"text":"Entry point of the Apphud SDK. It provides access to all its features.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Apphud"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","url":"\/documentation\/apphudsdk","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"title":"ApphudSDK","type":"topic","role":"collection","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudReceipt"}],"abstract":[{"code":"ApphudReceipt","type":"codeVoice"},{"text":" is Apphud’s wrapper around StoreKit’s ","type":"text"},{"code":"Receipt","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/apphudsdk\/apphudreceipt","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt","navigatorTitle":[{"text":"ApphudReceipt","kind":"identifier"}],"title":"ApphudReceipt","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"fetchRawReceiptInfo:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"fetchRawReceiptInfo:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"fetchRawReceiptInfo:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@ApphudSDK@objc(cs)ApphudReceipt)","text":"void (^)(ApphudReceipt *)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"fetchRawReceiptInfo:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1fetchRawReceiptInfo(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1fetchRawReceiptInfo(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fetchRawReceiptInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"op":"replace","value":[{"text":"Apphud","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments"},{"value":"ApphudReceipt","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ApphudReceipt"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}