{"abstract":[{"type":"text","text":"Fetches a paywall screen and returns it as a SwiftUI view ready for presentation."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchPaywallView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall"},{"text":", ","kind":"text"},{"text":"maxTimeout","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"cachePolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A18PaywallCachePolicyO","text":"ApphudPaywallCachePolicy"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onDismiss"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:9ApphudSDK0A11PaywallViewV","text":"ApphudPaywallView","kind":"typeIdentifier"}],"title":"fetchPaywallView(_:maxTimeout:cachePolicy:onDismiss:)","externalID":"s:9ApphudSDK0A0C16fetchPaywallView_10maxTimeout11cachePolicy9onDismissAA0adE0VAA0aD0C_SdAA0ad5CacheI0OyycSgtYaKFZ","roleHeading":"Type Method","modules":[{"name":"ApphudSDK"}]},"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/fetchpaywallview(_:maxtimeout:cachepolicy:ondismiss:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchPaywallView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"paywall","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxTimeout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":" = APPHUD_PAYWALL_SCREEN_LOAD_TIMEOUT, ","kind":"text"},{"kind":"externalParam","text":"cachePolicy"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A18PaywallCachePolicyO","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallCachePolicy","text":"ApphudPaywallCachePolicy"},{"kind":"text","text":" = .sandboxAndProduction, "},{"kind":"externalParam","text":"onDismiss"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")? = nil) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallView","preciseIdentifier":"s:9ApphudSDK0A11PaywallViewV","text":"ApphudPaywallView"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"paywall","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"ApphudPaywall","type":"codeVoice"},{"type":"text","text":" object to fetch the screen for"}]}]},{"name":"maxTimeout","content":[{"inlineContent":[{"type":"text","text":"Maximum time to wait for the screen to load (default: 10 seconds)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Cache policy for the paywall screen (default: .sandboxAndProduction)","type":"text"}]}],"name":"cachePolicy"},{"name":"onDismiss","content":[{"inlineContent":[{"text":"Optional callback invoked when the paywall should be dismissed.","type":"text"},{"text":" ","type":"text"},{"text":"If nil, uses SwiftUI’s environment dismiss (iOS 15+) or attempts UIKit dismissal","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A SwiftUI view containing the paywall screen"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is the SwiftUI equivalent of "},{"code":"fetchPaywallScreen","type":"codeVoice"},{"type":"text","text":" and provides a seamless way"},{"text":" ","type":"text"},{"type":"text","text":"to integrate Apphud paywalls into SwiftUI applications."}]},{"style":"note","name":"Throws","type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"code":"ApphudError","type":"codeVoice"},{"text":" if the screen fails to load","type":"text"}],"type":"paragraph"}]},{"level":2,"text":"Usage Examples:","type":"heading","anchor":"Usage-Examples"},{"type":"paragraph","inlineContent":[{"text":"Pre-fetch and present:","type":"text"}]},{"code":["@State private var paywallView: ApphudPaywallView?","","Button(\"Show Paywall\") {","    Task {","        do {","            paywallView = try await Apphud.fetchPaywallView(paywall) {","               paywallView = nil","            }","        } catch {","            print(\"Failed to load paywall: \\(error)\")","        }","    }","}",".fullScreenCover(isPresented: .constant(paywallView != nil)) {","    paywallView?.fullscreen()","}"],"type":"codeListing","syntax":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchPaywallView(_:maxTimeout:cachePolicy:onDismiss:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"url":"\/documentation\/apphudsdk\/apphud","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","title":"Apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallCachePolicy":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudPaywallCachePolicy","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallCachePolicy","url":"\/documentation\/apphudsdk\/apphudpaywallcachepolicy","kind":"symbol","title":"ApphudPaywallCachePolicy","type":"topic","abstract":[{"type":"text","text":"Specifies how paywalls are cached."}],"navigatorTitle":[{"kind":"identifier","text":"ApphudPaywallCachePolicy"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallView":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudPaywallView"}],"type":"topic","url":"\/documentation\/apphudsdk\/apphudpaywallview","role":"symbol","title":"ApphudPaywallView","abstract":[{"type":"text","text":"A SwiftUI wrapper for ApphudPaywallScreenController that displays the paywall fullscreen."},{"type":"text","text":" "},{"type":"text","text":"Automatically handles dismissal through SwiftUI mechanisms instead of UIKit."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallView","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPaywallView"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/fetchPaywallView(_:maxTimeout:cachePolicy:onDismiss:)":{"abstract":[{"type":"text","text":"Fetches a paywall screen and returns it as a SwiftUI view ready for presentation."}],"url":"\/documentation\/apphudsdk\/apphud\/fetchpaywallview(_:maxtimeout:cachepolicy:ondismiss:)","role":"symbol","kind":"symbol","title":"fetchPaywallView(_:maxTimeout:cachePolicy:onDismiss:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchPaywallView(_:maxTimeout:cachePolicy:onDismiss:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fetchPaywallView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier","text":"ApphudPaywall"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxTimeout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cachePolicy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ApphudPaywallCachePolicy","preciseIdentifier":"s:9ApphudSDK0A18PaywallCachePolicyO"},{"kind":"text","text":", "},{"text":"onDismiss","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A11PaywallViewV","text":"ApphudPaywallView","kind":"typeIdentifier"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"kind":"symbol","title":"ApphudPaywall","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudPaywall"}],"url":"\/documentation\/apphudsdk\/apphudpaywall","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudPaywall","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Apphud","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","op":"replace","value":[{"kind":"identifier","text":"Apphud"}]},{"op":"replace","value":[{"text":"Apphud","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle"},{"value":"ApphudPaywall","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title"},{"value":[{"text":"ApphudPaywall","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ApphudPaywall"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/navigatorTitle","op":"replace"}]}]}