{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"sections":[],"metadata":{"modules":[{"name":"ApphudSDK"}],"symbolKind":"method","roleHeading":"Type Method","externalID":"s:9ApphudSDK0A0C15fetchPlacements11maxAttempts_ySi_ySayAA0A9PlacementCG_AA0A5ErrorCSgtctFZ","title":"fetchPlacements(maxAttempts:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchPlacements"},{"kind":"text","text":"("},{"text":"maxAttempts","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", (["},{"preciseIdentifier":"s:9ApphudSDK0A9PlacementC","kind":"typeIdentifier","text":"ApphudPlacement"},{"text":"], ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError","text":"ApphudError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"kind":"symbol","abstract":[{"type":"text","text":"Retrieves the placements configured in Product Hub > Placements, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner "},{"code":"SKProduct","type":"codeVoice"},{"type":"text","text":"s are loaded from the App Store."}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchPlacements(maxAttempts:_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/fetchplacements(maxattempts:_:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchPlacements"},{"text":"(","kind":"text"},{"text":"maxAttempts","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":" = APPHUD_DEFAULT_RETRIES, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ([","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A9PlacementC","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPlacement","text":"ApphudPlacement"},{"text":"], ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError","text":"ApphudError","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Number of request attempts before throwing an error. Must be between 1 and 10. Default value is 3."}],"type":"paragraph"}],"name":"maxAttempts"},{"content":[{"inlineContent":[{"text":"A closure that takes an array of ","type":"text"},{"type":"codeVoice","code":"ApphudPlacement"},{"type":"text","text":" objects and returns void."}],"type":"paragraph"}],"name":"callback"}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"A placement is a specific location within a user’s journey (such as onboarding, settings, etc.) where its internal paywall is intended to be displayed."}],"type":"paragraph"},{"inlineContent":[{"text":"For immediate access without awaiting ","type":"text"},{"code":"SKProduct","type":"codeVoice"},{"type":"text","text":"s, use "},{"type":"codeVoice","code":"ApphudDelegate"},{"text":"’s ","type":"text"},{"code":"userDidLoad","type":"codeVoice"},{"type":"text","text":" method or the callback in "},{"code":"Apphud.start(...)","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/fetchPlacements(maxAttempts:_:)":{"url":"\/documentation\/apphudsdk\/apphud\/fetchplacements(maxattempts:_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchPlacements","kind":"identifier"},{"kind":"text","text":"("},{"text":"maxAttempts","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ([","kind":"text"},{"text":"ApphudPlacement","preciseIdentifier":"s:9ApphudSDK0A9PlacementC","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError","text":"ApphudError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"text":"Retrieves the placements configured in Product Hub > Placements, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"s are loaded from the App Store."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchPlacements(maxAttempts:_:)","kind":"symbol","title":"fetchPlacements(maxAttempts:_:)","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"url":"\/documentation\/apphudsdk\/apphud","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","title":"Apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudError":{"type":"topic","url":"\/documentation\/apphudsdk\/apphuderror","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ApphudError","kind":"identifier"}],"title":"ApphudError","navigatorTitle":[{"kind":"identifier","text":"ApphudError"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPlacement":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPlacement","title":"ApphudPlacement","url":"\/documentation\/apphudsdk\/apphudplacement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPlacement"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudPlacement"}],"type":"topic","abstract":[{"text":"A placement is a specific location within a user’s journey (such as onboarding, settings, etc.) where its internal paywall is intended to be displayed.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Apphud","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"text":"Apphud","kind":"identifier"}]},{"value":[{"text":"Apphud","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/title","value":"ApphudError","op":"replace"},{"value":[{"kind":"identifier","text":"ApphudError"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ApphudError"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/navigatorTitle","op":"replace"}]}]}