{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchSKProducts(maxAttempts:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchSKProducts"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"maxAttempts"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> ["},{"preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"roleHeading":"Type Method","modules":[{"name":"ApphudSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fetchSKProductsWithMaxAttempts:completionHandler:"}],"title":"fetchSKProducts(maxAttempts:)","symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)fetchSKProductsWithMaxAttempts:completionHandler:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"abstract":[{"text":"Fetches ","type":"text"},{"code":"SKProduct","type":"codeVoice"},{"type":"text","text":" objects asynchronously from the App Store. This method is used to retrieve the products that you have configured in the Apphud dashboard (Apphud > Product Hub > Products)."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/fetchskproducts(maxattempts:)"]},{"paths":["\/documentation\/apphudsdk\/apphud\/fetchskproducts(maxattempts:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchSKProducts","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxAttempts"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":" = APPHUD_DEFAULT_RETRIES) "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> ["},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":"]","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Number of request attempts before throwing an error. Must be between 1 and 10. Default value is 3.","type":"text"}]}],"name":"maxAttempts"}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"An array of ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"text":" objects corresponding to the products added in the Apphud > Product Hub > Products section.","type":"text"}]}]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"url":"\/documentation\/apphudsdk\/apphud","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","title":"Apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/fetchSKProducts(maxAttempts:)":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchSKProducts","kind":"identifier"},{"kind":"text","text":"("},{"text":"maxAttempts","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ["},{"text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","title":"fetchSKProducts(maxAttempts:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchSKProducts(maxAttempts:)","navigatorTitle":[{"text":"fetchSKProductsWithMaxAttempts:completionHandler:","kind":"identifier"}],"abstract":[{"text":"Fetches ","type":"text"},{"code":"SKProduct","type":"codeVoice"},{"type":"text","text":" objects asynchronously from the App Store. This method is used to retrieve the products that you have configured in the Apphud dashboard (Apphud > Product Hub > Products)."}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphud\/fetchskproducts(maxattempts:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"fetchSKProductsWithMaxAttempts:completionHandler:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fetchSKProductsWithMaxAttempts:completionHandler:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"fetchSKProductsWithMaxAttempts:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"text":"maxAttempts","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"NSArray<SKProduct *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Number of request attempts before throwing an error. Must be between 1 and 10. Default value is 3."}]}],"name":"maxAttempts"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","op":"replace","value":[{"kind":"identifier","text":"Apphud"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","value":[{"kind":"identifier","text":"Apphud"}]},{"op":"replace","value":"fetchSKProductsWithMaxAttempts:completionHandler:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1fetchSKProducts(maxAttempts:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"fetchSKProductsWithMaxAttempts:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1fetchSKProducts(maxAttempts:)\/fragments"}]}]}