{"abstract":[{"text":"Asynchronously fetches a paywall Screen for the given paywall.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fetchPaywallScreen","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"paywall","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","text":"ApphudPaywall"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":" = APPHUD_PAYWALL_SCREEN_LOAD_TIMEOUT, "},{"text":"cachePolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudPaywallCachePolicy","preciseIdentifier":"s:9ApphudSDK0A18PaywallCachePolicyO","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallCachePolicy"},{"kind":"text","text":" = .sandboxAndProduction, "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenFetchResult","text":"ApphudPaywallScreenFetchResult","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A24PaywallScreenFetchResultO"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]},{"parameters":[{"name":"paywall","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"ApphudPaywall","type":"codeVoice"},{"text":" instance whose Screen you want to display.","type":"text"}]}]},{"name":"maxTimeout","content":[{"inlineContent":[{"type":"text","text":"Maximum time (in seconds) to wait for the Screen to load. If this interval elapses without success, the completion handler is called with an error. Defaults to "},{"code":"APPHUD_PAYWALL_SCREEN_LOAD_TIMEOUT","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"cachePolicy","content":[{"type":"paragraph","inlineContent":[{"text":"Defines paywall caching behavior.","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"text":"A closure receiving an ","type":"text"},{"code":"ApphudPaywallScreenFetchResult","type":"codeVoice"},{"text":", which contains either a ready-to-use ","type":"text"},{"type":"codeVoice","code":"ApphudPaywallScreenController"},{"type":"text","text":" or an error."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You must manually add returned controller to your view hierarchy."},{"type":"text","text":" "},{"type":"text","text":"If the paywall does not have a Screen, this method returns nil."},{"type":"text","text":" "},{"text":"If you did not call ","type":"text"},{"code":"preloadPaywallScreens(placementIdentifiers:)","type":"codeVoice"},{"text":" beforehand, loading will start when this method is called.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If paywall Screen already pre-loaded, it will present immediately. You can use ApphudPaywall’s "},{"code":"isScreenPreloaded","type":"codeVoice"},{"type":"text","text":" function."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/fetchpaywallscreen(_:maxtimeout:cachepolicy:completion:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchPaywallScreen(_:maxTimeout:cachePolicy:completion:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Apphud-Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/start(apiKey:userID:observerMode:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/startManually(apiKey:userID:deviceID:observerMode:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/updateUserID(_:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/userID()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/deviceID()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/currentUser()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/logout()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/refreshUserData(callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placements(maxAttempts:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/rawPlacements()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placement(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/deferPlacements()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/preloadPaywallScreens(placementIdentifiers:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchPaywallView(_:maxTimeout:cachePolicy:onDismiss:)"],"title":"Apphud Methods","generated":true}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"fetchPaywallScreen(_:maxTimeout:cachePolicy:completion:)","symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchPaywallScreen"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"maxTimeout","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"text":"cachePolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudPaywallCachePolicy","preciseIdentifier":"s:9ApphudSDK0A18PaywallCachePolicyO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"ApphudPaywallScreenFetchResult","preciseIdentifier":"s:9ApphudSDK0A24PaywallScreenFetchResultO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:9ApphudSDK0A0C18fetchPaywallScreen_10maxTimeout11cachePolicy10completionyAA0aD0C_SdAA0ad5CacheI0OyAA0adE11FetchResultOctFZ","role":"symbol","modules":[{"name":"ApphudSDK"}]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/fetchPaywallView(_:maxTimeout:cachePolicy:onDismiss:)":{"abstract":[{"type":"text","text":"Fetches a paywall screen and returns it as a SwiftUI view ready for presentation."}],"type":"topic","title":"fetchPaywallView(_:maxTimeout:cachePolicy:onDismiss:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchPaywallView(_:maxTimeout:cachePolicy:onDismiss:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fetchPaywallView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":", ","kind":"text"},{"text":"maxTimeout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"cachePolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A18PaywallCachePolicyO","kind":"typeIdentifier","text":"ApphudPaywallCachePolicy"},{"kind":"text","text":", "},{"text":"onDismiss","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"ApphudPaywallView","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A11PaywallViewV"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphud\/fetchpaywallview(_:maxtimeout:cachepolicy:ondismiss:)","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/placement(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"placement"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:9ApphudSDK0A9PlacementC","kind":"typeIdentifier","text":"ApphudPlacement"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Asynchronously retrieve a specific placement by identifier configured in Mission control > Targetings, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner "},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"s are loaded from the App Store."}],"url":"\/documentation\/apphudsdk\/apphud\/placement(_:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placement(_:)","title":"placement(_:)","type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywallShown(_:)":{"url":"\/documentation\/apphudsdk\/apphud\/paywallshown(_:)","title":"paywallShown(_:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paywallShown"},{"kind":"text","text":"("},{"text":"ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Logs a “Paywall Shown” event which is required for A\/B Testing analytics."}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"paywallShown:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/updateUserID(_:callback:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/updateUserID(_:callback:)","url":"\/documentation\/apphudsdk\/apphud\/updateuserid(_:callback:)","type":"topic","abstract":[{"text":"Updates the user ID. Use this when you need to change the user identifier during the app’s runtime.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"s"}],"title":"updateUserID(_:callback:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateUserID","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:9ApphudSDK0A4UserV","kind":"typeIdentifier","text":"ApphudUser"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/rawPlacements()":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/rawPlacements()","kind":"symbol","abstract":[{"text":"A list of paywall placements, potentially altered based on the user’s involvement in A\/B testing, if any. A placement is a specific location within a user’s journey (such as onboarding, settings, etc.) where its internal paywall is intended to be displayed.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphud\/rawplacements()","title":"rawPlacements()","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawPlacements","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"ApphudPlacement","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A9PlacementC"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenFetchResult":{"type":"topic","title":"ApphudPaywallScreenFetchResult","abstract":[{"type":"text","text":"Represents the result of attempting to fetch and prepare a paywall screen for display."}],"navigatorTitle":[{"text":"ApphudPaywallScreenFetchResult","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPaywallScreenFetchResult"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenFetchResult","url":"\/documentation\/apphudsdk\/apphudpaywallscreenfetchresult","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","kind":"symbol","abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"navigatorTitle":[{"text":"ApphudPaywall","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphudpaywall","title":"ApphudPaywall","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudPaywall","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/logout()":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/logout()","kind":"symbol","abstract":[{"type":"text","text":"Logs out the current user, clears all saved data, and resets the SDK to an uninitialized state. After calling this method, you must reinitialize the SDK with "},{"type":"codeVoice","code":"Apphud.start(...)"},{"type":"text","text":" or "},{"type":"codeVoice","code":"Apphud.manually(...)"},{"type":"text","text":" for a new user."}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"logoutWithCompletionHandler:","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphud\/logout()","title":"logout()","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logout","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/deviceID()":{"type":"topic","title":"deviceID()","abstract":[{"text":"Returns the current device ID. Use this method if you need to implement a custom logout\/login flow by saving a User ID & Device ID pair for each app user. This allows for a more controlled management of user sessions and device associations.","type":"text"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"deviceID"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceID","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/deviceID()","url":"\/documentation\/apphudsdk\/apphud\/deviceid()","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/start(apiKey:userID:observerMode:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/start(apiKey:userID:observerMode:callback:)","kind":"symbol","abstract":[{"type":"text","text":"Initializes Apphud SDK. Call this during the app’s launch."}],"url":"\/documentation\/apphudsdk\/apphud\/start(apikey:userid:observermode:callback:)","title":"start(apiKey:userID:observerMode:callback:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"userID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"observerMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"ApphudUser","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A4UserV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/deferPlacements()":{"role":"symbol","title":"deferPlacements()","url":"\/documentation\/apphudsdk\/apphud\/deferplacements()","abstract":[{"text":"Disables automatic app remote config, paywall and placement requests during the SDK’s initial setup. Developers must explicitly call ","type":"text"},{"code":"fetchPlacements","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"await placements()","type":"codeVoice"},{"text":" methods at a later point in the app’s lifecycle to fetch placements with inner paywalls.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deferPlacements"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/deferPlacements()","kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallCachePolicy":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallCachePolicy","kind":"symbol","abstract":[{"text":"Specifies how paywalls are cached.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudPaywallCachePolicy"}],"url":"\/documentation\/apphudsdk\/apphudpaywallcachepolicy","title":"ApphudPaywallCachePolicy","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPaywallCachePolicy"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud","title":"Apphud","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/placements(maxAttempts:)":{"type":"topic","title":"placements(maxAttempts:)","abstract":[{"type":"text","text":"Asynchronously retrieves the paywall placements configured in Mission control > Targetings, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner "},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"s are loaded from the App Store."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"placements"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxAttempts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A9PlacementC","kind":"typeIdentifier","text":"ApphudPlacement"},{"kind":"text","text":"]"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placements(maxAttempts:)","url":"\/documentation\/apphudsdk\/apphud\/placements(maxattempts:)","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/startManually(apiKey:userID:deviceID:observerMode:callback:)":{"role":"symbol","title":"startManually(apiKey:userID:deviceID:observerMode:callback:)","url":"\/documentation\/apphudsdk\/apphud\/startmanually(apikey:userid:deviceid:observermode:callback:)","abstract":[{"type":"text","text":"Initializes Apphud SDK with User ID & Device ID pair. Not recommended for use unless you know what you are doing."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startManually"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deviceID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"observerMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A4UserV","text":"ApphudUser"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/startManually(apiKey:userID:deviceID:observerMode:callback:)","kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/refreshUserData(callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/refreshUserData(callback:)","kind":"symbol","abstract":[{"type":"text","text":"Refreshes current user data including app remote config, paywalls, placements, subscriptions, non-renewing purchases, and promotionals."}],"url":"\/documentation\/apphudsdk\/apphud\/refreshuserdata(callback:)","title":"refreshUserData(callback:)","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refreshUserData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A4UserV","text":"ApphudUser","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"))","kind":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/userID()":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/userID()","kind":"symbol","abstract":[{"type":"text","text":"Returns the current userID that identifies the user across multiple devices."}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"userID","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphud\/userid()","title":"userID()","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userID","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/currentUser()":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/currentUser()","kind":"symbol","abstract":[{"text":"Returns an instance of the current user.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphud\/currentuser()","title":"currentUser()","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentUser"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A4UserV","text":"ApphudUser"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/preloadPaywallScreens(placementIdentifiers:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preloadPaywallScreens","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"placementIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Preloads and caches one or more paywall screens to enable faster presentation."}],"url":"\/documentation\/apphudsdk\/apphud\/preloadpaywallscreens(placementidentifiers:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/preloadPaywallScreens(placementIdentifiers:)","title":"preloadPaywallScreens(placementIdentifiers:)","type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/fetchPaywallScreen(_:maxTimeout:cachePolicy:completion:)":{"type":"topic","title":"fetchPaywallScreen(_:maxTimeout:cachePolicy:completion:)","abstract":[{"type":"text","text":"Asynchronously fetches a paywall Screen for the given paywall."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchPaywallScreen"},{"text":"(","kind":"text"},{"text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxTimeout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"text":"cachePolicy","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ApphudPaywallCachePolicy","preciseIdentifier":"s:9ApphudSDK0A18PaywallCachePolicyO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ApphudPaywallScreenFetchResult","preciseIdentifier":"s:9ApphudSDK0A24PaywallScreenFetchResultO"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchPaywallScreen(_:maxTimeout:cachePolicy:completion:)","kind":"symbol","url":"\/documentation\/apphudsdk\/apphud\/fetchpaywallscreen(_:maxtimeout:cachepolicy:completion:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallShown(_:)\/title","value":"paywallShown:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallShown(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"paywallShown:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","value":"ApphudPaywall"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","value":[{"text":"ApphudPaywall","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/navigatorTitle","value":[{"kind":"identifier","text":"ApphudPaywall"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1logout()\/title","value":"logoutWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1logout()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"logoutWithCompletionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1deviceID()\/title","value":"deviceID"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1deviceID()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"deviceID"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"text":"Apphud","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","value":[{"kind":"identifier","text":"Apphud"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1userID()\/title","value":"userID","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1userID()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"userID","kind":"identifier"}],"op":"replace"}]}]}