{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchProducts"},{"text":"(","kind":"text"},{"text":"maxAttempts","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" = APPHUD_DEFAULT_RETRIES, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" ([","kind":"text"},{"text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"maxAttempts","content":[{"type":"paragraph","inlineContent":[{"text":"Number of request attempts before throwing an error. Must be between 1 and 10. Default value is 3.","type":"text"}]}]},{"name":"callback","content":[{"inlineContent":[{"text":"A closure that is called upon completion. It returns an array of ","type":"text"},{"code":"SKProduct","type":"codeVoice"},{"text":" objects and an optional ","type":"text"},{"type":"codeVoice","code":"Error"},{"type":"text","text":" if the fetch operation encountered any issues."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The method doesn’t return a value directly but instead provides the result through the "},{"code":"callback","type":"codeVoice"},{"text":" parameter.","type":"text"}]}],"kind":"content"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"name":"Important","type":"aside","style":"important","content":[{"inlineContent":[{"type":"text","text":"Best practice is to manage products using placements configurations in the Apphud Product Hub > Placements, rather than directly fetching products. Implementing placements logic via the dashboard allows for more organized and scalable management of your app’s placements and paywalls."}],"type":"paragraph"}]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/fetchproducts(maxattempts:_:)"]},{"paths":["\/documentation\/apphudsdk\/apphud\/fetchproducts(maxattempts:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"fetchProductsWithMaxAttempts::","kind":"identifier"}],"title":"fetchProducts(maxAttempts:_:)","modules":[{"name":"ApphudSDK"}],"symbolKind":"method","roleHeading":"Type Method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)fetchProductsWithMaxAttempts::","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fetchProducts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxAttempts","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ([","kind":"text"},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":"], "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchProducts(maxAttempts:_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Retrieves an array of existing ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"text":" objects or fetches products from the App Store that have been added in the Apphud Dashboard under Product Hub > Products.","type":"text"}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","url":"\/documentation\/apphudsdk","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","abstract":[]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"kind":"symbol","title":"Apphud","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/fetchProducts(maxAttempts:_:)":{"role":"symbol","url":"\/documentation\/apphudsdk\/apphud\/fetchproducts(maxattempts:_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/fetchProducts(maxAttempts:_:)","title":"fetchProducts(maxAttempts:_:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fetchProducts","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxAttempts"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", (["},{"text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"fetchProductsWithMaxAttempts::"}],"abstract":[{"text":"Retrieves an array of existing ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"text":" objects or fetches products from the App Store that have been added in the Apphud Dashboard under Product Hub > Products.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"fetchProductsWithMaxAttempts::","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"fetchProductsWithMaxAttempts::","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"fetchProductsWithMaxAttempts:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"maxAttempts","kind":"internalParam"},{"kind":"text","text":" "},{"text":":","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)","text":"void (^)(NSArray<SKProduct *> *, NSError *)"},{"kind":"text","text":") "},{"text":"callback","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"op":"replace","value":[{"kind":"identifier","text":"Apphud"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1fetchProducts(maxAttempts:_:)\/title","op":"replace","value":"fetchProductsWithMaxAttempts::"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1fetchProducts(maxAttempts:_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fetchProductsWithMaxAttempts::"}],"op":"replace"}]}]}