{"abstract":[{"text":"Grants a free promotional subscription to the user. This method updates the user’s subscription status, and after this, the ","type":"text"},{"type":"codeVoice","code":"hasActiveSubscription()"},{"type":"text","text":" method will return "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"grantPromotional","kind":"identifier"},{"kind":"text","text":"("},{"text":"daysCount","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"text":"productId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"permissionGroup","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ApphudGroup","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudGroup"},{"text":"?, ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","text":"ApphudBoolCallback","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)grantPromotionalWithDaysCount:productId:permissionGroup:callback:","modules":[{"name":"ApphudSDK"}],"title":"grantPromotional(daysCount:productId:permissionGroup:callback:)","navigatorTitle":[{"text":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"grantPromotional","kind":"identifier"},{"text":"(","kind":"text"},{"text":"daysCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"productId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"permissionGroup"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup","text":"ApphudGroup","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudGroup"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ApphudBoolCallback","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback"},{"text":"?)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Required. The number of days for the free premium access. For a lifetime promotional, pass an extremely high value, like 100000.","type":"text"}]}],"name":"daysCount"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional*. It’s recommended to provide the Product Id of the promotional subscription. Read the note below for more details."}]}],"name":"productId"},{"name":"permissionGroup","content":[{"type":"paragraph","inlineContent":[{"text":"Optional*. The Permission Group of the promotional subscription. Use this parameter if you have multiple permission groups.","type":"text"}]}]},{"name":"callback","content":[{"inlineContent":[{"text":"Optional. Returns ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the promotional subscription was successfully granted."}],"type":"paragraph"}]}]},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Either "},{"type":"codeVoice","code":"productId"},{"type":"text","text":" (recommended) or "},{"code":"permissionGroup","type":"codeVoice"},{"type":"text","text":" should be passed, or both parameters can be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":". If both "},{"type":"codeVoice","code":"productId"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"permissionGroup"},{"text":" are provided, ","type":"text"},{"code":"productId","type":"codeVoice"},{"text":" will be used. ","type":"text"},{"identifier":"https:\/\/docs.apphud.com\/docs\/product-hub","isActive":true,"type":"reference"}]}],"type":"aside"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/grantpromotional(dayscount:productid:permissiongroup:callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/grantpromotional(dayscount:productid:permissiongroup:callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Apphud Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/start(apiKey:userID:observerMode:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywall(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placement(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:callback:)-6dhy3","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/restorePurchases(callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasPremiumAccess()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasActiveSubscription()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)"],"generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/grantPromotional(daysCount:productId:permissionGroup:callback:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/placement(_:)":{"url":"\/documentation\/apphudsdk\/apphud\/placement(_:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placement(_:)","kind":"symbol","title":"placement(_:)","role":"symbol","abstract":[{"text":"Asynchronously retrieve a specific placement by identifier configured in Product Hub > Placements, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"s are loaded from the App Store."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"placement","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"ApphudPlacement","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A9PlacementC"},{"text":"?","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/addAttribution(data:from:identifer:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","role":"symbol","type":"topic","abstract":[{"text":"Submits attribution data to Apphud from your chosen attribution network provider.","type":"text"}],"kind":"symbol","title":"addAttribution(data:from:identifer:callback:)","url":"\/documentation\/apphudsdk\/apphud\/addattribution(data:from:identifer:callback:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addAttribution"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"data"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudAttributionProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@E@ApphudAttributionProvider"},{"text":", ","kind":"text"},{"text":"identifer","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"addAttributionWithData:from:identifer:callback:","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/restorePurchases(callback:)":{"url":"\/documentation\/apphudsdk\/apphud\/restorepurchases(callback:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/restorePurchases(callback:)","kind":"symbol","title":"restorePurchases(callback:)","role":"symbol","abstract":[{"text":"Implements the ","type":"text"},{"type":"codeVoice","code":"Restore Purchases"},{"type":"text","text":" mechanism. This method sends the current App Store Receipt to Apphud and returns information about the user’s subscriptions and in-app purchases."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"restorePurchases","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (["},{"text":"ApphudSubscription","preciseIdentifier":"s:9ApphudSDK0A12SubscriptionC","kind":"typeIdentifier"},{"kind":"text","text":"]?, ["},{"kind":"typeIdentifier","text":"ApphudNonRenewingPurchase","preciseIdentifier":"s:9ApphudSDK0A19NonRenewingPurchaseC"},{"text":"]?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywall(_:)":{"deprecated":true,"title":"paywall(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paywall","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywall(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paywall:completionHandler:"}],"url":"\/documentation\/apphudsdk\/apphud\/paywall(_:)","abstract":[{"type":"text","text":"Asynchronously retrieve a specific paywall by identifier configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner "},{"code":"SKProduct","type":"codeVoice"},{"type":"text","text":"s are loaded from the App Store."}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/hasActiveSubscription()":{"title":"hasActiveSubscription()","abstract":[{"text":"Checks if the user has an active premium subscription.","type":"text"}],"kind":"symbol","url":"\/documentation\/apphudsdk\/apphud\/hasactivesubscription()","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasActiveSubscription()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hasActiveSubscription"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasActiveSubscription"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudGroup":{"type":"topic","url":"\/documentation\/apphudsdk\/apphudgroup","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ApphudGroup","kind":"identifier"}],"abstract":[{"text":"Apphud class which describes products permission groups","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudGroup"}],"kind":"symbol","title":"ApphudGroup"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywallShown(_:)":{"type":"topic","abstract":[{"type":"text","text":"Logs a “Paywall Shown” event which is required for A\/B Testing analytics."}],"url":"\/documentation\/apphudsdk\/apphud\/paywallshown(_:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paywallShown","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"paywallShown:","kind":"identifier"}],"role":"symbol","title":"paywallShown(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/checkEligibilityForPromotionalOffer(product:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkEligibilityForPromotionalOffer"},{"kind":"text","text":"("},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"checkEligibilityForPromotionalOfferWithProduct:callback:"}],"role":"symbol","abstract":[{"type":"text","text":"Checks whether the given product is eligible for any of its promotional offers."}],"url":"\/documentation\/apphudsdk\/apphud\/checkeligibilityforpromotionaloffer(product:callback:)","title":"checkEligibilityForPromotionalOffer(product:callback:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/hasPremiumAccess()":{"url":"\/documentation\/apphudsdk\/apphud\/haspremiumaccess()","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasPremiumAccess()","kind":"symbol","title":"hasPremiumAccess()","role":"symbol","abstract":[{"type":"text","text":"Determines if the user has active premium access through a subscription or a non-renewing purchase (lifetime)."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasPremiumAccess","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasPremiumAccess"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudBoolCallback":{"navigatorTitle":[{"kind":"identifier","text":"ApphudBoolCallback"}],"url":"\/documentation\/apphudsdk\/apphudboolcallback","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Public Callback object provide -> Bool","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback","title":"ApphudBoolCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ApphudBoolCallback","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)":{"title":"willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","abstract":[{"type":"text","text":"Notifies Apphud when a purchase process is initiated from a paywall in "},{"type":"codeVoice","code":"Observer Mode"},{"text":", enabling the use of A\/B experiments. This method should be called right before executing your own purchase method, and it’s specifically required only when the SDK is in Observer Mode.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPurchaseProductFrom"},{"text":"(","kind":"text"},{"text":"paywallIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"placementIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"type":"topic","url":"\/documentation\/apphudsdk\/apphud\/willpurchaseproductfrom(paywallidentifier:placementidentifier:)","navigatorTitle":[{"kind":"identifier","text":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/start(apiKey:userID:observerMode:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/start(apiKey:userID:observerMode:callback:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Initializes Apphud SDK. Call this during the app’s launch."}],"title":"start(apiKey:userID:observerMode:callback:)","kind":"symbol","url":"\/documentation\/apphudsdk\/apphud\/start(apikey:userid:observermode:callback:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"observerMode"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"text":": ((","kind":"text"},{"text":"ApphudUser","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A4UserV"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/checkEligibilityForIntroductoryOffer(product:callback:)":{"type":"topic","abstract":[{"type":"text","text":"Checks whether the given product is eligible for an introductory offer, which includes "},{"code":"free trial","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"pay as you go"},{"text":", or ","type":"text"},{"type":"codeVoice","code":"pay up front"},{"text":" options.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphud\/checkeligibilityforintroductoryoffer(product:callback:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"checkEligibilityForIntroductoryOffer","kind":"identifier"},{"kind":"text","text":"("},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","kind":"typeIdentifier","text":"ApphudBoolCallback"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"checkEligibilityForIntroductoryOfferWithProduct:callback:","kind":"identifier"}],"role":"symbol","title":"checkEligibilityForIntroductoryOffer(product:callback:)"},"https://docs.apphud.com/docs/product-hub":{"type":"link","titleInlineContent":[{"type":"text","text":"Documentation"}],"title":"Documentation","url":"https:\/\/docs.apphud.com\/docs\/product-hub","identifier":"https:\/\/docs.apphud.com\/docs\/product-hub"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/grantPromotional(daysCount:productId:permissionGroup:callback:)":{"title":"grantPromotional(daysCount:productId:permissionGroup:callback:)","url":"\/documentation\/apphudsdk\/apphud\/grantpromotional(dayscount:productid:permissiongroup:callback:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"grantPromotional"},{"text":"(","kind":"text"},{"text":"daysCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"productId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"permissionGroup"},{"text":": ","kind":"text"},{"text":"ApphudGroup","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudGroup"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"text":"?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/grantPromotional(daysCount:productId:permissionGroup:callback:)","abstract":[{"text":"Grants a free promotional subscription to the user. This method updates the user’s subscription status, and after this, the ","type":"text"},{"type":"codeVoice","code":"hasActiveSubscription()"},{"text":" method will return ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","navigatorTitle":[{"text":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/purchase(_:callback:)-6dhy3":{"type":"topic","abstract":[{"text":"Initiates the purchase of an ","type":"text"},{"code":"ApphudProduct","type":"codeVoice"},{"type":"text","text":" object from an "},{"type":"codeVoice","code":"ApphudPaywall"},{"type":"text","text":" and optionally from "},{"code":"ApphudPlacement","type":"codeVoice"},{"type":"text","text":" and automatically submits the App Store Receipt to Apphud."}],"url":"\/documentation\/apphudsdk\/apphud\/purchase(_:callback:)-6dhy3","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:callback:)-6dhy3","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchase"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","text":"ApphudPurchaseResult","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"purchaseApphudProduct:callback:"}],"role":"symbol","title":"purchase(_:callback:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/setUserProperty(key:value:setOnce:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserProperty"},{"text":"(","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","text":"ApphudUserPropertyKey","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"setOnce"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setUserPropertyWithKey:value:setOnce:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Sets a custom user property in Apphud. The value assigned to this property must be of one of the following types: ","type":"text"},{"code":"Int","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"Float"},{"type":"text","text":", "},{"code":"Double","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"Bool"},{"type":"text","text":", "},{"code":"String","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"NSNumber"},{"text":", ","type":"text"},{"type":"codeVoice","code":"NSString"},{"type":"text","text":", "},{"type":"codeVoice","code":"NSNull"},{"type":"text","text":", or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/apphudsdk\/apphud\/setuserproperty(key:value:setonce:)","title":"setUserProperty(key:value:setOnce:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"title":"Apphud Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywall(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:callback:)-6dhy3","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasPremiumAccess()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasActiveSubscription()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"grantPromotionalWithDaysCount:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"daysCount"},{"text":" ","kind":"text"},{"kind":"identifier","text":"productId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"productId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"permissionGroup:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudGroup","text":"ApphudGroup","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup"},{"text":" *) ","kind":"text"},{"text":"permissionGroup","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callback:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#b)","text":"void (^)(_Bool)"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1addAttribution(data:from:identifer:callback:)\/title","value":"addAttributionWithData:from:identifer:callback:"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1addAttribution(data:from:identifer:callback:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"addAttributionWithData:from:identifer:callback:","kind":"identifier"}]},{"value":"paywall:completionHandler:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywall(_:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"paywall:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywall(_:)\/fragments"},{"value":"hasActiveSubscription","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasActiveSubscription()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasActiveSubscription()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"hasActiveSubscription","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudGroup\/title","value":"ApphudGroup"},{"value":[{"text":"ApphudGroup","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudGroup\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallShown(_:)\/title","value":"paywallShown:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallShown(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"paywallShown:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForPromotionalOffer(product:callback:)\/title","op":"replace","value":"checkEligibilityForPromotionalOfferWithProduct:callback:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"checkEligibilityForPromotionalOfferWithProduct:callback:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForPromotionalOffer(product:callback:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasPremiumAccess()\/title","value":"hasPremiumAccess"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasPremiumAccess()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"hasPremiumAccess","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)\/title","value":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:"},{"value":[{"kind":"text","text":"+ "},{"text":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForIntroductoryOffer(product:callback:)\/title","op":"replace","value":"checkEligibilityForIntroductoryOfferWithProduct:callback:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForIntroductoryOffer(product:callback:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"checkEligibilityForIntroductoryOfferWithProduct:callback:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1grantPromotional(daysCount:productId:permissionGroup:callback:)\/title","op":"replace","value":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:"},{"value":[{"kind":"text","text":"+ "},{"text":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1grantPromotional(daysCount:productId:permissionGroup:callback:)\/fragments","op":"replace"},{"value":"purchaseApphudProduct:callback:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchase(_:callback:)-6dhy3\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchase(_:callback:)-6dhy3\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"purchaseApphudProduct:callback:","kind":"identifier"}]},{"value":"setUserPropertyWithKey:value:setOnce:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1setUserProperty(key:value:setOnce:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1setUserProperty(key:value:setOnce:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setUserPropertyWithKey:value:setOnce:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}