{"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/handlepushnotification(apsinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/handlepushnotification(apsinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"handlePushNotification(apsInfo:)","navigatorTitle":[{"kind":"identifier","text":"handlePushNotificationWithApsInfo:"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol","modules":[{"name":"ApphudSDK"}],"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)handlePushNotificationWithApsInfo:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handlePushNotification"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apsInfo"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handlePushNotification","kind":"identifier"},{"kind":"text","text":"("},{"text":"apsInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payload of the push notification."}]}],"name":"apsInfo"}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if the push notification was successfully handled by Apphud.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"name":"Note","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"This method should be used in your push notification handling logic to allow Apphud to manage notifications related to its Rules.","type":"text"}]}]}]}],"abstract":[{"type":"text","text":"Handles an incoming push notification payload. This method is used to process Rules-related notifications created by Apphud."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/handlePushNotification(apsInfo:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"kind":"symbol","references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","title":"Apphud","url":"\/documentation\/apphudsdk\/apphud","type":"topic","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/handlePushNotification(apsInfo:)":{"url":"\/documentation\/apphudsdk\/apphud\/handlepushnotification(apsinfo:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/handlePushNotification(apsInfo:)","navigatorTitle":[{"text":"handlePushNotificationWithApsInfo:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"handlePushNotification(apsInfo:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handlePushNotification","kind":"identifier"},{"text":"(","kind":"text"},{"text":"apsInfo","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"text":"Handles an incoming push notification payload. This method is used to process Rules-related notifications created by Apphud.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"handlePushNotificationWithApsInfo:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"handlePushNotificationWithApsInfo:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"handlePushNotificationWithApsInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"apsInfo","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","op":"replace","value":"Apphud"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"text":"Apphud","kind":"identifier"}]},{"op":"replace","value":"handlePushNotificationWithApsInfo:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1handlePushNotification(apsInfo:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1handlePushNotification(apsInfo:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"handlePushNotificationWithApsInfo:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}