{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/incrementUserProperty(key:by:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incrementUserProperty"},{"text":"(","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","kind":"typeIdentifier","text":"ApphudUserPropertyKey","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"key","content":[{"inlineContent":[{"text":"Required. Use your custom string key or some of built-in keys.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Required\/Optional. You can pass negative value to decrement."}]}],"name":"by"}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Example:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["Apphud.incrementUserProperty(key: .init(\"progress\"), by: 0.5)"]}],"kind":"content"}],"abstract":[{"type":"text","text":"Increments a custom user property. Value must be one of: "},{"type":"codeVoice","code":"Int"},{"type":"text","text":", "},{"code":"Float","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" or "},{"code":"NSNumber","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/incrementuserproperty(key:by:)"]},{"paths":["\/documentation\/apphudsdk\/apphud\/incrementuserproperty(key:by:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"incrementUserPropertyWithKey:by:","kind":"identifier"}],"modules":[{"name":"ApphudSDK"}],"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)incrementUserPropertyWithKey:by:","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incrementUserProperty","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudUserPropertyKey","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":")","kind":"text"}],"title":"incrementUserProperty(key:by:)","roleHeading":"Type Method","symbolKind":"method","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","title":"Apphud","url":"\/documentation\/apphudsdk\/apphud","type":"topic","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey":{"type":"topic","abstract":[{"type":"text","text":"User property initializer class with reserved property names."}],"url":"\/documentation\/apphudsdk\/apphuduserpropertykey","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudUserPropertyKey"}],"navigatorTitle":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"role":"symbol","title":"ApphudUserPropertyKey"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/incrementUserProperty(key:by:)":{"title":"incrementUserProperty(key:by:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"incrementUserProperty","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","text":"ApphudUserPropertyKey"},{"text":", ","kind":"text"},{"text":"by","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":")","kind":"text"}],"abstract":[{"text":"Increments a custom user property. Value must be one of: ","type":"text"},{"type":"codeVoice","code":"Int"},{"type":"text","text":", "},{"code":"Float","type":"codeVoice"},{"type":"text","text":", "},{"code":"Double","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"NSNumber"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/incrementUserProperty(key:by:)","url":"\/documentation\/apphudsdk\/apphud\/incrementuserproperty(key:by:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"incrementUserPropertyWithKey:by:"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"incrementUserPropertyWithKey:by:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"incrementUserPropertyWithKey:by:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"incrementUserPropertyWithKey:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","text":"ApphudUserPropertyKey","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"key"},{"text":" ","kind":"text"},{"kind":"identifier","text":"by:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"by","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"kind":"identifier","text":"Apphud"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/title","value":"ApphudUserPropertyKey"},{"op":"replace","value":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1incrementUserProperty(key:by:)\/title","value":"incrementUserPropertyWithKey:by:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1incrementUserProperty(key:by:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"incrementUserPropertyWithKey:by:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}