{"metadata":{"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)isSandbox","navigatorTitle":[{"text":"isSandbox","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ApphudSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSandbox","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isSandbox()","roleHeading":"Type Method","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"abstract":[{"text":"Determines if the current build is running in a sandbox environment, such as during development, testing, or TestFlight, as opposed to a production App Store build.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/isSandbox()"},"kind":"symbol","variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/issandbox()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/issandbox()"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSandbox"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"text":"","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the build is a sandbox (development, TestFlight) build; ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" if it’s an App Store build."}],"type":"paragraph"}]},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"Use this method to differentiate behavior or configurations between development\/testing and production environments.","type":"text"}]}],"type":"aside","name":"Note"}],"kind":"content"}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/isSandbox()":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/isSandbox()","url":"\/documentation\/apphudsdk\/apphud\/issandbox()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSandbox","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","abstract":[{"type":"text","text":"Determines if the current build is running in a sandbox environment, such as during development, testing, or TestFlight, as opposed to a production App Store build."}],"kind":"symbol","type":"topic","title":"isSandbox()","navigatorTitle":[{"kind":"identifier","text":"isSandbox"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","value":"isSandbox","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"isSandbox","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isSandbox"},{"kind":"text","text":";"}]}]}},{"value":"Apphud","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","op":"replace","value":[{"text":"Apphud","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1isSandbox()\/title","value":"isSandbox"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1isSandbox()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"isSandbox","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}