{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/loadFallbackPaywalls(callback:)"},"metadata":{"modules":[{"name":"ApphudSDK"}],"roleHeading":"Type Method","title":"loadFallbackPaywalls(callback:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadFallbackPaywalls","kind":"identifier"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"ApphudError","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol","externalID":"s:9ApphudSDK0A0C20loadFallbackPaywalls8callbackyySayAA0A7PaywallCGSg_AA0A5ErrorCSgtc_tFZ"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadFallbackPaywalls"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (["},{"kind":"typeIdentifier","text":"ApphudPaywall","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"kind":"text","text":"]?, "},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError","text":"ApphudError"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/loadfallbackpaywalls(callback:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Explicitly loads fallback paywalls from the json file, if it was added to the project resources."},{"type":"text","text":" "},{"text":"By default, SDK automatically tries to load paywalls from the JSON file, if possible.","type":"text"},{"text":" ","type":"text"},{"text":"However, developer can also call this method directly for more control.","type":"text"},{"text":" ","type":"text"},{"text":"For more details, visit https:\/\/docs.apphud.com\/docs\/paywalls#set-up-fallback-mode","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","kind":"symbol","abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"navigatorTitle":[{"text":"ApphudPaywall","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphudpaywall","title":"ApphudPaywall","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudPaywall","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/loadFallbackPaywalls(callback:)":{"kind":"symbol","title":"loadFallbackPaywalls(callback:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/loadFallbackPaywalls(callback:)","url":"\/documentation\/apphudsdk\/apphud\/loadfallbackpaywalls(callback:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadFallbackPaywalls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (["},{"text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError","text":"ApphudError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"text":"Explicitly loads fallback paywalls from the json file, if it was added to the project resources.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"By default, SDK automatically tries to load paywalls from the JSON file, if possible."},{"text":" ","type":"text"},{"text":"However, developer can also call this method directly for more control.","type":"text"},{"text":" ","type":"text"},{"text":"For more details, visit https:\/\/docs.apphud.com\/docs\/paywalls#set-up-fallback-mode","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudError":{"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudError"}],"url":"\/documentation\/apphudsdk\/apphuderror","title":"ApphudError","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudError"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud","title":"Apphud","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","value":"ApphudPaywall"},{"value":[{"text":"ApphudPaywall","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/navigatorTitle","value":[{"text":"ApphudPaywall","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/title","value":"ApphudError","op":"replace"},{"value":[{"kind":"identifier","text":"ApphudError"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/navigatorTitle","op":"replace","value":[{"text":"ApphudError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","op":"replace","value":"Apphud"},{"value":[{"kind":"identifier","text":"Apphud"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","op":"replace"},{"value":[{"text":"Apphud","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","op":"replace"}]}]}