{"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/logout()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logout"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"}],"role":"symbol","navigatorTitle":[{"text":"logoutWithCompletionHandler:","kind":"identifier"}],"roleHeading":"Type Method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)logoutWithCompletionHandler:","title":"logout()","modules":[{"name":"ApphudSDK"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logout","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is particularly useful in scenarios involving custom logout\/login flows, allowing you to manage the subscription status of each user more effectively."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Note","type":"text"}]},{"text":": If the previous user had an active subscription, a new logged-in user can still restore purchases on the same device. In this case, both users will be merged under the account of the user with the active subscription, due to the Apple ID being tied to the device.","type":"text"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/logout()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/logout()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Logs out the current user, clears all saved data, and resets the SDK to an uninitialized state. After calling this method, you must reinitialize the SDK with "},{"type":"codeVoice","code":"Apphud.start(...)"},{"type":"text","text":" or "},{"type":"codeVoice","code":"Apphud.manually(...)"},{"type":"text","text":" for a new user."}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/logout()":{"title":"logout()","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Logs out the current user, clears all saved data, and resets the SDK to an uninitialized state. After calling this method, you must reinitialize the SDK with "},{"code":"Apphud.start(...)","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"Apphud.manually(...)"},{"text":" for a new user.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logout","kind":"identifier"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"}],"url":"\/documentation\/apphudsdk\/apphud\/logout()","navigatorTitle":[{"kind":"identifier","text":"logoutWithCompletionHandler:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/logout()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"logoutWithCompletionHandler:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"logoutWithCompletionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"logoutWithCompletionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv()","kind":"typeIdentifier","text":"void (^)(void)"},{"kind":"text","text":") "},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"Apphud","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Apphud"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1logout()\/title","value":"logoutWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1logout()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"logoutWithCompletionHandler:","kind":"identifier"}]}]}]}