{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"migratePurchasesIfNeeded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscription","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudSubscription","text":"ApphudSubscription"},{"kind":"text","text":"]?, ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudNonRenewingPurchase","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudNonRenewingPurchase","text":"ApphudNonRenewingPurchase"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example:"}]},{"type":"codeListing","syntax":"swift","code":["   \/\/ hasPurchases - is your own boolean value indicating that current user is paying user.","   if hasPurchases {","       Apphud.migratePurchasesIfNeeded { _, _, _ in}","   }"]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You can remove this method after a some period of time, i.e. when you are sure that all paying users are already synced with Apphud."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/migratepurchasesifneeded(callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/migratepurchasesifneeded(callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/migratePurchasesIfNeeded(callback:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If you already have a live app with paying users and you want Apphud to track their purchases, you should import their App Store receipts into Apphud. Call this method at launch of your app for your paying users. This method should be used only to migrate existing paying users that are not yet tracked by Apphud."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"migratePurchasesIfNeededWithCallback:"}],"role":"symbol","title":"migratePurchasesIfNeeded(callback:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"migratePurchasesIfNeeded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"ApphudSubscription","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudSubscription"},{"kind":"text","text":"]?, ["},{"kind":"typeIdentifier","text":"ApphudNonRenewingPurchase","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudNonRenewingPurchase"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)migratePurchasesIfNeededWithCallback:","modules":[{"name":"ApphudSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"No longer needed for iOS 15+. Purchases migrate automatically."}]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"role":"symbol","title":"Apphud","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/migratePurchasesIfNeeded(callback:)":{"deprecated":true,"role":"symbol","title":"migratePurchasesIfNeeded(callback:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"migratePurchasesIfNeeded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"ApphudSubscription","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudSubscription"},{"kind":"text","text":"]?, ["},{"kind":"typeIdentifier","text":"ApphudNonRenewingPurchase","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudNonRenewingPurchase"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"If you already have a live app with paying users and you want Apphud to track their purchases, you should import their App Store receipts into Apphud. Call this method at launch of your app for your paying users. This method should be used only to migrate existing paying users that are not yet tracked by Apphud."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/migratePurchasesIfNeeded(callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"migratePurchasesIfNeededWithCallback:"}],"url":"\/documentation\/apphudsdk\/apphud\/migratepurchasesifneeded(callback:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudSubscription":{"role":"symbol","title":"ApphudSubscription","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudSubscription"}],"abstract":[{"type":"text","text":"Custom Apphud class containing all information about customer subscription."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudSubscription"}],"url":"\/documentation\/apphudsdk\/apphudsubscription"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudNonRenewingPurchase":{"role":"symbol","title":"ApphudNonRenewingPurchase","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudNonRenewingPurchase"}],"abstract":[{"type":"text","text":"Custom Apphud class containing all information about customer non-renewing purchase"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudNonRenewingPurchase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudNonRenewingPurchase"}],"url":"\/documentation\/apphudsdk\/apphudnonrenewingpurchase"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"migratePurchasesIfNeededWithCallback:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"migratePurchasesIfNeededWithCallback:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"migratePurchasesIfNeededWithCallback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<ApphudSubscription *> *, NSArray<ApphudNonRenewingPurchase *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*QS4_#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"kind":"identifier","text":"Apphud"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1migratePurchasesIfNeeded(callback:)\/title","value":"migratePurchasesIfNeededWithCallback:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1migratePurchasesIfNeeded(callback:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"migratePurchasesIfNeededWithCallback:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscription\/title","value":"ApphudSubscription"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscription\/fragments","value":[{"kind":"identifier","text":"ApphudSubscription"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudNonRenewingPurchase\/title","value":"ApphudNonRenewingPurchase"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudNonRenewingPurchase\/fragments","value":[{"kind":"identifier","text":"ApphudNonRenewingPurchase"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}