{"abstract":[{"text":"Opts the user out of tracking. This method should be called before SDK initialization. When called, it prevents the tracking of certain user parameters like IDFA, IDFV, and IP address by Apphud.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"optOutOfTracking"},{"kind":"text","text":"()"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"name":"Note","type":"aside","style":"note","content":[{"inlineContent":[{"text":"Consider the privacy implications and ensure compliance with relevant data protection regulations when opting users out of tracking.","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"metadata":{"role":"symbol","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)optOutOfTracking","symbolKind":"method","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"optOutOfTracking","kind":"identifier"}],"title":"optOutOfTracking()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optOutOfTracking","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"ApphudSDK"}],"roleHeading":"Type Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/optoutoftracking()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/optoutoftracking()"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/optOutOfTracking()"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud","title":"Apphud","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/optOutOfTracking()":{"abstract":[{"type":"text","text":"Opts the user out of tracking. This method should be called before SDK initialization. When called, it prevents the tracking of certain user parameters like IDFA, IDFV, and IP address by Apphud."}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"optOutOfTracking"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"optOutOfTracking","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphud\/optoutoftracking()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/optOutOfTracking()","title":"optOutOfTracking()","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"optOutOfTracking"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"optOutOfTracking"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"optOutOfTracking","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","op":"replace","value":[{"kind":"identifier","text":"Apphud"}]},{"value":[{"kind":"identifier","text":"Apphud"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","op":"replace"},{"value":"optOutOfTracking","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1optOutOfTracking()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"optOutOfTracking","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1optOutOfTracking()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}