{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paywallClosed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paywall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information  - "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.apphud.com\/docs\/events#paywall-closed"}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/paywallclosed(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/paywallclosed(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallClosed(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Logs “Paywall Closed” event that will be used in Apphud Dashboard."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paywallClosed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"kind":"text","text":")"}],"title":"paywallClosed(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)paywallClosed:","modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"paywallClosed:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"role":"symbol","title":"Apphud","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"https://docs.apphud.com/docs/events#paywall-closed":{"title":"Paywall Closed Event Documentation","titleInlineContent":[{"type":"text","text":"Paywall Closed Event Documentation"}],"type":"link","identifier":"https:\/\/docs.apphud.com\/docs\/events#paywall-closed","url":"https:\/\/docs.apphud.com\/docs\/events#paywall-closed"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"role":"symbol","title":"ApphudPaywall","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPaywall"}],"abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudPaywall"}],"url":"\/documentation\/apphudsdk\/apphudpaywall"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywallClosed(_:)":{"role":"symbol","title":"paywallClosed(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paywallClosed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Logs “Paywall Closed” event that will be used in Apphud Dashboard."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallClosed(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paywallClosed:"}],"url":"\/documentation\/apphudsdk\/apphud\/paywallclosed(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"paywallClosed:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"paywallClosed:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"paywallClosed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"paywall"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"kind":"identifier","text":"Apphud"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","value":"ApphudPaywall"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","value":[{"kind":"identifier","text":"ApphudPaywall"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallClosed(_:)\/title","value":"paywallClosed:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallClosed(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"paywallClosed:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}