{"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/paywall(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/paywall(_:)"]}],"metadata":{"title":"paywall(_:)","platforms":[],"modules":[{"name":"ApphudSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paywall","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier","text":"ApphudPaywall"},{"text":"?","kind":"text"}],"symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)paywall:completionHandler:","navigatorTitle":[{"text":"paywall:completionHandler:","kind":"identifier"}],"role":"symbol","roleHeading":"Type Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paywall","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall"},{"kind":"text","text":"?"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique identifier for the desired paywall."}]}],"name":"identifier"}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"An optional "},{"type":"codeVoice","code":"ApphudPaywall"},{"text":" object if found, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if no matching paywall is found.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"For immediate access without awaiting "},{"type":"codeVoice","code":"SKProduct"},{"text":"s, use ","type":"text"},{"type":"codeVoice","code":"ApphudDelegate"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"userDidLoad"},{"type":"text","text":" method or the callback in "},{"type":"codeVoice","code":"Apphud.start(...)"},{"type":"text","text":"."}],"type":"paragraph"},{"name":"Important","style":"important","type":"aside","content":[{"inlineContent":[{"type":"text","text":"This is deprecated method. Retrieve paywalls from within placements instead. See documentation for details: https:\/\/docs.apphud.com\/docs\/placements"}],"type":"paragraph"}]}],"kind":"content"}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywall(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Asynchronously retrieve a specific paywall by identifier configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner "},{"type":"codeVoice","code":"SKProduct"},{"text":"s are loaded from the App Store.","type":"text"}],"seeAlsoSections":[{"title":"Apphud Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/start(apiKey:userID:observerMode:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placement(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:callback:)-6dhy3","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/grantPromotional(daysCount:productId:permissionGroup:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/restorePurchases(callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasPremiumAccess()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasActiveSubscription()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)"],"generated":true}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Deprecated in favor of placement(_ identifier: String)"}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/hasPremiumAccess()":{"url":"\/documentation\/apphudsdk\/apphud\/haspremiumaccess()","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasPremiumAccess()","kind":"symbol","title":"hasPremiumAccess()","role":"symbol","abstract":[{"type":"text","text":"Determines if the user has active premium access through a subscription or a non-renewing purchase (lifetime)."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasPremiumAccess","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasPremiumAccess"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)":{"title":"willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","abstract":[{"type":"text","text":"Notifies Apphud when a purchase process is initiated from a paywall in "},{"type":"codeVoice","code":"Observer Mode"},{"text":", enabling the use of A\/B experiments. This method should be called right before executing your own purchase method, and it’s specifically required only when the SDK is in Observer Mode.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPurchaseProductFrom"},{"text":"(","kind":"text"},{"text":"paywallIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"placementIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"type":"topic","url":"\/documentation\/apphudsdk\/apphud\/willpurchaseproductfrom(paywallidentifier:placementidentifier:)","navigatorTitle":[{"kind":"identifier","text":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/start(apiKey:userID:observerMode:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/start(apiKey:userID:observerMode:callback:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Initializes Apphud SDK. Call this during the app’s launch."}],"title":"start(apiKey:userID:observerMode:callback:)","kind":"symbol","url":"\/documentation\/apphudsdk\/apphud\/start(apikey:userid:observermode:callback:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"observerMode"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"text":": ((","kind":"text"},{"text":"ApphudUser","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A4UserV"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywallShown(_:)":{"type":"topic","abstract":[{"type":"text","text":"Logs a “Paywall Shown” event which is required for A\/B Testing analytics."}],"url":"\/documentation\/apphudsdk\/apphud\/paywallshown(_:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paywallShown","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"paywallShown:","kind":"identifier"}],"role":"symbol","title":"paywallShown(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/checkEligibilityForIntroductoryOffer(product:callback:)":{"type":"topic","abstract":[{"type":"text","text":"Checks whether the given product is eligible for an introductory offer, which includes "},{"code":"free trial","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"pay as you go"},{"text":", or ","type":"text"},{"type":"codeVoice","code":"pay up front"},{"text":" options.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphud\/checkeligibilityforintroductoryoffer(product:callback:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"checkEligibilityForIntroductoryOffer","kind":"identifier"},{"kind":"text","text":"("},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","kind":"typeIdentifier","text":"ApphudBoolCallback"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"checkEligibilityForIntroductoryOfferWithProduct:callback:","kind":"identifier"}],"role":"symbol","title":"checkEligibilityForIntroductoryOffer(product:callback:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/restorePurchases(callback:)":{"url":"\/documentation\/apphudsdk\/apphud\/restorepurchases(callback:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/restorePurchases(callback:)","kind":"symbol","title":"restorePurchases(callback:)","role":"symbol","abstract":[{"text":"Implements the ","type":"text"},{"type":"codeVoice","code":"Restore Purchases"},{"type":"text","text":" mechanism. This method sends the current App Store Receipt to Apphud and returns information about the user’s subscriptions and in-app purchases."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"restorePurchases","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (["},{"text":"ApphudSubscription","preciseIdentifier":"s:9ApphudSDK0A12SubscriptionC","kind":"typeIdentifier"},{"kind":"text","text":"]?, ["},{"kind":"typeIdentifier","text":"ApphudNonRenewingPurchase","preciseIdentifier":"s:9ApphudSDK0A19NonRenewingPurchaseC"},{"text":"]?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/grantPromotional(daysCount:productId:permissionGroup:callback:)":{"title":"grantPromotional(daysCount:productId:permissionGroup:callback:)","url":"\/documentation\/apphudsdk\/apphud\/grantpromotional(dayscount:productid:permissiongroup:callback:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"grantPromotional"},{"text":"(","kind":"text"},{"text":"daysCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"productId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"permissionGroup"},{"text":": ","kind":"text"},{"text":"ApphudGroup","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudGroup"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"text":"?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/grantPromotional(daysCount:productId:permissionGroup:callback:)","abstract":[{"text":"Grants a free promotional subscription to the user. This method updates the user’s subscription status, and after this, the ","type":"text"},{"type":"codeVoice","code":"hasActiveSubscription()"},{"text":" method will return ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","navigatorTitle":[{"text":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/placement(_:)":{"url":"\/documentation\/apphudsdk\/apphud\/placement(_:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placement(_:)","kind":"symbol","title":"placement(_:)","role":"symbol","abstract":[{"text":"Asynchronously retrieve a specific placement by identifier configured in Product Hub > Placements, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"s are loaded from the App Store."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"placement","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"ApphudPlacement","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A9PlacementC"},{"text":"?","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/hasActiveSubscription()":{"title":"hasActiveSubscription()","abstract":[{"text":"Checks if the user has an active premium subscription.","type":"text"}],"kind":"symbol","url":"\/documentation\/apphudsdk\/apphud\/hasactivesubscription()","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasActiveSubscription()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hasActiveSubscription"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasActiveSubscription"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/setUserProperty(key:value:setOnce:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserProperty"},{"text":"(","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","text":"ApphudUserPropertyKey","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"setOnce"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setUserPropertyWithKey:value:setOnce:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Sets a custom user property in Apphud. The value assigned to this property must be of one of the following types: ","type":"text"},{"code":"Int","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"Float"},{"type":"text","text":", "},{"code":"Double","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"Bool"},{"type":"text","text":", "},{"code":"String","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"NSNumber"},{"text":", ","type":"text"},{"type":"codeVoice","code":"NSString"},{"type":"text","text":", "},{"type":"codeVoice","code":"NSNull"},{"type":"text","text":", or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/apphudsdk\/apphud\/setuserproperty(key:value:setonce:)","title":"setUserProperty(key:value:setOnce:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","role":"symbol","title":"ApphudPaywall","abstract":[{"text":"An object associated with purchases container (Paywall).","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPaywall"}],"url":"\/documentation\/apphudsdk\/apphudpaywall","navigatorTitle":[{"kind":"identifier","text":"ApphudPaywall"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywall(_:)":{"deprecated":true,"title":"paywall(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paywall","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywall(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paywall:completionHandler:"}],"url":"\/documentation\/apphudsdk\/apphud\/paywall(_:)","abstract":[{"type":"text","text":"Asynchronously retrieve a specific paywall by identifier configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner "},{"code":"SKProduct","type":"codeVoice"},{"type":"text","text":"s are loaded from the App Store."}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/addAttribution(data:from:identifer:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","role":"symbol","type":"topic","abstract":[{"text":"Submits attribution data to Apphud from your chosen attribution network provider.","type":"text"}],"kind":"symbol","title":"addAttribution(data:from:identifer:callback:)","url":"\/documentation\/apphudsdk\/apphud\/addattribution(data:from:identifer:callback:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addAttribution"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"data"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudAttributionProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@E@ApphudAttributionProvider"},{"text":", ","kind":"text"},{"text":"identifer","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"addAttributionWithData:from:identifer:callback:","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/checkEligibilityForPromotionalOffer(product:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkEligibilityForPromotionalOffer"},{"kind":"text","text":"("},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"checkEligibilityForPromotionalOfferWithProduct:callback:"}],"role":"symbol","abstract":[{"type":"text","text":"Checks whether the given product is eligible for any of its promotional offers."}],"url":"\/documentation\/apphudsdk\/apphud\/checkeligibilityforpromotionaloffer(product:callback:)","title":"checkEligibilityForPromotionalOffer(product:callback:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/purchase(_:callback:)-6dhy3":{"type":"topic","abstract":[{"text":"Initiates the purchase of an ","type":"text"},{"code":"ApphudProduct","type":"codeVoice"},{"type":"text","text":" object from an "},{"type":"codeVoice","code":"ApphudPaywall"},{"type":"text","text":" and optionally from "},{"code":"ApphudPlacement","type":"codeVoice"},{"type":"text","text":" and automatically submits the App Store Receipt to Apphud."}],"url":"\/documentation\/apphudsdk\/apphud\/purchase(_:callback:)-6dhy3","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:callback:)-6dhy3","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchase"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","text":"ApphudPurchaseResult","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"purchaseApphudProduct:callback:"}],"role":"symbol","title":"purchase(_:callback:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"paywall:completionHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"paywall:completionHandler:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:callback:)-6dhy3","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/grantPromotional(daysCount:productId:permissionGroup:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasPremiumAccess()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasActiveSubscription()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)"],"generated":true,"title":"Apphud Methods"}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"paywall:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"identifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"text":"void (^)(ApphudPaywall *)","preciseIdentifier":"c:BFv(#*$@M@ApphudSDK@objc(cs)ApphudPaywall)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasPremiumAccess()\/title","op":"replace","value":"hasPremiumAccess"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasPremiumAccess()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"hasPremiumAccess"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)\/title","op":"replace","value":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:","kind":"identifier"}]},{"op":"replace","value":"paywallShown:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallShown(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallShown(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"paywallShown:"}]},{"value":"checkEligibilityForIntroductoryOfferWithProduct:callback:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForIntroductoryOffer(product:callback:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForIntroductoryOffer(product:callback:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"checkEligibilityForIntroductoryOfferWithProduct:callback:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1grantPromotional(daysCount:productId:permissionGroup:callback:)\/title","value":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1grantPromotional(daysCount:productId:permissionGroup:callback:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasActiveSubscription()\/title","value":"hasActiveSubscription"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"hasActiveSubscription"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasActiveSubscription()\/fragments"},{"value":"setUserPropertyWithKey:value:setOnce:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1setUserProperty(key:value:setOnce:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setUserPropertyWithKey:value:setOnce:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1setUserProperty(key:value:setOnce:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","value":"ApphudPaywall","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","value":[{"kind":"identifier","text":"ApphudPaywall"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywall(_:)\/title","op":"replace","value":"paywall:completionHandler:"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywall(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"paywall:completionHandler:"}],"op":"replace"},{"value":"addAttributionWithData:from:identifer:callback:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1addAttribution(data:from:identifer:callback:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1addAttribution(data:from:identifer:callback:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"addAttributionWithData:from:identifer:callback:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForPromotionalOffer(product:callback:)\/title","value":"checkEligibilityForPromotionalOfferWithProduct:callback:"},{"value":[{"text":"+ ","kind":"text"},{"text":"checkEligibilityForPromotionalOfferWithProduct:callback:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForPromotionalOffer(product:callback:)\/fragments","op":"replace"},{"value":"purchaseApphudProduct:callback:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchase(_:callback:)-6dhy3\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchase(_:callback:)-6dhy3\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"purchaseApphudProduct:callback:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}