{"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallsDidLoadCallback(_:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/paywallsdidloadcallback(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/paywallsdidloadcallback(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paywallsDidLoadCallback"},{"text":"(([","kind":"text"},{"text":"ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"paywallsDidLoadCallback:"}],"platforms":[],"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)paywallsDidLoadCallback:","modules":[{"name":"ApphudSDK"}],"title":"paywallsDidLoadCallback(_:)","symbolKind":"method","role":"symbol","roleHeading":"Type Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"title":"Apphud Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/start(apiKey:userID:observerMode:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywalls()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placements()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywall(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placement(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placementsDidLoadCallback(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:callback:)-6dhy3","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/grantPromotional(daysCount:productId:permissionGroup:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/restorePurchases(callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasPremiumAccess()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasActiveSubscription()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)"],"generated":true}],"deprecationSummary":[{"inlineContent":[{"text":"Deprecated in favor of placementsDidLoadCallback(...)","type":"text"}],"type":"paragraph"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paywallsDidLoadCallback"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure that takes an array of "},{"code":"ApphudPaywall","type":"codeVoice"},{"type":"text","text":" objects and returns void."}]}]}],"kind":"parameters"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"For immediate access without awaiting "},{"type":"codeVoice","code":"SKProduct"},{"text":"s, use ","type":"text"},{"type":"codeVoice","code":"ApphudDelegate"},{"text":"’s ","type":"text"},{"type":"codeVoice","code":"userDidLoad"},{"text":" method or the callback in ","type":"text"},{"code":"Apphud.start(...)","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"},{"name":"Important","type":"aside","content":[{"inlineContent":[{"type":"text","text":"This is deprecated method. Retrieve paywalls from within placements instead. See documentation for details: https:\/\/docs.apphud.com\/docs\/placements"}],"type":"paragraph"}],"style":"important"}],"kind":"content"}],"abstract":[{"text":"Retrieves the paywalls configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"s are loaded from the App Store."}],"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/purchase(_:callback:)-6dhy3":{"title":"purchase(_:callback:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:callback:)-6dhy3","abstract":[{"type":"text","text":"Initiates the purchase of an "},{"type":"codeVoice","code":"ApphudProduct"},{"text":" object from an ","type":"text"},{"code":"ApphudPaywall","type":"codeVoice"},{"type":"text","text":" and optionally from "},{"code":"ApphudPlacement","type":"codeVoice"},{"text":" and automatically submits the App Store Receipt to Apphud.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"purchase"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ApphudProduct","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct"},{"kind":"text","text":", "},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"purchaseApphudProduct:callback:","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphud\/purchase(_:callback:)-6dhy3"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywalls()":{"title":"paywalls()","role":"symbol","url":"\/documentation\/apphudsdk\/apphud\/paywalls()","kind":"symbol","deprecated":true,"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paywalls"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywalls()","navigatorTitle":[{"kind":"identifier","text":"paywallsWithCompletionHandler:"}],"abstract":[{"text":"Asynchronously retrieves the paywalls configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"text":"s are loaded from the App Store.","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/checkEligibilityForIntroductoryOffer(product:callback:)":{"title":"checkEligibilityForIntroductoryOffer(product:callback:)","kind":"symbol","url":"\/documentation\/apphudsdk\/apphud\/checkeligibilityforintroductoryoffer(product:callback:)","role":"symbol","abstract":[{"text":"Checks whether the given product is eligible for an introductory offer, which includes ","type":"text"},{"code":"free trial","type":"codeVoice"},{"text":", ","type":"text"},{"code":"pay as you go","type":"codeVoice"},{"type":"text","text":", or "},{"type":"codeVoice","code":"pay up front"},{"text":" options.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkEligibilityForIntroductoryOffer"},{"text":"(","kind":"text"},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","text":"ApphudBoolCallback","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"checkEligibilityForIntroductoryOfferWithProduct:callback:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/setUserProperty(key:value:setOnce:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","title":"setUserProperty(key:value:setOnce:)","abstract":[{"text":"Sets a custom user property in Apphud. The value assigned to this property must be of one of the following types: ","type":"text"},{"type":"codeVoice","code":"Int"},{"type":"text","text":", "},{"code":"Float","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":", ","type":"text"},{"code":"Bool","type":"codeVoice"},{"type":"text","text":", "},{"code":"String","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"NSNumber"},{"type":"text","text":", "},{"type":"codeVoice","code":"NSString"},{"type":"text","text":", "},{"code":"NSNull","type":"codeVoice"},{"text":", or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/apphudsdk\/apphud\/setuserproperty(key:value:setonce:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setUserProperty","kind":"identifier"},{"kind":"text","text":"("},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ApphudUserPropertyKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"},{"kind":"text","text":", "},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"setOnce","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"setUserPropertyWithKey:value:setOnce:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/placement(_:)":{"title":"placement(_:)","role":"symbol","url":"\/documentation\/apphudsdk\/apphud\/placement(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"placement","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A9PlacementC","text":"ApphudPlacement","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"text":"Asynchronously retrieve a specific placement by identifier configured in Product Hub > Placements, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"code":"SKProduct","type":"codeVoice"},{"type":"text","text":"s are loaded from the App Store."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placement(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywallsDidLoadCallback(_:)":{"title":"paywallsDidLoadCallback(_:)","role":"symbol","url":"\/documentation\/apphudsdk\/apphud\/paywallsdidloadcallback(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paywallsDidLoadCallback"},{"text":"(([","kind":"text"},{"text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"paywallsDidLoadCallback:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Retrieves the paywalls configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner "},{"code":"SKProduct","type":"codeVoice"},{"text":"s are loaded from the App Store.","type":"text"}],"deprecated":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallsDidLoadCallback(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","url":"\/documentation\/apphudsdk","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"title":"ApphudSDK","type":"topic","role":"collection","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPurchaseProductFrom"},{"kind":"text","text":"("},{"text":"paywallIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placementIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","abstract":[{"text":"Notifies Apphud when a purchase process is initiated from a paywall in ","type":"text"},{"type":"codeVoice","code":"Observer Mode"},{"text":", enabling the use of A\/B experiments. This method should be called right before executing your own purchase method, and it’s specifically required only when the SDK is in Observer Mode.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphud\/willpurchaseproductfrom(paywallidentifier:placementidentifier:)","title":"willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/checkEligibilityForPromotionalOffer(product:callback:)":{"kind":"symbol","url":"\/documentation\/apphudsdk\/apphud\/checkeligibilityforpromotionaloffer(product:callback:)","abstract":[{"text":"Checks whether the given product is eligible for any of its promotional offers.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)","navigatorTitle":[{"text":"checkEligibilityForPromotionalOfferWithProduct:callback:","kind":"identifier"}],"type":"topic","title":"checkEligibilityForPromotionalOffer(product:callback:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkEligibilityForPromotionalOffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"product"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier","text":"SKProduct"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"text":"ApphudBoolCallback","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","title":"ApphudPaywall","abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudPaywall","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/apphudsdk\/apphudpaywall","navigatorTitle":[{"text":"ApphudPaywall","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/hasPremiumAccess()":{"title":"hasPremiumAccess()","role":"symbol","url":"\/documentation\/apphudsdk\/apphud\/haspremiumaccess()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hasPremiumAccess","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"hasPremiumAccess","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Determines if the user has active premium access through a subscription or a non-renewing purchase (lifetime).","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasPremiumAccess()"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywallShown(_:)":{"title":"paywallShown(_:)","role":"symbol","url":"\/documentation\/apphudsdk\/apphud\/paywallshown(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paywallShown","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"paywallShown:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Logs a “Paywall Shown” event which is required for A\/B Testing analytics.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/restorePurchases(callback:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/restorePurchases(callback:)","abstract":[{"text":"Implements the ","type":"text"},{"type":"codeVoice","code":"Restore Purchases"},{"type":"text","text":" mechanism. This method sends the current App Store Receipt to Apphud and returns information about the user’s subscriptions and in-app purchases."}],"title":"restorePurchases(callback:)","url":"\/documentation\/apphudsdk\/apphud\/restorepurchases(callback:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restorePurchases"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"text":": ([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12SubscriptionC","text":"ApphudSubscription"},{"kind":"text","text":"]?, ["},{"preciseIdentifier":"s:9ApphudSDK0A19NonRenewingPurchaseC","text":"ApphudNonRenewingPurchase","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/grantPromotional(daysCount:productId:permissionGroup:callback:)":{"title":"grantPromotional(daysCount:productId:permissionGroup:callback:)","role":"symbol","kind":"symbol","url":"\/documentation\/apphudsdk\/apphud\/grantpromotional(dayscount:productid:permissiongroup:callback:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"grantPromotional","kind":"identifier"},{"text":"(","kind":"text"},{"text":"daysCount","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"productId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"permissionGroup"},{"text":": ","kind":"text"},{"text":"ApphudGroup","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudGroup"},{"kind":"text","text":"?, "},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","text":"ApphudBoolCallback"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/grantPromotional(daysCount:productId:permissionGroup:callback:)","navigatorTitle":[{"text":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:","kind":"identifier"}],"abstract":[{"text":"Grants a free promotional subscription to the user. This method updates the user’s subscription status, and after this, the ","type":"text"},{"type":"codeVoice","code":"hasActiveSubscription()"},{"text":" method will return ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/placements()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placements()","abstract":[{"text":"Asynchronously retrieves the paywall placements configured in Product Hub > Placements, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"code":"SKProduct","type":"codeVoice"},{"text":"s are loaded from the App Store.","type":"text"}],"title":"placements()","url":"\/documentation\/apphudsdk\/apphud\/placements()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placements"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> ["},{"text":"ApphudPlacement","preciseIdentifier":"s:9ApphudSDK0A9PlacementC","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywall(_:)":{"title":"paywall(_:)","role":"symbol","url":"\/documentation\/apphudsdk\/apphud\/paywall(_:)","kind":"symbol","deprecated":true,"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paywall"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier","text":"ApphudPaywall"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywall(_:)","navigatorTitle":[{"kind":"identifier","text":"paywall:completionHandler:"}],"abstract":[{"text":"Asynchronously retrieve a specific paywall by identifier configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"text":"s are loaded from the App Store.","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/addAttribution(data:from:identifer:callback:)":{"kind":"symbol","abstract":[{"text":"Submits attribution data to Apphud from your chosen attribution network provider.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","url":"\/documentation\/apphudsdk\/apphud\/addattribution(data:from:identifer:callback:)","navigatorTitle":[{"kind":"identifier","text":"addAttributionWithData:from:identifer:callback:"}],"title":"addAttribution(data:from:identifer:callback:)","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAttribution"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@E@ApphudAttributionProvider","kind":"typeIdentifier","text":"ApphudAttributionProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"identifer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","text":"ApphudBoolCallback","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/hasActiveSubscription()":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasActiveSubscription"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hasActiveSubscription"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasActiveSubscription()","abstract":[{"text":"Checks if the user has an active premium subscription.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphud\/hasactivesubscription()","title":"hasActiveSubscription()","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/placementsDidLoadCallback(_:)":{"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"placementsDidLoadCallback","kind":"identifier"},{"text":"(([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A9PlacementC","text":"ApphudPlacement"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placementsDidLoadCallback(_:)","kind":"symbol","url":"\/documentation\/apphudsdk\/apphud\/placementsdidloadcallback(_:)","title":"placementsDidLoadCallback(_:)","abstract":[{"text":"Retrieves the placements configured in Product Hub > Placements, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"code":"SKProduct","type":"codeVoice"},{"text":"s are loaded from the App Store.","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/start(apiKey:userID:observerMode:callback:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiKey"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"userID","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"observerMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ((","kind":"text"},{"text":"ApphudUser","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A4UserV"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Initializes Apphud SDK. Call this during the app’s launch.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/start(apiKey:userID:observerMode:callback:)","url":"\/documentation\/apphudsdk\/apphud\/start(apikey:userid:observermode:callback:)","title":"start(apiKey:userID:observerMode:callback:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"paywallsDidLoadCallback:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"paywallsDidLoadCallback:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":[{"title":"Apphud Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywalls()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywall(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:callback:)-6dhy3","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/grantPromotional(daysCount:productId:permissionGroup:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasPremiumAccess()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasActiveSubscription()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)"],"generated":true}],"op":"replace"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"paywallsDidLoadCallback:"},{"kind":"text","text":"("},{"text":"void (^)(NSArray<ApphudPaywall *> *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchase(_:callback:)-6dhy3\/title","value":"purchaseApphudProduct:callback:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchase(_:callback:)-6dhy3\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"purchaseApphudProduct:callback:","kind":"identifier"}]},{"value":"paywallsWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywalls()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywalls()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"paywallsWithCompletionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForIntroductoryOffer(product:callback:)\/title","value":"checkEligibilityForIntroductoryOfferWithProduct:callback:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"checkEligibilityForIntroductoryOfferWithProduct:callback:"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForIntroductoryOffer(product:callback:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1setUserProperty(key:value:setOnce:)\/title","op":"replace","value":"setUserPropertyWithKey:value:setOnce:"},{"value":[{"kind":"text","text":"+ "},{"text":"setUserPropertyWithKey:value:setOnce:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1setUserProperty(key:value:setOnce:)\/fragments"},{"value":"paywallsDidLoadCallback:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallsDidLoadCallback(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallsDidLoadCallback(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"paywallsDidLoadCallback:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)\/title","value":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForPromotionalOffer(product:callback:)\/title","value":"checkEligibilityForPromotionalOfferWithProduct:callback:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForPromotionalOffer(product:callback:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"checkEligibilityForPromotionalOfferWithProduct:callback:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","value":"ApphudPaywall","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","op":"replace","value":[{"text":"ApphudPaywall","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasPremiumAccess()\/title","op":"replace","value":"hasPremiumAccess"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasPremiumAccess()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"hasPremiumAccess"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallShown(_:)\/title","value":"paywallShown:"},{"value":[{"kind":"text","text":"+ "},{"text":"paywallShown:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallShown(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1grantPromotional(daysCount:productId:permissionGroup:callback:)\/title","value":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1grantPromotional(daysCount:productId:permissionGroup:callback:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywall(_:)\/title","value":"paywall:completionHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywall(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"paywall:completionHandler:"}]},{"value":"addAttributionWithData:from:identifer:callback:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1addAttribution(data:from:identifer:callback:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"addAttributionWithData:from:identifer:callback:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1addAttribution(data:from:identifer:callback:)\/fragments"},{"op":"replace","value":"hasActiveSubscription","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasActiveSubscription()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasActiveSubscription()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"hasActiveSubscription"}]}]}]}