{"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallsDidLoadCallback(maxAttempts:_:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/paywallsdidloadcallback(maxattempts:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/paywallsdidloadcallback(maxattempts:_:)"]}],"metadata":{"title":"paywallsDidLoadCallback(maxAttempts:_:)","symbolKind":"method","role":"symbol","roleHeading":"Type Method","platforms":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paywallsDidLoadCallback","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"maxAttempts"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall"},{"kind":"text","text":"], "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"paywallsDidLoadCallbackWithMaxAttempts::","kind":"identifier"}],"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)paywallsDidLoadCallbackWithMaxAttempts::","modules":[{"name":"ApphudSDK"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Deprecated in favor of fetchPlacements(...)"}],"type":"paragraph"}],"sections":[],"abstract":[{"text":"Retrieves the paywalls configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"text":"s are loaded from the App Store.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paywallsDidLoadCallback"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"maxAttempts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" = APPHUD_DEFAULT_RETRIES, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (["},{"text":"ApphudPaywall","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":"], ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"maxAttempts","content":[{"type":"paragraph","inlineContent":[{"text":"Number of request attempts before throwing an error. Must be between 1 and 10. Default value is 3.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A closure that takes an array of ","type":"text"},{"code":"ApphudPaywall","type":"codeVoice"},{"type":"text","text":" objects and returns void."}]}],"name":"callback"},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"Optional StoreKit Error that may occur while fetching products from the App Store. You might want to retry the request if the error comes out.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For immediate access without awaiting "},{"type":"codeVoice","code":"SKProduct"},{"text":"s, use ","type":"text"},{"code":"ApphudDelegate","type":"codeVoice"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"userDidLoad"},{"type":"text","text":" method or the callback in "},{"code":"Apphud.start(...)","type":"codeVoice"},{"type":"text","text":"."}]},{"name":"Important","style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This is deprecated method. Retrieve paywalls from within placements instead. See documentation for details: https:\/\/docs.apphud.com\/docs\/placements"}]}],"type":"aside"}],"kind":"content"}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","navigatorTitle":[{"text":"ApphudPaywall","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPaywall"}],"kind":"symbol","title":"ApphudPaywall","role":"symbol","type":"topic","url":"\/documentation\/apphudsdk\/apphudpaywall","abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywallsDidLoadCallback(maxAttempts:_:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallsDidLoadCallback(maxAttempts:_:)","role":"symbol","kind":"symbol","title":"paywallsDidLoadCallback(maxAttempts:_:)","deprecated":true,"type":"topic","abstract":[{"text":"Retrieves the paywalls configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"s are loaded from the App Store."}],"navigatorTitle":[{"kind":"identifier","text":"paywallsDidLoadCallbackWithMaxAttempts::"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paywallsDidLoadCallback"},{"text":"(","kind":"text"},{"text":"maxAttempts","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ([","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"url":"\/documentation\/apphudsdk\/apphud\/paywallsdidloadcallback(maxattempts:_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","url":"\/documentation\/apphudsdk","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","abstract":[]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"kind":"symbol","title":"Apphud","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"paywallsDidLoadCallbackWithMaxAttempts::","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"paywallsDidLoadCallbackWithMaxAttempts::","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"paywallsDidLoadCallbackWithMaxAttempts:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"maxAttempts","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)","text":"void (^)(NSArray<ApphudPaywall *> *, NSError *)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","value":"ApphudPaywall"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","op":"replace","value":[{"text":"ApphudPaywall","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallsDidLoadCallback(maxAttempts:_:)\/title","op":"replace","value":"paywallsDidLoadCallbackWithMaxAttempts::"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallsDidLoadCallback(maxAttempts:_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"paywallsDidLoadCallbackWithMaxAttempts::"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"value":[{"text":"Apphud","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments"}]}]}