{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paywalls"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> ["},{"text":"ApphudPaywall","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"An array of ","type":"text"},{"type":"codeVoice","code":"ApphudPaywall"},{"type":"text","text":" objects, representing the configured paywalls."}],"type":"paragraph"}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"For immediate access without awaiting "},{"type":"codeVoice","code":"SKProduct"},{"text":"s, use ","type":"text"},{"type":"codeVoice","code":"rawPaywalls()"},{"type":"text","text":" method."}],"type":"paragraph"},{"style":"important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This is deprecated method. Retrieve paywalls from within placements instead. See documentation for details: https:\/\/docs.apphud.com\/docs\/paywalls"}]}],"name":"Important"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywalls()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Asynchronously retrieves the paywalls configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner "},{"type":"codeVoice","code":"SKProduct"},{"text":"s are loaded from the App Store.","type":"text"}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/paywalls()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/paywalls()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"paywalls()","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)paywallsWithCompletionHandler:","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paywalls","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ["},{"text":"ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":"]","kind":"text"}],"modules":[{"name":"ApphudSDK"}],"role":"symbol","platforms":[],"roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"paywallsWithCompletionHandler:"}]},"deprecationSummary":[{"inlineContent":[{"text":"Deprecated in favor of placements()","type":"text"}],"type":"paragraph"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"title":"ApphudPaywall","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","role":"symbol","kind":"symbol","abstract":[{"text":"An object associated with purchases container (Paywall).","type":"text"}],"url":"\/documentation\/apphudsdk\/apphudpaywall","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ApphudPaywall","kind":"identifier"}],"navigatorTitle":[{"text":"ApphudPaywall","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywalls()":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywalls()","url":"\/documentation\/apphudsdk\/apphud\/paywalls()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paywalls","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"text":" -> [","kind":"text"},{"text":"ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":"]","kind":"text"}],"deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"Asynchronously retrieves the paywalls configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner "},{"type":"codeVoice","code":"SKProduct"},{"text":"s are loaded from the App Store.","type":"text"}],"kind":"symbol","type":"topic","title":"paywalls()","navigatorTitle":[{"text":"paywallsWithCompletionHandler:","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"paywallsWithCompletionHandler:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"paywallsWithCompletionHandler:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"paywallsWithCompletionHandler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray)","kind":"typeIdentifier","text":"void (^)(NSArray<ApphudPaywall *> *)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"ApphudPaywall","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","op":"replace"},{"value":[{"text":"ApphudPaywall","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywalls()\/title","value":"paywallsWithCompletionHandler:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"paywallsWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywalls()\/fragments"},{"op":"replace","value":"Apphud","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"text":"Apphud","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}