{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/pendingrulescreencontroller()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/pendingrulescreencontroller()"]}],"metadata":{"roleHeading":"Type Method","role":"symbol","title":"pendingRuleScreenController()","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)pendingRuleScreenController","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pendingRuleScreenController"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"pendingRuleScreenController","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ApphudSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/pendingRuleScreenController()"},"abstract":[{"text":"Retrieves the view controller for the Screen that is pending presentation. This screen is usually triggered by a pending Rule in Apphud. You have the option to present this Screen manually or use the ","type":"text"},{"type":"codeVoice","code":"showPendingScreen"},{"type":"text","text":" method."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pendingRuleScreenController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional "},{"type":"codeVoice","code":"UIViewController"},{"text":" representing the Screen that is pending for presentation. Returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if there is no Screen currently pending.","type":"text"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this method to retrieve the view controller for a delayed Screen if you need to present it manually or modify it before presentation."}]}]}]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/pendingRuleScreenController()":{"url":"\/documentation\/apphudsdk\/apphud\/pendingrulescreencontroller()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"pendingRuleScreenController","kind":"identifier"}],"abstract":[{"type":"text","text":"Retrieves the view controller for the Screen that is pending presentation. This screen is usually triggered by a pending Rule in Apphud. You have the option to present this Screen manually or use the "},{"code":"showPendingScreen","type":"codeVoice"},{"text":" method.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/pendingRuleScreenController()","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pendingRuleScreenController"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"pendingRuleScreenController()"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"url":"\/documentation\/apphudsdk\/apphud","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","title":"Apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"pendingRuleScreenController","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"pendingRuleScreenController"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"pendingRuleScreenController"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"An optional ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" representing the Screen that is pending for presentation. Returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if there is no Screen currently pending."}]}]}},{"value":"pendingRuleScreenController","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1pendingRuleScreenController()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"pendingRuleScreenController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1pendingRuleScreenController()\/fragments","op":"replace"},{"value":"Apphud","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","op":"replace"},{"value":[{"text":"Apphud","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments"},{"value":[{"text":"Apphud","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","op":"replace"}]}]}