{"metadata":{"role":"symbol","title":"permissionGroups()","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"permissionGroups","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudGroup","text":"ApphudGroup"},{"text":"]?","kind":"text"}],"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)permissionGroupsWithCompletionHandler:","navigatorTitle":[{"text":"permissionGroupsWithCompletionHandler:","kind":"identifier"}],"modules":[{"name":"ApphudSDK"}]},"abstract":[{"type":"text","text":"Asynchronously fetches permission groups configured in the Apphud > Product Hub. Note that this method may return an empty array at the first app launch until products are loaded. Groups are cached on the device."}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"permissionGroups","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudGroup","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup","text":"ApphudGroup"},{"kind":"text","text":"]?"}]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional array of "},{"code":"ApphudGroup","type":"codeVoice"},{"text":" objects, representing the permission groups.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/permissiongroups()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/permissiongroups()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/permissionGroups()"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/permissionGroups()":{"abstract":[{"type":"text","text":"Asynchronously fetches permission groups configured in the Apphud > Product Hub. Note that this method may return an empty array at the first app launch until products are loaded. Groups are cached on the device."}],"url":"\/documentation\/apphudsdk\/apphud\/permissiongroups()","title":"permissionGroups()","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/permissionGroups()","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"permissionGroups"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"ApphudGroup","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudGroup"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"permissionGroupsWithCompletionHandler:"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudGroup":{"abstract":[{"type":"text","text":"Apphud class which describes products permission groups"}],"url":"\/documentation\/apphudsdk\/apphudgroup","title":"ApphudGroup","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudGroup"}],"navigatorTitle":[{"text":"ApphudGroup","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","url":"\/documentation\/apphudsdk","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","abstract":[]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"kind":"symbol","title":"Apphud","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"permissionGroupsWithCompletionHandler:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"permissionGroupsWithCompletionHandler:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"permissionGroupsWithCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray)","text":"void (^)(NSArray<ApphudGroup *> *)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1permissionGroups()\/title","value":"permissionGroupsWithCompletionHandler:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"permissionGroupsWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1permissionGroups()\/fragments"},{"value":"ApphudGroup","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudGroup\/title"},{"value":[{"text":"ApphudGroup","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudGroup\/fragments"},{"op":"replace","value":"Apphud","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"text":"Apphud","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}