{"metadata":{"role":"symbol","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placements"},{"text":"(","kind":"text"},{"text":"maxAttempts","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"ApphudPlacement","preciseIdentifier":"s:9ApphudSDK0A9PlacementC","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"externalID":"s:9ApphudSDK0A0C10placements11maxAttemptsSayAA0A9PlacementCGSi_tYaFZ","title":"placements(maxAttempts:)","modules":[{"name":"ApphudSDK"}],"symbolKind":"method"},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placements(maxAttempts:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placements"},{"kind":"text","text":"("},{"text":"maxAttempts","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = APPHUD_DEFAULT_RETRIES) ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"ApphudPlacement","preciseIdentifier":"s:9ApphudSDK0A9PlacementC","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPlacement"},{"kind":"text","text":"]"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Number of request attempts before throwing an error. Must be between 1 and 10. Default value is 3.","type":"text"}]}],"name":"maxAttempts"}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An array of ","type":"text"},{"type":"codeVoice","code":"ApphudPlacement"},{"type":"text","text":" objects, representing the configured placements."}]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A placement is a specific location within a user’s journey (such as onboarding, settings, etc.) where its internal paywall is intended to be displayed. See documentation for details: https:\/\/docs.apphud.com\/docs\/placements."}]},{"name":"Important","style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In case of network issues this method may return empty array. To get the possible error use "},{"code":"fetchPlacements","type":"codeVoice"},{"type":"text","text":" method instead."}]}],"type":"aside"},{"inlineContent":[{"text":"For immediate access without awaiting ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"text":"s, use ","type":"text"},{"type":"codeVoice","code":"rawPlacements()"},{"text":" method.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/placements(maxattempts:)"]}],"abstract":[{"text":"Asynchronously retrieves the paywall placements configured in Product Hub > Placements, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"s are loaded from the App Store."}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/placements(maxAttempts:)":{"kind":"symbol","role":"symbol","abstract":[{"text":"Asynchronously retrieves the paywall placements configured in Product Hub > Placements, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"s are loaded from the App Store."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placements(maxAttempts:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"placements"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxAttempts"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A9PlacementC","text":"ApphudPlacement","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"placements(maxAttempts:)","url":"\/documentation\/apphudsdk\/apphud\/placements(maxattempts:)","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"url":"\/documentation\/apphudsdk\/apphud","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","title":"Apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPlacement":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPlacement","title":"ApphudPlacement","url":"\/documentation\/apphudsdk\/apphudplacement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPlacement"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudPlacement"}],"type":"topic","abstract":[{"text":"A placement is a specific location within a user’s journey (such as onboarding, settings, etc.) where its internal paywall is intended to be displayed.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"text":"Apphud","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","value":[{"kind":"identifier","text":"Apphud"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}