{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/products"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/products"]}],"sections":[],"metadata":{"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cpy)storeKitProducts","modules":[{"name":"ApphudSDK"}],"roleHeading":"Type Property","title":"products","navigatorTitle":[{"text":"storeKitProducts","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"products"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct"},{"text":"]?","kind":"text"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(storeKitProducts) ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"products"},{"text":": [","kind":"text"},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"This method returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the products have not yet been fetched from the App Store. To ensure functionality, configure Product Hub in Apphud."}],"type":"paragraph"}]},{"name":"Important","style":"important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"As a best practice, instead of using this method directly, implement your paywall logic through the Apphud Dashboard for more effective paywall management and to leverage Apphud’s functionalities.","type":"text"}]}]}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/products"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"abstract":[{"type":"text","text":"Retrieves an array of "},{"code":"SKProduct","type":"codeVoice"},{"text":" objects that were added in the Apphud dashboard (Apphud > Product Hub > Products). This property returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the products have not been fetched from the App Store yet.","type":"text"}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/products":{"url":"\/documentation\/apphudsdk\/apphud\/products","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/products","type":"topic","title":"products","navigatorTitle":[{"kind":"identifier","text":"storeKitProducts"}],"abstract":[{"text":"Retrieves an array of ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"text":" objects that were added in the Apphud dashboard (Apphud > Product Hub > Products). This property returns ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the products have not been fetched from the App Store yet."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"products","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier","text":"SKProduct"},{"kind":"text","text":"]?"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"storeKitProducts","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"storeKitProducts"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<SKProduct *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"storeKitProducts"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"Apphud","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title"},{"value":[{"kind":"identifier","text":"Apphud"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1products\/title","value":"storeKitProducts"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1products\/fragments","op":"replace","value":[{"text":"storeKitProducts","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}