{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"metadata":{"modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"text":"purchaseApphudProduct:callback:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"purchase","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct"},{"kind":"text","text":", "},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","kind":"typeIdentifier","text":"ApphudPurchaseResult"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"roleHeading":"Type Method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)purchaseApphudProduct:callback:","symbolKind":"method","title":"purchase(_:callback:)","role":"symbol"},"abstract":[{"type":"text","text":"Initiates the purchase of an "},{"type":"codeVoice","code":"ApphudProduct"},{"text":" object from an ","type":"text"},{"code":"ApphudPaywall","type":"codeVoice"},{"type":"text","text":" and optionally from "},{"type":"codeVoice","code":"ApphudPlacement"},{"text":" and automatically submits the App Store Receipt to Apphud.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/start(apiKey:userID:observerMode:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywall(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placement(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/grantPromotional(daysCount:productId:permissionGroup:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/restorePurchases(callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasPremiumAccess()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasActiveSubscription()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)"],"generated":true,"title":"Apphud Methods"}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:callback:)-6dhy3","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/purchase(_:callback:)-6dhy3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/purchase(_:callback:)-6dhy3"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"text":"(purchaseApphudProduct:callback:) ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchase"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"product","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","kind":"typeIdentifier","text":"ApphudProduct","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct"},{"kind":"text","text":", "},{"text":"callback","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","text":"ApphudPurchaseResult"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"product","content":[{"inlineContent":[{"text":"Required. An ","type":"text"},{"type":"codeVoice","code":"ApphudProduct"},{"type":"text","text":" object from your "},{"type":"codeVoice","code":"ApphudPaywall"},{"text":". Configure placements and paywalls in Apphud Dashboard > Product Hub before using.","type":"text"}],"type":"paragraph"}]},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. Returns an "},{"type":"codeVoice","code":"ApphudPurchaseResult"},{"text":" object.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"aside","style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You can purchase products using your own code; Apphud will still receive the App Store receipt."}]}]}]}],"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"url":"\/documentation\/apphudsdk\/apphudpurchaseresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudPurchaseResult","kind":"identifier"}],"abstract":[{"text":"General class that is returned in purchase block.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","navigatorTitle":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"kind":"symbol","role":"symbol","title":"ApphudPurchaseResult"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/hasActiveSubscription()":{"title":"hasActiveSubscription()","abstract":[{"text":"Checks if the user has an active premium subscription.","type":"text"}],"kind":"symbol","url":"\/documentation\/apphudsdk\/apphud\/hasactivesubscription()","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasActiveSubscription()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hasActiveSubscription"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasActiveSubscription"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)":{"title":"willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","abstract":[{"type":"text","text":"Notifies Apphud when a purchase process is initiated from a paywall in "},{"type":"codeVoice","code":"Observer Mode"},{"text":", enabling the use of A\/B experiments. This method should be called right before executing your own purchase method, and it’s specifically required only when the SDK is in Observer Mode.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPurchaseProductFrom"},{"text":"(","kind":"text"},{"text":"paywallIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"placementIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"type":"topic","url":"\/documentation\/apphudsdk\/apphud\/willpurchaseproductfrom(paywallidentifier:placementidentifier:)","navigatorTitle":[{"kind":"identifier","text":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/hasPremiumAccess()":{"url":"\/documentation\/apphudsdk\/apphud\/haspremiumaccess()","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasPremiumAccess()","kind":"symbol","title":"hasPremiumAccess()","role":"symbol","abstract":[{"type":"text","text":"Determines if the user has active premium access through a subscription or a non-renewing purchase (lifetime)."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasPremiumAccess","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasPremiumAccess"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/placement(_:)":{"url":"\/documentation\/apphudsdk\/apphud\/placement(_:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/placement(_:)","kind":"symbol","title":"placement(_:)","role":"symbol","abstract":[{"text":"Asynchronously retrieve a specific placement by identifier configured in Product Hub > Placements, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"s are loaded from the App Store."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"placement","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"ApphudPlacement","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A9PlacementC"},{"text":"?","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/purchase(_:callback:)-6dhy3":{"type":"topic","abstract":[{"text":"Initiates the purchase of an ","type":"text"},{"code":"ApphudProduct","type":"codeVoice"},{"type":"text","text":" object from an "},{"type":"codeVoice","code":"ApphudPaywall"},{"type":"text","text":" and optionally from "},{"code":"ApphudPlacement","type":"codeVoice"},{"type":"text","text":" and automatically submits the App Store Receipt to Apphud."}],"url":"\/documentation\/apphudsdk\/apphud\/purchase(_:callback:)-6dhy3","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:callback:)-6dhy3","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchase"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","text":"ApphudPurchaseResult","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"purchaseApphudProduct:callback:"}],"role":"symbol","title":"purchase(_:callback:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywallShown(_:)":{"type":"topic","abstract":[{"type":"text","text":"Logs a “Paywall Shown” event which is required for A\/B Testing analytics."}],"url":"\/documentation\/apphudsdk\/apphud\/paywallshown(_:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paywallShown","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"paywallShown:","kind":"identifier"}],"role":"symbol","title":"paywallShown(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/checkEligibilityForIntroductoryOffer(product:callback:)":{"type":"topic","abstract":[{"type":"text","text":"Checks whether the given product is eligible for an introductory offer, which includes "},{"code":"free trial","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"pay as you go"},{"text":", or ","type":"text"},{"type":"codeVoice","code":"pay up front"},{"text":" options.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphud\/checkeligibilityforintroductoryoffer(product:callback:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"checkEligibilityForIntroductoryOffer","kind":"identifier"},{"kind":"text","text":"("},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","kind":"typeIdentifier","text":"ApphudBoolCallback"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"checkEligibilityForIntroductoryOfferWithProduct:callback:","kind":"identifier"}],"role":"symbol","title":"checkEligibilityForIntroductoryOffer(product:callback:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/setUserProperty(key:value:setOnce:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserProperty"},{"text":"(","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","text":"ApphudUserPropertyKey","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"setOnce"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setUserPropertyWithKey:value:setOnce:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Sets a custom user property in Apphud. The value assigned to this property must be of one of the following types: ","type":"text"},{"code":"Int","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"Float"},{"type":"text","text":", "},{"code":"Double","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"Bool"},{"type":"text","text":", "},{"code":"String","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"NSNumber"},{"text":", ","type":"text"},{"type":"codeVoice","code":"NSString"},{"type":"text","text":", "},{"type":"codeVoice","code":"NSNull"},{"type":"text","text":", or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/apphudsdk\/apphud\/setuserproperty(key:value:setonce:)","title":"setUserProperty(key:value:setOnce:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/checkEligibilityForPromotionalOffer(product:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkEligibilityForPromotionalOffer"},{"kind":"text","text":"("},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"checkEligibilityForPromotionalOfferWithProduct:callback:"}],"role":"symbol","abstract":[{"type":"text","text":"Checks whether the given product is eligible for any of its promotional offers."}],"url":"\/documentation\/apphudsdk\/apphud\/checkeligibilityforpromotionaloffer(product:callback:)","title":"checkEligibilityForPromotionalOffer(product:callback:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/grantPromotional(daysCount:productId:permissionGroup:callback:)":{"title":"grantPromotional(daysCount:productId:permissionGroup:callback:)","url":"\/documentation\/apphudsdk\/apphud\/grantpromotional(dayscount:productid:permissiongroup:callback:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"grantPromotional"},{"text":"(","kind":"text"},{"text":"daysCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"productId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"permissionGroup"},{"text":": ","kind":"text"},{"text":"ApphudGroup","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudGroup"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"text":"?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/grantPromotional(daysCount:productId:permissionGroup:callback:)","abstract":[{"text":"Grants a free promotional subscription to the user. This method updates the user’s subscription status, and after this, the ","type":"text"},{"type":"codeVoice","code":"hasActiveSubscription()"},{"text":" method will return ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","navigatorTitle":[{"text":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/restorePurchases(callback:)":{"url":"\/documentation\/apphudsdk\/apphud\/restorepurchases(callback:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/restorePurchases(callback:)","kind":"symbol","title":"restorePurchases(callback:)","role":"symbol","abstract":[{"text":"Implements the ","type":"text"},{"type":"codeVoice","code":"Restore Purchases"},{"type":"text","text":" mechanism. This method sends the current App Store Receipt to Apphud and returns information about the user’s subscriptions and in-app purchases."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"restorePurchases","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (["},{"text":"ApphudSubscription","preciseIdentifier":"s:9ApphudSDK0A12SubscriptionC","kind":"typeIdentifier"},{"kind":"text","text":"]?, ["},{"kind":"typeIdentifier","text":"ApphudNonRenewingPurchase","preciseIdentifier":"s:9ApphudSDK0A19NonRenewingPurchaseC"},{"text":"]?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/start(apiKey:userID:observerMode:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/start(apiKey:userID:observerMode:callback:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Initializes Apphud SDK. Call this during the app’s launch."}],"title":"start(apiKey:userID:observerMode:callback:)","kind":"symbol","url":"\/documentation\/apphudsdk\/apphud\/start(apikey:userid:observermode:callback:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"observerMode"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"text":": ((","kind":"text"},{"text":"ApphudUser","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A4UserV"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ApphudProduct","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphudproduct","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudProduct"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","title":"ApphudProduct","abstract":[{"text":"Apphud’s wrapper around ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"text":".","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/paywall(_:)":{"deprecated":true,"title":"paywall(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paywall","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywall(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paywall:completionHandler:"}],"url":"\/documentation\/apphudsdk\/apphud\/paywall(_:)","abstract":[{"type":"text","text":"Asynchronously retrieve a specific paywall by identifier configured in Product Hub > Paywalls, potentially altered based on the user’s involvement in A\/B testing, if any. Awaits until the inner "},{"code":"SKProduct","type":"codeVoice"},{"type":"text","text":"s are loaded from the App Store."}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/addAttribution(data:from:identifer:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","role":"symbol","type":"topic","abstract":[{"text":"Submits attribution data to Apphud from your chosen attribution network provider.","type":"text"}],"kind":"symbol","title":"addAttribution(data:from:identifer:callback:)","url":"\/documentation\/apphudsdk\/apphud\/addattribution(data:from:identifer:callback:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addAttribution"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"data"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudAttributionProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@E@ApphudAttributionProvider"},{"text":", ","kind":"text"},{"text":"identifer","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"addAttributionWithData:from:identifer:callback:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"purchaseApphudProduct:callback:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"purchaseApphudProduct:callback:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Apphud Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywall(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/paywallShown(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/grantPromotional(daysCount:productId:permissionGroup:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasPremiumAccess()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/hasActiveSubscription()","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/addAttribution(data:from:identifer:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForIntroductoryOffer(product:callback:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/checkEligibilityForPromotionalOffer(product:callback:)"],"generated":true}]},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"purchaseApphudProduct:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","kind":"typeIdentifier","text":"ApphudProduct"},{"text":" *) ","kind":"text"},{"text":"product","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callback:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*$@M@ApphudSDK@objc(cs)ApphudPurchaseResult)","text":"void (^)(ApphudPurchaseResult *)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"callback"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title","value":"ApphudPurchaseResult"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments","value":[{"text":"ApphudPurchaseResult","kind":"identifier"}]},{"op":"replace","value":"hasActiveSubscription","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasActiveSubscription()\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"hasActiveSubscription"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasActiveSubscription()\/fragments"},{"op":"replace","value":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasPremiumAccess()\/title","value":"hasPremiumAccess"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"hasPremiumAccess","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1hasPremiumAccess()\/fragments"},{"value":"purchaseApphudProduct:callback:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchase(_:callback:)-6dhy3\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchase(_:callback:)-6dhy3\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"purchaseApphudProduct:callback:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallShown(_:)\/title","value":"paywallShown:"},{"value":[{"kind":"text","text":"+ "},{"text":"paywallShown:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywallShown(_:)\/fragments"},{"op":"replace","value":"checkEligibilityForIntroductoryOfferWithProduct:callback:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForIntroductoryOffer(product:callback:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForIntroductoryOffer(product:callback:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"checkEligibilityForIntroductoryOfferWithProduct:callback:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1setUserProperty(key:value:setOnce:)\/title","value":"setUserPropertyWithKey:value:setOnce:"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1setUserProperty(key:value:setOnce:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setUserPropertyWithKey:value:setOnce:","kind":"identifier"}]},{"op":"replace","value":"checkEligibilityForPromotionalOfferWithProduct:callback:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForPromotionalOffer(product:callback:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"checkEligibilityForPromotionalOfferWithProduct:callback:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1checkEligibilityForPromotionalOffer(product:callback:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1grantPromotional(daysCount:productId:permissionGroup:callback:)\/title","op":"replace","value":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1grantPromotional(daysCount:productId:permissionGroup:callback:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"grantPromotionalWithDaysCount:productId:permissionGroup:callback:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/title","value":"ApphudProduct"},{"value":[{"kind":"identifier","text":"ApphudProduct"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/fragments","op":"replace"},{"op":"replace","value":"paywall:completionHandler:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywall(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1paywall(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"paywall:completionHandler:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1addAttribution(data:from:identifer:callback:)\/title","op":"replace","value":"addAttributionWithData:from:identifer:callback:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"addAttributionWithData:from:identifer:callback:"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1addAttribution(data:from:identifer:callback:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}