{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:isPurchasing:)-3cisu","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","symbolKind":"method","platforms":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0"},{"deprecated":false,"introducedAt":"15.0","beta":false,"name":"iPadOS","unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"15.0","unavailable":false,"deprecated":false},{"introducedAt":"12.0","deprecated":false,"beta":false,"name":"macOS","unavailable":false},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"15.0"},{"beta":false,"introducedAt":"8.0","name":"watchOS","unavailable":false,"deprecated":false}],"title":"purchase(_:isPurchasing:)","modules":[{"name":"ApphudSDK"}],"externalID":"s:9ApphudSDK0A0C8purchase_12isPurchasingAA0A19AsyncPurchaseResultV8StoreKit7ProductV_7SwiftUI7BindingVySbGSgtYaFZ","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"purchase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Product","kind":"typeIdentifier","preciseIdentifier":"s:8StoreKit7ProductV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isPurchasing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":">?) "},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A19AsyncPurchaseResultV","text":"ApphudAsyncPurchaseResult"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"purchase"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"product","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8StoreKit7ProductV","text":"Product","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isPurchasing"},{"kind":"text","text":": "},{"text":"Binding","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV"},{"text":"<","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":">? = nil) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"text":"ApphudAsyncPurchaseResult","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAsyncPurchaseResult","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A19AsyncPurchaseResultV"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/purchase(_:ispurchasing:)-3cisu"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"url":"\/documentation\/apphudsdk\/apphud","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","title":"Apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/purchase(_:isPurchasing:)-3cisu":{"title":"purchase(_:isPurchasing:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:isPurchasing:)-3cisu","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchase"},{"text":"(","kind":"text"},{"text":"Product","preciseIdentifier":"s:8StoreKit7ProductV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isPurchasing","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":">?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"ApphudAsyncPurchaseResult","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A19AsyncPurchaseResultV"}],"abstract":[],"url":"\/documentation\/apphudsdk\/apphud\/purchase(_:ispurchasing:)-3cisu"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAsyncPurchaseResult":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudAsyncPurchaseResult"}],"navigatorTitle":[{"text":"ApphudAsyncPurchaseResult","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAsyncPurchaseResult","url":"\/documentation\/apphudsdk\/apphudasyncpurchaseresult","kind":"symbol","title":"ApphudAsyncPurchaseResult","abstract":[],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Apphud","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"text":"Apphud","kind":"identifier"}],"op":"replace"},{"value":[{"text":"Apphud","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","op":"replace"}]}]}