{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/purchasepromo(apphudproduct:discountid:_:)"]},{"paths":["\/documentation\/apphudsdk\/apphud\/purchasepromo(apphudproduct:discountid:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"purchasePromoWithApphudProduct:discountID::","kind":"identifier"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"purchasePromo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apphudProduct"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","kind":"typeIdentifier","text":"ApphudProduct"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"discountID"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ((","kind":"text"},{"text":"ApphudPurchaseResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"title":"purchasePromo(apphudProduct:discountID:_:)","modules":[{"name":"ApphudSDK"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)purchasePromoWithApphudProduct:discountID::"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchasePromo(apphudProduct:discountID:_:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"purchasePromo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apphudProduct"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct"},{"text":", ","kind":"text"},{"text":"discountID","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"callback","kind":"internalParam"},{"kind":"text","text":": (("},{"text":"ApphudPurchaseResult","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"apphudProduct","content":[{"inlineContent":[{"type":"text","text":"Required. An "},{"type":"codeVoice","code":"ApphudProduct"},{"type":"text","text":" object representing the subscription to be purchased."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Required. The identifier of the ","type":"text"},{"type":"codeVoice","code":"SKProductDiscount"},{"text":" to be applied to the purchase.","type":"text"}]}],"name":"discountID"},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"text":"Optional. Returns an ","type":"text"},{"type":"codeVoice","code":"ApphudPurchaseResult"},{"text":" object upon completion.","type":"text"}]}]}]},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method automatically sends the in-app purchase receipt to Apphud."}]}],"style":"note","name":"Note"}],"kind":"content"}],"abstract":[{"type":"text","text":"Purchases a subscription with a promotional offer and automatically submits the App Store Receipt to Apphud."}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/purchasePromo(apphudProduct:discountID:_:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchasePromo(apphudProduct:discountID:_:)","url":"\/documentation\/apphudsdk\/apphud\/purchasepromo(apphudproduct:discountid:_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"purchasePromo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apphudProduct"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"discountID","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", (("},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","text":"ApphudPurchaseResult","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Purchases a subscription with a promotional offer and automatically submits the App Store Receipt to Apphud."}],"kind":"symbol","type":"topic","title":"purchasePromo(apphudProduct:discountID:_:)","navigatorTitle":[{"text":"purchasePromoWithApphudProduct:discountID::","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"type":"topic","url":"\/documentation\/apphudsdk\/apphudpurchaseresult","abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"title":"ApphudPurchaseResult","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPurchaseResult"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","navigatorTitle":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct":{"navigatorTitle":[{"kind":"identifier","text":"ApphudProduct"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","type":"topic","url":"\/documentation\/apphudsdk\/apphudproduct","kind":"symbol","abstract":[{"type":"text","text":"Apphud’s wrapper around "},{"code":"SKProduct","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudProduct"}],"role":"symbol","title":"ApphudProduct"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"purchasePromoWithApphudProduct:discountID::"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"purchasePromoWithApphudProduct:discountID::"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"purchasePromoWithApphudProduct:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","text":"ApphudProduct","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"apphudProduct","kind":"internalParam"},{"kind":"text","text":" "},{"text":"discountID:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"discountID","kind":"internalParam"},{"text":" ","kind":"text"},{"text":":","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(ApphudPurchaseResult *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@ApphudSDK@objc(cs)ApphudPurchaseResult)"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchasePromo(apphudProduct:discountID:_:)\/title","value":"purchasePromoWithApphudProduct:discountID::"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchasePromo(apphudProduct:discountID:_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"purchasePromoWithApphudProduct:discountID::"}],"op":"replace"},{"value":"ApphudPurchaseResult","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments","value":[{"kind":"identifier","text":"ApphudPurchaseResult"}]},{"op":"replace","value":"ApphudProduct","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/title"},{"value":[{"kind":"identifier","text":"ApphudProduct"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","op":"replace","value":[{"kind":"identifier","text":"Apphud"}]}]}]}