{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchasePromo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"product"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"discountID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","text":"ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"product","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Required. This is an "},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":" object that user wants to purchase."}]}]},{"name":"discountID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Required. This is a "},{"type":"codeVoice","code":"SKProductDiscount"},{"type":"text","text":" Identifier String object that you would like to apply."}]}]},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. Returns "},{"type":"codeVoice","code":"ApphudPurchaseResult"},{"type":"text","text":" object."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method automatically sends in-app purchase receipt to Apphud, so you don’t need to call "},{"type":"codeVoice","code":"submitReceipt"},{"type":"text","text":" method."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/purchasepromo(_:discountid:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/purchasepromo(_:discountid:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchasePromo(_:discountID:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Purchases subscription (promotional) offer and automatically submits App Store Receipt to Apphud."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchasePromo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"discountID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", (("},{"kind":"typeIdentifier","text":"ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"purchasePromo(_:discountID:_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)purchasePromo:discountID::","modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"purchasePromo:discountID::"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"role":"symbol","title":"ApphudPurchaseResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPurchaseResult"}],"abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"role":"symbol","title":"Apphud","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/purchasePromo(_:discountID:_:)":{"role":"symbol","title":"purchasePromo(_:discountID:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchasePromo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"discountID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", (("},{"kind":"typeIdentifier","text":"ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Purchases subscription (promotional) offer and automatically submits App Store Receipt to Apphud."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchasePromo(_:discountID:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"purchasePromo:discountID::"}],"url":"\/documentation\/apphudsdk\/apphud\/purchasepromo(_:discountid:_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"purchasePromo:discountID::"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"purchasePromo:discountID::"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"purchasePromo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"product"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"discountID"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(ApphudPurchaseResult *)","preciseIdentifier":"c:BFv(#*$@M@ApphudSDK@objc(cs)ApphudPurchaseResult)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title","value":"ApphudPurchaseResult"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments","value":[{"kind":"identifier","text":"ApphudPurchaseResult"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"kind":"identifier","text":"Apphud"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchasePromo(_:discountID:_:)\/title","value":"purchasePromo:discountID::"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchasePromo(_:discountID:_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"purchasePromo:discountID::"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}