{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:value:callback:)"},"abstract":[{"type":"text","text":"Experimental purchase method allowing the passing of a custom value for purchases. This custom value is sent to AppsFlyer and Facebook for value optimization, such as subscription Lifetime Value (LTV) or Average Revenue Per Paying User (ARPPU), in USD."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":"(purchaseApphudProduct:value:callback:) ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"purchase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"product","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","kind":"typeIdentifier","text":"ApphudPurchaseResult","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"product","content":[{"type":"paragraph","inlineContent":[{"text":"Required. An ","type":"text"},{"type":"codeVoice","code":"ApphudProduct"},{"type":"text","text":" object for the purchase."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Required. The custom value in USD to be sent for analytics."}],"type":"paragraph"}],"name":"value"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. Returns an "},{"type":"codeVoice","code":"ApphudPurchaseResult"},{"type":"text","text":" object."}]}],"name":"callback"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"aside","name":"Note","content":[{"inlineContent":[{"text":"Contact your support manager for detailed guidance on using this method.","type":"text"}],"type":"paragraph"}],"style":"note"}]}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/purchase(_:value:callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/purchase(_:value:callback:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"metadata":{"title":"purchase(_:value:callback:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchase"},{"text":"(","kind":"text"},{"text":"ApphudProduct","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)purchaseApphudProduct:value:callback:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"purchaseApphudProduct:value:callback:"}],"symbolKind":"method","modules":[{"name":"ApphudSDK"}],"roleHeading":"Type Method"},"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/purchase(_:value:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:value:callback:)","url":"\/documentation\/apphudsdk\/apphud\/purchase(_:value:callback:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchase"},{"text":"(","kind":"text"},{"text":"ApphudProduct","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct"},{"text":", ","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"ApphudPurchaseResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","abstract":[{"text":"Experimental purchase method allowing the passing of a custom value for purchases. This custom value is sent to AppsFlyer and Facebook for value optimization, such as subscription Lifetime Value (LTV) or Average Revenue Per Paying User (ARPPU), in USD.","type":"text"}],"kind":"symbol","type":"topic","title":"purchase(_:value:callback:)","navigatorTitle":[{"text":"purchaseApphudProduct:value:callback:","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"type":"topic","url":"\/documentation\/apphudsdk\/apphudpurchaseresult","abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"title":"ApphudPurchaseResult","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPurchaseResult"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","navigatorTitle":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct":{"navigatorTitle":[{"kind":"identifier","text":"ApphudProduct"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","type":"topic","url":"\/documentation\/apphudsdk\/apphudproduct","kind":"symbol","abstract":[{"type":"text","text":"Apphud’s wrapper around "},{"code":"SKProduct","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudProduct"}],"role":"symbol","title":"ApphudProduct"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"purchaseApphudProduct:value:callback:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"purchaseApphudProduct:value:callback:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"purchaseApphudProduct:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","text":"ApphudProduct","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"product"},{"text":" ","kind":"text"},{"text":"value:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"value","kind":"internalParam"},{"kind":"text","text":" "},{"text":"callback:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@ApphudSDK@objc(cs)ApphudPurchaseResult)","text":"void (^)(ApphudPurchaseResult *)"},{"kind":"text","text":") "},{"text":"callback","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"purchaseApphudProduct:value:callback:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchase(_:value:callback:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1purchase(_:value:callback:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"purchaseApphudProduct:value:callback:","kind":"identifier"}],"op":"replace"},{"value":"ApphudPurchaseResult","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments","value":[{"text":"ApphudPurchaseResult","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/title","value":"ApphudProduct"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/fragments","value":[{"kind":"identifier","text":"ApphudProduct"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","op":"replace","value":"Apphud"},{"value":[{"text":"Apphud","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments"}]}]}