{"abstract":[{"text":"Initiates an asynchronous purchase of an ","type":"text"},{"code":"ApphudProduct","type":"codeVoice"},{"text":" object from an ","type":"text"},{"code":"ApphudPaywall","type":"codeVoice"},{"text":" and automatically submits the App Store Receipt to Apphud.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:isPurchasing:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/purchase(_:ispurchasing:)"]}],"metadata":{"symbolKind":"method","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","beta":false},{"introducedAt":"13.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.0"},{"beta":false,"introducedAt":"11.0","deprecated":false,"name":"macOS","unavailable":false},{"beta":false,"unavailable":false,"deprecated":false,"introducedAt":"13.0","name":"tvOS"},{"beta":false,"introducedAt":"6.0","deprecated":false,"name":"watchOS","unavailable":false}],"modules":[{"name":"ApphudSDK"}],"externalID":"s:9ApphudSDK0A0C8purchase_12isPurchasingAA0A14PurchaseResultCAA0A7ProductC_7SwiftUI7BindingVySbGSgtYaFZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"purchase"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","kind":"typeIdentifier","text":"ApphudProduct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isPurchasing"},{"text":": ","kind":"text"},{"text":"Binding","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV"},{"text":"<","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":">?) "},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","kind":"typeIdentifier","text":"ApphudPurchaseResult"}],"role":"symbol","roleHeading":"Type Method","title":"purchase(_:isPurchasing:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"purchase"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"product","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"ApphudProduct","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"isPurchasing","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":">? = nil) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","text":"ApphudPurchaseResult","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"name":"product","content":[{"inlineContent":[{"type":"text","text":"Required. An "},{"type":"codeVoice","code":"ApphudProduct"},{"type":"text","text":" object from your "},{"type":"codeVoice","code":"ApphudPaywall"},{"type":"text","text":". Configure placements and paywalls in Apphud Dashboard > Mission control before using."}],"type":"paragraph"}]},{"name":"isPurchasing","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. A binding to a Boolean value indicating the purchase process status. Useful in SwiftUI."}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"ApphudPurchaseResult"},{"type":"text","text":" object."}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct":{"title":"ApphudProduct","navigatorTitle":[{"kind":"identifier","text":"ApphudProduct"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudProduct"}],"kind":"symbol","url":"\/documentation\/apphudsdk\/apphudproduct","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","type":"topic","abstract":[{"type":"text","text":"Apphud’s wrapper around "},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"."}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","navigatorTitle":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult","kind":"symbol","abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"title":"ApphudPurchaseResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPurchaseResult"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/purchase(_:isPurchasing:)":{"role":"symbol","title":"purchase(_:isPurchasing:)","url":"\/documentation\/apphudsdk\/apphud\/purchase(_:ispurchasing:)","abstract":[{"type":"text","text":"Initiates an asynchronous purchase of an "},{"type":"codeVoice","code":"ApphudProduct"},{"text":" object from an ","type":"text"},{"type":"codeVoice","code":"ApphudPaywall"},{"type":"text","text":" and automatically submits the App Store Receipt to Apphud."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchase"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","kind":"typeIdentifier","text":"ApphudProduct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isPurchasing"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":">?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","text":"ApphudPurchaseResult","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/purchase(_:isPurchasing:)","kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud","title":"Apphud","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/title","value":"ApphudProduct","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/fragments","value":[{"text":"ApphudProduct","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/navigatorTitle","op":"replace","value":[{"text":"ApphudProduct","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title","value":"ApphudPurchaseResult"},{"value":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/navigatorTitle","value":[{"text":"ApphudPurchaseResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"kind":"identifier","text":"Apphud"}]},{"value":[{"kind":"identifier","text":"Apphud"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}