{"abstract":[{"type":"text","text":"A list of paywalls, potentially altered based on the user’s involvement in A\/B testing, if any."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rawPaywalls","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"ApphudPaywall","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"kind":"text","text":"]"}]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"type":"codeVoice","code":"ApphudPaywall"},{"text":" objects, representing the configured paywalls.","type":"text"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This function doesn’t await until inner "},{"type":"codeVoice","code":"SKProduct"},{"text":"s are loaded from the App Store. That means paywalls may or may not have inner StoreKit products at the time you call this function.","type":"text"}]}],"style":"important","type":"aside","name":"Important"},{"type":"aside","style":"important","content":[{"inlineContent":[{"type":"text","text":"This function will return empty array if user is not yet loaded, or placements are not set up in the Product Hub."}],"type":"paragraph"}],"name":"Important"},{"inlineContent":[{"type":"text","text":"To get paywalls with awaiting for StoreKit products, use await Apphud.paywalls() or"},{"type":"text","text":" "},{"type":"text","text":"Apphud.paywallsDidLoadCallback(…) functions."}],"type":"paragraph"}]}],"metadata":{"symbolKind":"method","roleHeading":"Type Method","title":"rawPaywalls()","externalID":"s:9ApphudSDK0A0C11rawPaywallsSayAA0A7PaywallCGyFZ","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rawPaywalls","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"kind":"text","text":"]"}],"modules":[{"name":"ApphudSDK"}],"role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/rawPaywalls()","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/rawpaywalls()"]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","title":"ApphudPaywall","abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudPaywall","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/apphudsdk\/apphudpaywall","navigatorTitle":[{"text":"ApphudPaywall","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/rawPaywalls()":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/rawPaywalls()","type":"topic","title":"rawPaywalls()","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rawPaywalls","kind":"identifier"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier","text":"ApphudPaywall"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A list of paywalls, potentially altered based on the user’s involvement in A\/B testing, if any."}],"url":"\/documentation\/apphudsdk\/apphud\/rawpaywalls()","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"type":"topic","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud","abstract":[{"text":"Entry point of the Apphud SDK. It provides access to all its features.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Apphud"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","url":"\/documentation\/apphudsdk","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"title":"ApphudSDK","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ApphudPaywall","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","value":[{"kind":"identifier","text":"ApphudPaywall"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"kind":"identifier","text":"Apphud"}],"op":"replace"}]}]}