{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshStoreKitProducts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Best practise is not to use this method, but implement paywalls logic by adding your paywall configuration in Apphud Dashboard > Product Hub > Paywalls."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You shouldn’t call this method at app launch, because Apphud SDK automatically fetches products during initialization. Only use this method as a fallback."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/refreshstorekitproducts(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/refreshstorekitproducts(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/refreshStoreKitProducts(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Refreshes "},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"s from the App Store. You have to add all product identifiers in Apphud Dashboard > Product Hub > Products."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"refreshStoreKitProducts:"}],"role":"symbol","title":"refreshStoreKitProducts(_:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshStoreKitProducts"},{"kind":"text","text":"(((["},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)refreshStoreKitProducts:","modules":[{"name":"ApphudSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.2","deprecated":false},{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.14.4","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/refreshStoreKitProducts(_:)":{"role":"symbol","title":"refreshStoreKitProducts(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshStoreKitProducts"},{"kind":"text","text":"(((["},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Refreshes "},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"s from the App Store. You have to add all product identifiers in Apphud Dashboard > Product Hub > Products."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/refreshStoreKitProducts(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshStoreKitProducts:"}],"url":"\/documentation\/apphudsdk\/apphud\/refreshstorekitproducts(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[{"type":"text","text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"role":"symbol","title":"Apphud","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"url":"\/documentation\/apphudsdk\/apphud"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"refreshStoreKitProducts:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"refreshStoreKitProducts:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"refreshStoreKitProducts:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<SKProduct *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1refreshStoreKitProducts(_:)\/title","value":"refreshStoreKitProducts:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1refreshStoreKitProducts(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"refreshStoreKitProducts:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"kind":"identifier","text":"Apphud"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}