{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"abstract":[{"text":"Refreshes current user data including paywalls, placements, subscriptions, non-renewing purchases, and promotionals.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/refreshUserData(callback:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"refreshUserData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A4UserV","kind":"typeIdentifier","text":"ApphudUser"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"roleHeading":"Type Method","role":"symbol","title":"refreshUserData(callback:)","externalID":"s:9ApphudSDK0A0C15refreshUserData8callbackyyAA0aD0VSgc_tFZ","symbolKind":"method","modules":[{"name":"ApphudSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/refreshuserdata(callback:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"refreshUserData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUser","preciseIdentifier":"s:9ApphudSDK0A4UserV","text":"ApphudUser","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":"))","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"callback","content":[{"inlineContent":[{"type":"text","text":"A closure that gets called with the updated "},{"type":"codeVoice","code":"ApphudUser"},{"text":" object. The user object may be nil","type":"text"},{"type":"text","text":" "},{"type":"text","text":"if the refresh operation fails."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method triggers a refresh of all user-related data from Apphud servers. You can use this method to manually"},{"type":"text","text":" "},{"type":"text","text":"update the user’s data when needed, such as when the app returns from background."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To receive notifications about data updates, implement the following "},{"type":"codeVoice","code":"ApphudListener"},{"text":" methods:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"code":"apphudSubscriptionsUpdated","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"apphudNonRenewingPurchasesUpdated"}]}]}],"type":"unorderedList"},{"type":"aside","name":"Important","style":"important","content":[{"inlineContent":[{"type":"text","text":"Do not call this method on app launch as Apphud SDK automatically refreshes user data during initialization."}],"type":"paragraph"}]},{"type":"paragraph","inlineContent":[{"text":"Example usage:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["Apphud.refreshUserData { user in","    if let user = user {","        \/\/ Handle updated user data","    }","}"]}]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"url":"\/documentation\/apphudsdk\/apphud","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","title":"Apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUser":{"title":"ApphudUser","url":"\/documentation\/apphudsdk\/apphuduser","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUser","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ApphudUser","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ApphudUser","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/refreshUserData(callback:)":{"kind":"symbol","abstract":[{"text":"Refreshes current user data including paywalls, placements, subscriptions, non-renewing purchases, and promotionals.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refreshUserData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A4UserV","kind":"typeIdentifier","text":"ApphudUser"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/refreshUserData(callback:)","title":"refreshUserData(callback:)","url":"\/documentation\/apphudsdk\/apphud\/refreshuserdata(callback:)","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","op":"replace","value":"Apphud"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"kind":"identifier","text":"Apphud"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","value":[{"kind":"identifier","text":"Apphud"}]}]}]}