{"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setAttribution(data:from:identifer:callback:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"metadata":{"modules":[{"name":"ApphudSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setAttribution"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9ApphudSDK0A15AttributionDataV","kind":"typeIdentifier","text":"ApphudAttributionData"},{"kind":"text","text":"?, "},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ApphudSDK@E@ApphudAttributionProvider","text":"ApphudAttributionProvider","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"identifer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","text":"ApphudBoolCallback","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"role":"symbol","roleHeading":"Type Method","title":"setAttribution(data:from:identifer:callback:)","externalID":"s:9ApphudSDK0A0C14setAttribution4data4from9identifer8callbackyAA0aD4DataVSg_AA0aD8ProviderOSSSgySbcSgtFZ","symbolKind":"method"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setAttribution","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionData","kind":"typeIdentifier","text":"ApphudAttributionData","preciseIdentifier":"s:9ApphudSDK0A15AttributionDataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"provider"},{"text":": ","kind":"text"},{"text":"ApphudAttributionProvider","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider","preciseIdentifier":"c:@M@ApphudSDK@E@ApphudAttributionProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"identifer"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"text":"ApphudBoolCallback","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]}]},{"kind":"parameters","parameters":[{"name":"data","content":[{"inlineContent":[{"type":"text","text":"Optional. The ApphudAttributionData model. Pass nil for some integrations such as Apple Search Ads, Firebase."}],"type":"paragraph"}]},{"name":"provider","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Required. The name of the attribution provider."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. A closure that returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the data was successfully sent to Apphud."}]}],"name":"callback"}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":"Properly setting up attribution data is key for tracking and optimizing user acquisition strategies and measuring the ROI of marketing campaigns."}],"type":"paragraph"}],"type":"aside"}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Submits attribution data to Apphud"}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/setattribution(data:from:identifer:callback:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionData":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionData","type":"topic","abstract":[],"url":"\/documentation\/apphudsdk\/apphudattributiondata","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ApphudAttributionData","kind":"identifier"}],"title":"ApphudAttributionData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ApphudAttributionData","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider":{"abstract":[{"text":"List of available attribution providers","type":"text"},{"type":"text","text":" "},{"type":"text","text":"has to make Int in order to support Objective-C"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider","url":"\/documentation\/apphudsdk\/apphudattributionprovider","title":"ApphudAttributionProvider","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudAttributionProvider"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProvider"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"url":"\/documentation\/apphudsdk\/apphud","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","title":"Apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudBoolCallback":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback","kind":"symbol","title":"ApphudBoolCallback","abstract":[{"text":"Public Callback object provide -> Bool","type":"text"}],"navigatorTitle":[{"text":"ApphudBoolCallback","kind":"identifier"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphudboolcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudBoolCallback"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/setAttribution(data:from:identifer:callback:)":{"title":"setAttribution(data:from:identifer:callback:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setAttribution(data:from:identifer:callback:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setAttribution","kind":"identifier"},{"kind":"text","text":"("},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudAttributionData","preciseIdentifier":"s:9ApphudSDK0A15AttributionDataV"},{"text":"?, ","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ApphudAttributionProvider","preciseIdentifier":"c:@M@ApphudSDK@E@ApphudAttributionProvider","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"identifer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudBoolCallback","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Submits attribution data to Apphud"}],"url":"\/documentation\/apphudsdk\/apphud\/setattribution(data:from:identifer:callback:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ApphudAttributionProvider","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/fragments","op":"replace","value":[{"text":"ApphudAttributionProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/navigatorTitle","op":"replace","value":[{"text":"ApphudAttributionProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"text":"Apphud","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","value":[{"kind":"identifier","text":"Apphud"}],"op":"replace"}]}]}