{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPaywallsCacheTimeout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"New value in seconds. Must be between 0 and 172800 (48 hours)."}],"type":"paragraph"}],"name":"value"}],"kind":"parameters"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Must call before SDK initialization.","type":"text"}]}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setPaywallsCacheTimeout(_:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"ApphudSDK"}],"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)setPaywallsCacheTimeout:","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPaywallsCacheTimeout","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"title":"setPaywallsCacheTimeout(_:)","role":"symbol","navigatorTitle":[{"text":"setPaywallsCacheTimeout:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"abstract":[{"type":"text","text":"Override default paywalls and placements cache timeout value. Default cache value is 9000 seconds (25 hours)."},{"text":" ","type":"text"},{"text":"If expired, will make SDK to disregard cache and force refresh paywalls and placements.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Call it only if keeping paywalls and placements up to date is critical for your app business."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/setpaywallscachetimeout(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/setpaywallscachetimeout(_:)"]}],"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","role":"collection","url":"\/documentation\/apphudsdk","abstract":[{"type":"text","text":"Apphud is an all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams make the right decisions based on data and tools."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/setPaywallsCacheTimeout(_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPaywallsCacheTimeout","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setPaywallsCacheTimeout:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setPaywallsCacheTimeout(_:)","role":"symbol","url":"\/documentation\/apphudsdk\/apphud\/setpaywallscachetimeout(_:)","type":"topic","abstract":[{"type":"text","text":"Override default paywalls and placements cache timeout value. Default cache value is 9000 seconds (25 hours)."},{"text":" ","type":"text"},{"type":"text","text":"If expired, will make SDK to disregard cache and force refresh paywalls and placements."},{"type":"text","text":" "},{"text":"Call it only if keeping paywalls and placements up to date is critical for your app business.","type":"text"}],"title":"setPaywallsCacheTimeout(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"kind":"symbol","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"abstract":[{"text":"Entry point of the Apphud SDK. It provides access to all its features.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"setPaywallsCacheTimeout:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"setPaywallsCacheTimeout:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setPaywallsCacheTimeout:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"New value in seconds. Must be between 0 and 172800 (48 hours)."}],"type":"paragraph"}],"name":"value"}]},"op":"replace"},{"op":"replace","value":"setPaywallsCacheTimeout:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1setPaywallsCacheTimeout(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1setPaywallsCacheTimeout(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setPaywallsCacheTimeout:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"kind":"identifier","text":"Apphud"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","value":[{"text":"Apphud","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}