{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setUserProperty","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","text":"ApphudUserPropertyKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"},{"kind":"text","text":", "},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?, "},{"text":"setOnce","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = false)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Example:","type":"text"}]},{"syntax":"swift","code":["Apphud.setUserProperty(key: .init(\"custom_prop_1\"), value: 0.5)"],"type":"codeListing"},{"inlineContent":[{"text":"There are several built-in keys provided by Apphud, each expecting a specific value type:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":".email"},{"text":": The user’s email. The value must be a ","type":"text"},{"type":"codeVoice","code":"String"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".name"},{"type":"text","text":": The user’s name. The value must be a "},{"type":"codeVoice","code":"String"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":".phone"},{"type":"text","text":": The user’s phone number. The value must be a "},{"code":"String","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":".age","type":"codeVoice"},{"text":": The user’s age. The value must be an ","type":"text"},{"type":"codeVoice","code":"Int"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":".gender"},{"text":": The user’s gender. The value must be a ","type":"text"},{"type":"codeVoice","code":"String"},{"type":"text","text":", with accepted values being “male”, “female”, or “other”."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":".cohort"},{"text":": The cohort the user belongs to, typically indicating when they installed the app. The value must be a ","type":"text"},{"code":"String","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameters:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"key"},{"text":": Required. This can be initialized with a custom ","type":"text"},{"type":"codeVoice","code":"String"},{"type":"text","text":" or by using one of the built-in keys provided by Apphud."}]}]},{"content":[{"inlineContent":[{"code":"value","type":"codeVoice"},{"type":"text","text":": Required\/Optional. The value to be set for the specified key. Pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" or "},{"code":"NSNull","type":"codeVoice"},{"text":" to remove the property from Apphud.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"setOnce","type":"codeVoice"},{"text":": Optional. A Boolean value where passing ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" will make the property non-updatable, meaning it can only be set once."}],"type":"paragraph"}]}]},{"inlineContent":[{"type":"text","text":"Note: Custom user properties are useful for segmenting your user base within Apphud for targeted analysis or marketing efforts. Ensure the values you set are accurate and relevant to your app’s functionality and user experience."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/setuserproperty(key:value:setonce:)"]},{"paths":["\/documentation\/apphudsdk\/apphud\/setuserproperty(key:value:setonce:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"metadata":{"modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"text":"setUserPropertyWithKey:value:setOnce:","kind":"identifier"}],"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)setUserPropertyWithKey:value:setOnce:","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setUserProperty","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ApphudUserPropertyKey","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"},{"kind":"text","text":", "},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?, "},{"text":"setOnce","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"roleHeading":"Type Method","role":"symbol","title":"setUserProperty(key:value:setOnce:)"},"abstract":[{"text":"Sets a custom user property in Apphud. The value assigned to this property must be of one of the following types: ","type":"text"},{"code":"Int","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"Float"},{"type":"text","text":", "},{"type":"codeVoice","code":"Double"},{"type":"text","text":", "},{"type":"codeVoice","code":"Bool"},{"type":"text","text":", "},{"code":"String","type":"codeVoice"},{"type":"text","text":", "},{"code":"NSNumber","type":"codeVoice"},{"text":", ","type":"text"},{"code":"NSString","type":"codeVoice"},{"type":"text","text":", "},{"code":"NSNull","type":"codeVoice"},{"text":", or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey":{"abstract":[{"type":"text","text":"User property initializer class with reserved property names."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudUserPropertyKey"}],"title":"ApphudUserPropertyKey","url":"\/documentation\/apphudsdk\/apphuduserpropertykey","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","navigatorTitle":[{"text":"ApphudUserPropertyKey","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"url":"\/documentation\/apphudsdk\/apphud","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","title":"Apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/setUserProperty(key:value:setOnce:)":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setUserProperty","kind":"identifier"},{"kind":"text","text":"("},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudUserPropertyKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"},{"kind":"text","text":", "},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?, ","kind":"text"},{"text":"setOnce","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/setUserProperty(key:value:setOnce:)","role":"symbol","title":"setUserProperty(key:value:setOnce:)","abstract":[{"type":"text","text":"Sets a custom user property in Apphud. The value assigned to this property must be of one of the following types: "},{"type":"codeVoice","code":"Int"},{"text":", ","type":"text"},{"type":"codeVoice","code":"Float"},{"text":", ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"Bool"},{"type":"text","text":", "},{"type":"codeVoice","code":"String"},{"type":"text","text":", "},{"type":"codeVoice","code":"NSNumber"},{"text":", ","type":"text"},{"type":"codeVoice","code":"NSString"},{"text":", ","type":"text"},{"code":"NSNull","type":"codeVoice"},{"type":"text","text":", or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"url":"\/documentation\/apphudsdk\/apphud\/setuserproperty(key:value:setonce:)","navigatorTitle":[{"kind":"identifier","text":"setUserPropertyWithKey:value:setOnce:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"setUserPropertyWithKey:value:setOnce:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setUserPropertyWithKey:value:setOnce:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"setUserPropertyWithKey:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","text":"ApphudUserPropertyKey","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"text":"value:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"value"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setOnce:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"setOnce","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/title","value":"ApphudUserPropertyKey"},{"value":[{"kind":"identifier","text":"ApphudUserPropertyKey"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/navigatorTitle","value":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud","op":"replace"},{"value":[{"text":"Apphud","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","op":"replace","value":[{"text":"Apphud","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1setUserProperty(key:value:setOnce:)\/title","value":"setUserPropertyWithKey:value:setOnce:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1setUserProperty(key:value:setOnce:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setUserPropertyWithKey:value:setOnce:"}],"op":"replace"}]}]}