{"variants":[{"paths":["\/documentation\/apphudsdk\/apphud\/submitpushnotificationstokenstring(string:callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphud\/submitpushnotificationstokenstring(string:callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submitPushNotificationsTokenString","kind":"identifier"},{"kind":"text","text":"("},{"text":"string","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"text":"ApphudBoolCallback","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The push token as a String object."}]}],"name":"token"},{"content":[{"inlineContent":[{"text":"An optional closure that returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the token was successfully sent to Apphud.","type":"text"}],"type":"paragraph"}],"name":"callback"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this method if your push token is already converted into a String format. Ensure the token is accurate for successful submission."}]}],"name":"Note","type":"aside","style":"note"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/submitPushNotificationsTokenString(string:callback:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Submits the device’s push token to Apphud as a String. This method provides an alternative way to submit the token if you have it in a string format."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"submitPushNotificationsTokenStringWithString:callback:","kind":"identifier"}],"title":"submitPushNotificationsTokenString(string:callback:)","externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)submitPushNotificationsTokenStringWithString:callback:","roleHeading":"Type Method","modules":[{"name":"ApphudSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"submitPushNotificationsTokenString"},{"text":"(","kind":"text"},{"text":"string","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudBoolCallback","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"text":"?)","kind":"text"}],"role":"symbol"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudBoolCallback":{"kind":"symbol","title":"ApphudBoolCallback","url":"\/documentation\/apphudsdk\/apphudboolcallback","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback","abstract":[{"text":"Public Callback object provide -> Bool","type":"text"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudBoolCallback"}],"navigatorTitle":[{"text":"ApphudBoolCallback","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","url":"\/documentation\/apphudsdk","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"title":"ApphudSDK","type":"topic","role":"collection","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/submitPushNotificationsTokenString(string:callback:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/submitPushNotificationsTokenString(string:callback:)","url":"\/documentation\/apphudsdk\/apphud\/submitpushnotificationstokenstring(string:callback:)","kind":"symbol","navigatorTitle":[{"text":"submitPushNotificationsTokenStringWithString:callback:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Submits the device’s push token to Apphud as a String. This method provides an alternative way to submit the token if you have it in a string format.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"submitPushNotificationsTokenString"},{"text":"(","kind":"text"},{"text":"string","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","text":"ApphudBoolCallback","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","title":"submitPushNotificationsTokenString(string:callback:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"type":"topic","url":"\/documentation\/apphudsdk\/apphud","title":"Apphud","abstract":[{"text":"Entry point of the Apphud SDK. It provides access to all its features.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Apphud"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Apphud"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"submitPushNotificationsTokenStringWithString:callback:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"submitPushNotificationsTokenStringWithString:callback:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"submitPushNotificationsTokenStringWithString:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"string","kind":"internalParam"},{"kind":"text","text":" "},{"text":"callback:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(_Bool)","preciseIdentifier":"c:BFv(#b)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"submitPushNotificationsTokenStringWithString:callback:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1submitPushNotificationsTokenString(string:callback:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"submitPushNotificationsTokenStringWithString:callback:"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1submitPushNotificationsTokenString(string:callback:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title","value":"Apphud"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments","value":[{"text":"Apphud","kind":"identifier"}]}]}]}