{"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/submitPushNotificationsToken(token:callback:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Submits the device’s push token to Apphud. This is essential for enabling Apphud to send push notifications to the device.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/submitpushnotificationstoken(token:callback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/submitpushnotificationstoken(token:callback:)"]}],"kind":"symbol","metadata":{"symbolKind":"method","navigatorTitle":[{"text":"submitPushNotificationsTokenWithToken:callback:","kind":"identifier"}],"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)submitPushNotificationsTokenWithToken:callback:","modules":[{"name":"ApphudSDK"}],"title":"submitPushNotificationsToken(token:callback:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submitPushNotificationsToken","kind":"identifier"},{"kind":"text","text":"("},{"text":"token","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"text":"ApphudBoolCallback","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka"},{"text":"?)","kind":"text"}],"roleHeading":"Type Method","role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submitPushNotificationsToken","kind":"identifier"},{"kind":"text","text":"("},{"text":"token","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback","preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","kind":"typeIdentifier","text":"ApphudBoolCallback"},{"kind":"text","text":"?)"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"token","content":[{"inlineContent":[{"text":"The push token, provided as a Data object.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional closure that returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the token was successfully sent to Apphud."}]}],"name":"callback"}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Ensure that the push token is obtained correctly from your app’s notification setup process before submitting it to Apphud.","type":"text"}]}],"style":"note"}]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/submitPushNotificationsToken(token:callback:)":{"url":"\/documentation\/apphudsdk\/apphud\/submitpushnotificationstoken(token:callback:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/submitPushNotificationsToken(token:callback:)","navigatorTitle":[{"kind":"identifier","text":"submitPushNotificationsTokenWithToken:callback:"}],"kind":"symbol","type":"topic","title":"submitPushNotificationsToken(token:callback:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitPushNotificationsToken"},{"kind":"text","text":"("},{"text":"token","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A12BoolCallbacka","text":"ApphudBoolCallback","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Submits the device’s push token to Apphud. This is essential for enabling Apphud to send push notifications to the device.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","kind":"symbol","title":"Apphud","url":"\/documentation\/apphudsdk\/apphud","type":"topic","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Apphud","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudBoolCallback":{"navigatorTitle":[{"kind":"identifier","text":"ApphudBoolCallback"}],"url":"\/documentation\/apphudsdk\/apphudboolcallback","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Public Callback object provide -> Bool","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudBoolCallback","title":"ApphudBoolCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ApphudBoolCallback","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"submitPushNotificationsTokenWithToken:callback:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"submitPushNotificationsTokenWithToken:callback:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"submitPushNotificationsTokenWithToken:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"text":"token","kind":"internalParam"},{"kind":"text","text":" "},{"text":"callback:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(_Bool)","preciseIdentifier":"c:BFv(#b)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1submitPushNotificationsToken(token:callback:)\/title","value":"submitPushNotificationsTokenWithToken:callback:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"submitPushNotificationsTokenWithToken:callback:"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1submitPushNotificationsToken(token:callback:)\/fragments"},{"op":"replace","value":"Apphud","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title"},{"value":[{"text":"Apphud","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}