{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willPurchaseProductFrom"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"paywallIdentifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placementIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"paywallIdentifier","content":[{"inlineContent":[{"text":"Required. The Paywall ID from Apphud Product Hub > Paywalls.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional. The Placement ID from Apphud Product Hub > Placements if using placements; otherwise, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}],"name":"placementIdentifier"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"aside","name":"Important","style":"important","content":[{"type":"paragraph","inlineContent":[{"text":"Observer mode only. Call this method immediately before your custom purchase method.","type":"text"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example usage:"}]},{"syntax":"swift","type":"codeListing","code":["Apphud.willPurchaseProductFrom(paywallIdentifier: \"main_paywall\", placementIdentifier: \"some_placement\")","YourClass.purchase(someProduct)"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ApphudSDK@objc(cs)Apphud(cm)willPurchaseProductFromPaywallIdentifier:placementIdentifier:","symbolKind":"method","role":"symbol","title":"willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPurchaseProductFrom"},{"text":"(","kind":"text"},{"text":"paywallIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"placementIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:"}],"modules":[{"name":"ApphudSDK"}],"roleHeading":"Type Method"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphud\/willpurchaseproductfrom(paywallidentifier:placementidentifier:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphud\/willpurchaseproductfrom(paywallidentifier:placementidentifier:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)"},"sections":[],"abstract":[{"text":"Notifies Apphud when a purchase process is initiated from a paywall in ","type":"text"},{"type":"codeVoice","code":"Observer Mode"},{"type":"text","text":", enabling the use of A\/B experiments. This method should be called right before executing your own purchase method, and it’s specifically required only when the SDK is in Observer Mode."}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)":{"abstract":[{"type":"text","text":"Notifies Apphud when a purchase process is initiated from a paywall in "},{"type":"codeVoice","code":"Observer Mode"},{"type":"text","text":", enabling the use of A\/B experiments. This method should be called right before executing your own purchase method, and it’s specifically required only when the SDK is in Observer Mode."}],"type":"topic","kind":"symbol","role":"symbol","title":"willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"willPurchaseProductFrom","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paywallIdentifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"placementIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:"}],"url":"\/documentation\/apphudsdk\/apphud\/willpurchaseproductfrom(paywallidentifier:placementidentifier:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud\/willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/Apphud":{"url":"\/documentation\/apphudsdk\/apphud","navigatorTitle":[{"text":"Apphud","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/Apphud","title":"Apphud","abstract":[{"type":"text","text":"Entry point of the Apphud SDK. It provides access to all its features."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Apphud"}],"type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"willPurchaseProductFromPaywallIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"paywallIdentifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"placementIdentifier:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"placementIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"parameters":[{"name":"paywallIdentifier","content":[{"type":"paragraph","inlineContent":[{"text":"Required. The Paywall ID from Apphud Product Hub > Paywalls.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Optional. The Placement ID from Apphud Product Hub > Placements if using placements; otherwise, pass "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"placementIdentifier"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"willPurchaseProductFromPaywallIdentifier:placementIdentifier:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud~1willPurchaseProductFrom(paywallIdentifier:placementIdentifier:)\/fragments","op":"replace"},{"value":"Apphud","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/title"},{"value":[{"kind":"identifier","text":"Apphud"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1Apphud\/navigatorTitle","op":"replace","value":[{"text":"Apphud","kind":"identifier"}]}]}]}