{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ApphudSDK@objc(cs)ApphudPaywall(py)experimentName","title":"experimentName","navigatorTitle":[{"kind":"identifier","text":"experimentName"}],"modules":[{"name":"ApphudSDK"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"experimentName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/experimentName","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"experimentName","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphudpaywall\/experimentname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudpaywall\/experimentname"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A\/B test experiment name"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/experimentName":{"url":"\/documentation\/apphudsdk\/apphudpaywall\/experimentname","title":"experimentName","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A\/B test experiment name"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/experimentName","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"experimentName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"experimentName"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"kind":"symbol","title":"ApphudPaywall","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudPaywall"}],"url":"\/documentation\/apphudsdk\/apphudpaywall","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudPaywall","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"experimentName","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"experimentName"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"experimentName","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1experimentName\/title","value":"experimentName","op":"replace"},{"value":[{"kind":"identifier","text":"experimentName"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1experimentName\/fragments","op":"replace"},{"op":"replace","value":"ApphudPaywall","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","value":[{"text":"ApphudPaywall","kind":"identifier"}]},{"value":[{"text":"ApphudPaywall","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/navigatorTitle","op":"replace"}]}]}