{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromPaywall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphudpaywall\/frompaywall"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudpaywall\/frompaywall"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/fromPaywall","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A\/B test paywall identifier"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromPaywall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"fromPaywall","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ApphudSDK@objc(cs)ApphudPaywall(py)fromPaywall","modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"fromPaywall"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/fromPaywall":{"role":"symbol","title":"fromPaywall","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromPaywall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A\/B test paywall identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/fromPaywall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fromPaywall"}],"url":"\/documentation\/apphudsdk\/apphudpaywall\/frompaywall"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"role":"symbol","title":"ApphudPaywall","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPaywall"}],"abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudPaywall"}],"url":"\/documentation\/apphudsdk\/apphudpaywall"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fromPaywall"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fromPaywall"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"fromPaywall"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1fromPaywall\/title","value":"fromPaywall"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1fromPaywall\/fragments","value":[{"kind":"identifier","text":"fromPaywall"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","value":"ApphudPaywall"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","value":[{"kind":"identifier","text":"ApphudPaywall"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}