{"metadata":{"externalID":"s:9ApphudSDK0A7PaywallC09hasVisualC0SbyF","symbolKind":"method","modules":[{"name":"ApphudSDK"}],"title":"hasVisualPaywall()","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasVisualPaywall"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall"]]},"abstract":[{"text":"Use this function to know whether paywall has a valid visual Screen.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/hasVisualPaywall()","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasVisualPaywall"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudpaywall\/hasvisualpaywall()"]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","kind":"symbol","abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"navigatorTitle":[{"text":"ApphudPaywall","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphudpaywall","title":"ApphudPaywall","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudPaywall","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/hasVisualPaywall()":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/hasVisualPaywall()","type":"topic","kind":"symbol","role":"symbol","title":"hasVisualPaywall()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasVisualPaywall"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"Use this function to know whether paywall has a valid visual Screen.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphudpaywall\/hasvisualpaywall()"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","op":"replace","value":"ApphudPaywall"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudPaywall"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/navigatorTitle","value":[{"text":"ApphudPaywall","kind":"identifier"}]}]}]}