{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parentPaywallIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/parentPaywallIdentifier"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Represents the identifier of a parent paywall from which an experiment variation was derived in A\/B Experiments. This property is populated only if the ‘Use existing paywall’ option was selected during the setup of the experiment variation."}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphudpaywall\/parentpaywallidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudpaywall\/parentpaywallidentifier"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@ApphudSDK@objc(cs)ApphudPaywall(py)parentPaywallIdentifier","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parentPaywallIdentifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"parentPaywallIdentifier","kind":"identifier"}],"modules":[{"name":"ApphudSDK"}],"roleHeading":"Instance Property","role":"symbol","title":"parentPaywallIdentifier"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"kind":"symbol","title":"ApphudPaywall","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudPaywall"}],"url":"\/documentation\/apphudsdk\/apphudpaywall","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudPaywall","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/parentPaywallIdentifier":{"role":"symbol","url":"\/documentation\/apphudsdk\/apphudpaywall\/parentpaywallidentifier","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parentPaywallIdentifier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/parentPaywallIdentifier","navigatorTitle":[{"kind":"identifier","text":"parentPaywallIdentifier"}],"kind":"symbol","abstract":[{"text":"Represents the identifier of a parent paywall from which an experiment variation was derived in A\/B Experiments. This property is populated only if the ‘Use existing paywall’ option was selected during the setup of the experiment variation.","type":"text"}],"title":"parentPaywallIdentifier"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"parentPaywallIdentifier","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"parentPaywallIdentifier","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"parentPaywallIdentifier","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"ApphudPaywall","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title"},{"value":[{"text":"ApphudPaywall","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/navigatorTitle","value":[{"text":"ApphudPaywall","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"parentPaywallIdentifier","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1parentPaywallIdentifier\/title"},{"op":"replace","value":[{"text":"parentPaywallIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1parentPaywallIdentifier\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}