{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Current paywall’s placement identifier, if available."}],"kind":"symbol","variants":[{"paths":["\/documentation\/apphudsdk\/apphudpaywall\/placementidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudpaywall\/placementidentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/placementIdentifier"},"sections":[],"metadata":{"navigatorTitle":[{"text":"placementIdentifier","kind":"identifier"}],"role":"symbol","symbolKind":"property","title":"placementIdentifier","externalID":"c:@M@ApphudSDK@objc(cs)ApphudPaywall(py)placementIdentifier","roleHeading":"Instance Property","modules":[{"name":"ApphudSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placementIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placementIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall/placementIdentifier":{"abstract":[{"type":"text","text":"Current paywall’s placement identifier, if available."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall\/placementIdentifier","kind":"symbol","navigatorTitle":[{"text":"placementIdentifier","kind":"identifier"}],"role":"symbol","title":"placementIdentifier","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placementIdentifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/apphudsdk\/apphudpaywall\/placementidentifier"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","url":"\/documentation\/apphudsdk","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","abstract":[]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","navigatorTitle":[{"text":"ApphudPaywall","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPaywall"}],"kind":"symbol","title":"ApphudPaywall","role":"symbol","type":"topic","url":"\/documentation\/apphudsdk\/apphudpaywall","abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"placementIdentifier","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"placementIdentifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"placementIdentifier","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"placementIdentifier","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1placementIdentifier\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall~1placementIdentifier\/fragments","value":[{"text":"placementIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","value":"ApphudPaywall","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","value":[{"text":"ApphudPaywall","kind":"identifier"}],"op":"replace"}]}]}