{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/!=(_:_:)"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","extendedModule":"Swift","title":"!=(_:_:)","modules":[{"name":"ApphudSDK","relatedModules":["Swift"]}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@ApphudSDK@E@ApphudScreenDismissAction","symbolKind":"op","roleHeading":"Operator"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudscreendismissaction\/!=(_:_:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/Equatable-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction":{"abstract":[{"type":"text","text":"These are three types of actions that are returned in "},{"code":"apphudScreenDismissAction(screenName: String, controller: UIViewController)","type":"codeVoice"},{"type":"text","text":" delegate method"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudScreenDismissAction"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction","role":"symbol","title":"ApphudScreenDismissAction","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudScreenDismissAction","kind":"identifier"}],"type":"topic","url":"\/documentation\/apphudsdk\/apphudscreendismissaction"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/Equatable-Implementations","url":"\/documentation\/apphudsdk\/apphudscreendismissaction\/equatable-implementations","type":"topic","abstract":[],"role":"collectionGroup"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","role":"collection","url":"\/documentation\/apphudsdk","abstract":[{"type":"text","text":"Apphud is an all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams make the right decisions based on data and tools."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction/!=(_:_:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/!=(_:_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"type":"topic","title":"!=(_:_:)","url":"\/documentation\/apphudsdk\/apphudscreendismissaction\/!=(_:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction\/title","op":"replace","value":"ApphudScreenDismissAction"},{"value":[{"kind":"identifier","text":"ApphudScreenDismissAction"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction\/navigatorTitle","value":[{"kind":"identifier","text":"ApphudScreenDismissAction"}]}]}]}