{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"closeOnly","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/apphudsdk\/apphudscreendismissaction\/closeonly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudscreendismissaction\/closeonly"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"closeOnly","kind":"identifier"}],"modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"text":"ApphudScreenDismissActionCloseOnly","kind":"identifier"}],"title":"ApphudScreenDismissAction.closeOnly","roleHeading":"Case","externalID":"c:@M@ApphudSDK@E@ApphudScreenDismissAction@ApphudScreenDismissActionCloseOnly"},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/closeOnly","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction/closeOnly":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"closeOnly","kind":"identifier"}],"navigatorTitle":[{"text":"ApphudScreenDismissActionCloseOnly","kind":"identifier"}],"abstract":[],"role":"symbol","title":"ApphudScreenDismissAction.closeOnly","url":"\/documentation\/apphudsdk\/apphudscreendismissaction\/closeonly","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/closeOnly","type":"topic","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction":{"abstract":[{"type":"text","text":"These are three types of actions that are returned in "},{"code":"apphudScreenDismissAction(screenName: String, controller: UIViewController)","type":"codeVoice"},{"type":"text","text":" delegate method"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudScreenDismissAction"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction","role":"symbol","title":"ApphudScreenDismissAction","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudScreenDismissAction","kind":"identifier"}],"type":"topic","url":"\/documentation\/apphudsdk\/apphudscreendismissaction"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","role":"collection","url":"\/documentation\/apphudsdk","abstract":[{"type":"text","text":"Apphud is an all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams make the right decisions based on data and tools."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ApphudScreenDismissActionCloseOnly","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ApphudScreenDismissActionCloseOnly","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"ApphudScreenDismissActionCloseOnly","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction~1closeOnly\/title","value":"ApphudScreenDismissActionCloseOnly"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction~1closeOnly\/fragments","value":[{"kind":"identifier","text":"ApphudScreenDismissActionCloseOnly"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction\/title","value":"ApphudScreenDismissAction","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction\/fragments","value":[{"text":"ApphudScreenDismissAction","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ApphudScreenDismissAction"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}