{"sections":[],"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"ApphudScreenDismissActionThankAndClose","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@ApphudSDK@E@ApphudScreenDismissAction@ApphudScreenDismissActionThankAndClose","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"thankAndClose","kind":"identifier"}],"title":"ApphudScreenDismissAction.thankAndClose","modules":[{"name":"ApphudSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudscreendismissaction\/thankandclose"]},{"paths":["\/documentation\/apphudsdk\/apphudscreendismissaction\/thankandclose"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/thankAndClose"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"thankAndClose","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction/thankAndClose":{"type":"topic","navigatorTitle":[{"text":"ApphudScreenDismissActionThankAndClose","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"thankAndClose","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction\/thankAndClose","url":"\/documentation\/apphudsdk\/apphudscreendismissaction\/thankandclose","title":"ApphudScreenDismissAction.thankAndClose","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudScreenDismissAction"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudScreenDismissAction"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphudscreendismissaction","type":"topic","kind":"symbol","title":"ApphudScreenDismissAction","abstract":[{"text":"These are three types of actions that are returned in ","type":"text"},{"code":"apphudScreenDismissAction(screenName: String, controller: UIViewController)","type":"codeVoice"},{"type":"text","text":" delegate method"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ApphudScreenDismissActionThankAndClose","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"ApphudScreenDismissActionThankAndClose","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ApphudScreenDismissActionThankAndClose"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction~1thankAndClose\/title","value":"ApphudScreenDismissActionThankAndClose"},{"op":"replace","value":[{"text":"ApphudScreenDismissActionThankAndClose","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction~1thankAndClose\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction\/title","value":"ApphudScreenDismissAction"},{"value":[{"kind":"identifier","text":"ApphudScreenDismissAction"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}