{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Returns true if the product has a commitment plan option configured in the Paywall page of Mission control."},{"type":"text","text":" "},{"text":"If true, SDK will try to purchase commitment plan offer instead of regular pricing.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCommitmentPlanSupported","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/apphudsdk\/apphudproduct\/iscommitmentplansupported()"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct"]]},"metadata":{"role":"symbol","title":"isCommitmentPlanSupported()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isCommitmentPlanSupported","kind":"identifier"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":[{"beta":false,"unavailable":false,"introducedAt":"26.4","name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"26.4","name":"iPadOS","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"26.4","beta":false},{"beta":false,"unavailable":false,"introducedAt":"26.4","name":"macOS","deprecated":false},{"introducedAt":"26.4","deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"introducedAt":"26.4","deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"},{"introducedAt":"26.4","deprecated":false,"unavailable":false,"beta":false,"name":"watchOS"}],"externalID":"s:9ApphudSDK0A7ProductC25isCommitmentPlanSupportedSbyYaF","symbolKind":"method","modules":[{"name":"ApphudSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct\/isCommitmentPlanSupported()"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct/isCommitmentPlanSupported()":{"kind":"symbol","title":"isCommitmentPlanSupported()","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct\/isCommitmentPlanSupported()","url":"\/documentation\/apphudsdk\/apphudproduct\/iscommitmentplansupported()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCommitmentPlanSupported"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Returns true if the product has a commitment plan option configured in the Paywall page of Mission control.","type":"text"},{"text":" ","type":"text"},{"text":"If true, SDK will try to purchase commitment plan offer instead of regular pricing.","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct":{"title":"ApphudProduct","navigatorTitle":[{"kind":"identifier","text":"ApphudProduct"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudProduct"}],"kind":"symbol","url":"\/documentation\/apphudsdk\/apphudproduct","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","type":"topic","abstract":[{"type":"text","text":"Apphud’s wrapper around "},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/title","value":"ApphudProduct","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/fragments","value":[{"kind":"identifier","text":"ApphudProduct"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/navigatorTitle","value":[{"kind":"identifier","text":"ApphudProduct"}]}]}]}