{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct"]]},"kind":"symbol","metadata":{"role":"symbol","title":"properties","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"properties","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A10AnyCodableV","text":"ApphudAnyCodable","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"symbolKind":"property","externalID":"s:9ApphudSDK0A7ProductC10propertiesSDySSAA0A10AnyCodableVGSgvp","modules":[{"name":"ApphudSDK"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"properties"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAnyCodable","kind":"typeIdentifier","text":"ApphudAnyCodable","preciseIdentifier":"s:9ApphudSDK0A10AnyCodableV"},{"kind":"text","text":"]? { get }"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct\/properties","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudproduct\/properties"]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct/properties":{"kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct\/properties","title":"properties","url":"\/documentation\/apphudsdk\/apphudproduct\/properties","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A10AnyCodableV","text":"ApphudAnyCodable","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct":{"title":"ApphudProduct","navigatorTitle":[{"kind":"identifier","text":"ApphudProduct"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudProduct"}],"kind":"symbol","url":"\/documentation\/apphudsdk\/apphudproduct","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","type":"topic","abstract":[{"type":"text","text":"Apphud’s wrapper around "},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"."}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAnyCodable":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAnyCodable","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudAnyCodable"}],"title":"ApphudAnyCodable","url":"\/documentation\/apphudsdk\/apphudanycodable","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ApphudAnyCodable","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/title","op":"replace","value":"ApphudProduct"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/fragments","value":[{"kind":"identifier","text":"ApphudProduct"}]},{"value":[{"kind":"identifier","text":"ApphudProduct"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}