{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:7Combine9PublishedV","text":"Published"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"skProduct","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"May be "},{"type":"codeVoice","code":"nil"},{"text":" if product identifier is invalid, or product is not available in App Store Connect.","type":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct\/skProduct"},"sections":[],"metadata":{"title":"skProduct","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"skProduct","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"skProduct","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier","text":"SKProduct"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"ApphudSDK"}],"externalID":"c:@M@ApphudSDK@objc(cs)ApphudProduct(py)skProduct"},"abstract":[{"text":"When paywalls are successfully loaded, skProduct model will always be present if App Store returned model for this product id. getPaywalls method will return callback only when StoreKit products are fetched and mapped with Apphud products.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudproduct\/skproduct"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudproduct\/skproduct"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct":{"kind":"symbol","navigatorTitle":[{"text":"ApphudProduct","kind":"identifier"}],"type":"topic","url":"\/documentation\/apphudsdk\/apphudproduct","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","abstract":[{"type":"text","text":"Apphud’s wrapper around "},{"type":"codeVoice","code":"SKProduct"},{"text":".","type":"text"}],"title":"ApphudProduct","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudProduct"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct/skProduct":{"abstract":[{"text":"When paywalls are successfully loaded, skProduct model will always be present if App Store returned model for this product id. getPaywalls method will return callback only when StoreKit products are fetched and mapped with Apphud products.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphudproduct\/skproduct","title":"skProduct","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct\/skProduct","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"skProduct","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"skProduct"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"skProduct"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"skProduct","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":" * "},{"text":"skProduct","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"ApphudProduct","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/title"},{"op":"replace","value":[{"text":"ApphudProduct","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ApphudProduct"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct~1skProduct\/title","value":"skProduct"},{"op":"replace","value":[{"kind":"identifier","text":"skProduct"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct~1skProduct\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}