{"kind":"symbol","variants":[{"paths":["\/documentation\/apphudsdk\/apphudpaywallscreenfetchresult\/error(error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:9ApphudSDK0A24PaywallScreenFetchResultO5erroryAcA0A5ErrorC_tcACmF","role":"symbol","symbolKind":"case","roleHeading":"Case","title":"ApphudPaywallScreenFetchResult.error(error:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError","text":"ApphudError"},{"kind":"text","text":")"}],"modules":[{"name":"ApphudSDK"}]},"abstract":[{"text":"An error occurred while fetching or initializing the paywall screen.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenFetchResult"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenFetchResult\/error(error:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError","text":"ApphudError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The error describing what went wrong."}],"type":"paragraph"}],"name":"error"}]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenFetchResult/error(error:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenFetchResult\/error(error:)","url":"\/documentation\/apphudsdk\/apphudpaywallscreenfetchresult\/error(error:)","abstract":[{"text":"An error occurred while fetching or initializing the paywall screen.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudError","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"ApphudPaywallScreenFetchResult.error(error:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudError":{"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudError"}],"url":"\/documentation\/apphudsdk\/apphuderror","title":"ApphudError","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudError"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenFetchResult":{"type":"topic","title":"ApphudPaywallScreenFetchResult","abstract":[{"type":"text","text":"Represents the result of attempting to fetch and prepare a paywall screen for display."}],"navigatorTitle":[{"text":"ApphudPaywallScreenFetchResult","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPaywallScreenFetchResult"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenFetchResult","url":"\/documentation\/apphudsdk\/apphudpaywallscreenfetchresult","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"ApphudError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/fragments","value":[{"kind":"identifier","text":"ApphudError"}]},{"value":[{"text":"ApphudError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}