{"variants":[{"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/adjust"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/adjust"]}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"adjust","kind":"identifier"}],"title":"ApphudAttributionProvider.adjust","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderAdjust"}],"externalID":"c:@M@ApphudSDK@E@ApphudAttributionProvider@ApphudAttributionProviderAdjust","role":"symbol","modules":[{"name":"ApphudSDK"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/adjust","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"adjust","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider":{"url":"\/documentation\/apphudsdk\/apphudattributionprovider","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider","abstract":[{"type":"text","text":"List of available attribution providers"},{"type":"text","text":" "},{"text":"has to make Int in order to support Objective-C","type":"text"}],"kind":"symbol","type":"topic","title":"ApphudAttributionProvider","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudAttributionProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ApphudAttributionProvider","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","url":"\/documentation\/apphudsdk","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","abstract":[]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/adjust":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/adjust","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"adjust","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphudattributionprovider\/adjust","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderAdjust"}],"abstract":[],"title":"ApphudAttributionProvider.adjust","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ApphudAttributionProviderAdjust"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ApphudAttributionProviderAdjust","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ApphudAttributionProviderAdjust","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/title","value":"ApphudAttributionProvider"},{"op":"replace","value":[{"kind":"identifier","text":"ApphudAttributionProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1adjust\/title","value":"ApphudAttributionProviderAdjust"},{"value":[{"kind":"identifier","text":"ApphudAttributionProviderAdjust"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1adjust\/fragments","op":"replace"}]}]}