{"metadata":{"externalID":"c:@M@ApphudSDK@E@ApphudAttributionProvider@ApphudAttributionProviderAppleAdsAttribution","title":"ApphudAttributionProvider.appleAdsAttribution","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appleAdsAttribution","kind":"identifier"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"ApphudAttributionProviderAppleAdsAttribution","kind":"identifier"}],"modules":[{"name":"ApphudSDK"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appleAdsAttribution","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/appleAdsAttribution"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/appleadsattribution"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/appleadsattribution"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/appleAdsAttribution":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ApphudAttributionProviderAppleAdsAttribution","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/appleAdsAttribution","title":"ApphudAttributionProvider.appleAdsAttribution","type":"topic","url":"\/documentation\/apphudsdk\/apphudattributionprovider\/appleadsattribution","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appleAdsAttribution","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider","url":"\/documentation\/apphudsdk\/apphudattributionprovider","abstract":[{"text":"List of available attribution providers","type":"text"},{"text":" ","type":"text"},{"text":"has to make Int in order to support Objective-C","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudAttributionProvider"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProvider"}],"title":"ApphudAttributionProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ApphudAttributionProviderAppleAdsAttribution"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudAttributionProviderAppleAdsAttribution"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ApphudAttributionProviderAppleAdsAttribution","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1appleAdsAttribution\/title","op":"replace","value":"ApphudAttributionProviderAppleAdsAttribution"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1appleAdsAttribution\/fragments","op":"replace","value":[{"text":"ApphudAttributionProviderAppleAdsAttribution","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/title","op":"replace","value":"ApphudAttributionProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudAttributionProvider"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ApphudAttributionProvider"}]}]}]}