{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/branch"]},{"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/branch"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"ApphudAttributionProvider.branch","externalID":"c:@M@ApphudSDK@E@ApphudAttributionProvider@ApphudAttributionProviderBranch","modules":[{"name":"ApphudSDK"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"branch","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderBranch"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"branch"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/branch"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider":{"abstract":[{"text":"List of available attribution providers","type":"text"},{"type":"text","text":" "},{"type":"text","text":"has to make Int in order to support Objective-C"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider","url":"\/documentation\/apphudsdk\/apphudattributionprovider","title":"ApphudAttributionProvider","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudAttributionProvider"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProvider"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/branch":{"type":"topic","title":"ApphudAttributionProvider.branch","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/branch","url":"\/documentation\/apphudsdk\/apphudattributionprovider\/branch","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"branch"}],"kind":"symbol","navigatorTitle":[{"text":"ApphudAttributionProviderBranch","kind":"identifier"}],"abstract":[],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ApphudAttributionProviderBranch","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"ApphudAttributionProviderBranch"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ApphudAttributionProviderBranch","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ApphudAttributionProvider","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/fragments","value":[{"text":"ApphudAttributionProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/navigatorTitle","value":[{"text":"ApphudAttributionProvider","kind":"identifier"}]},{"value":"ApphudAttributionProviderBranch","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1branch\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1branch\/fragments","value":[{"text":"ApphudAttributionProviderBranch","kind":"identifier"}]}]}]}