{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Pass custom attribution data to Apphud. Contact your support manager for details.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"custom","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ApphudSDK"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@ApphudSDK@E@ApphudAttributionProvider@ApphudAttributionProviderCustom","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderCustom"}],"title":"ApphudAttributionProvider.custom"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/custom"]},{"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/custom"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/custom","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/custom":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderCustom"}],"abstract":[{"type":"text","text":"Pass custom attribution data to Apphud. Contact your support manager for details."}],"type":"topic","title":"ApphudAttributionProvider.custom","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/custom","url":"\/documentation\/apphudsdk\/apphudattributionprovider\/custom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider","url":"\/documentation\/apphudsdk\/apphudattributionprovider","abstract":[{"text":"List of available attribution providers","type":"text"},{"text":" ","type":"text"},{"text":"has to make Int in order to support Objective-C","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudAttributionProvider"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProvider"}],"title":"ApphudAttributionProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ApphudAttributionProviderCustom","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ApphudAttributionProviderCustom","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"ApphudAttributionProviderCustom","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1custom\/title","value":"ApphudAttributionProviderCustom"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1custom\/fragments","value":[{"text":"ApphudAttributionProviderCustom","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/title","value":"ApphudAttributionProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/fragments","value":[{"text":"ApphudAttributionProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/navigatorTitle","value":[{"text":"ApphudAttributionProvider","kind":"identifier"}]}]}]}