{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"firebase","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/firebase"]},{"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/firebase"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/firebase","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderFirebase"}],"roleHeading":"Case","modules":[{"name":"ApphudSDK"}],"title":"ApphudAttributionProvider.firebase","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"firebase","kind":"identifier"}],"externalID":"c:@M@ApphudSDK@E@ApphudAttributionProvider@ApphudAttributionProviderFirebase"},"kind":"symbol","references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider":{"abstract":[{"text":"List of available attribution providers","type":"text"},{"type":"text","text":" "},{"type":"text","text":"has to make Int in order to support Objective-C"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider","url":"\/documentation\/apphudsdk\/apphudattributionprovider","title":"ApphudAttributionProvider","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudAttributionProvider"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProvider"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/firebase":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderFirebase"}],"title":"ApphudAttributionProvider.firebase","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firebase","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/apphudsdk\/apphudattributionprovider\/firebase","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/firebase"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ApphudAttributionProviderFirebase"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ApphudAttributionProviderFirebase","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ApphudAttributionProviderFirebase","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/title","value":"ApphudAttributionProvider"},{"op":"replace","value":[{"text":"ApphudAttributionProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/fragments"},{"value":[{"kind":"identifier","text":"ApphudAttributionProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1firebase\/title","value":"ApphudAttributionProviderFirebase","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1firebase\/fragments","value":[{"kind":"identifier","text":"ApphudAttributionProviderFirebase"}]}]}]}