{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tenjin","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"case","roleHeading":"Case","modules":[{"name":"ApphudSDK"}],"title":"ApphudAttributionProvider.tenjin","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"tenjin","kind":"identifier"}],"externalID":"c:@M@ApphudSDK@E@ApphudAttributionProvider@ApphudAttributionProviderTenjin","navigatorTitle":[{"text":"ApphudAttributionProviderTenjin","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/tenjin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/tenjin"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/tenjin"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider":{"navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProvider"}],"url":"\/documentation\/apphudsdk\/apphudattributionprovider","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ApphudAttributionProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"List of available attribution providers"},{"text":" ","type":"text"},{"text":"has to make Int in order to support Objective-C","type":"text"}],"role":"symbol","title":"ApphudAttributionProvider","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","role":"collection","url":"\/documentation\/apphudsdk","abstract":[{"type":"text","text":"Apphud is an all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams make the right decisions based on data and tools."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/tenjin":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/tenjin","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProviderTenjin"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphudattributionprovider\/tenjin","title":"ApphudAttributionProvider.tenjin","kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"tenjin","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ApphudAttributionProviderTenjin","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"ApphudAttributionProviderTenjin","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ApphudAttributionProviderTenjin","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/title","value":"ApphudAttributionProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/fragments","value":[{"kind":"identifier","text":"ApphudAttributionProvider"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/navigatorTitle","value":[{"text":"ApphudAttributionProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1tenjin\/title","op":"replace","value":"ApphudAttributionProviderTenjin"},{"value":[{"kind":"identifier","text":"ApphudAttributionProviderTenjin"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1tenjin\/fragments"}]}]}