{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tiktok"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/tiktok"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudattributionprovider\/tiktok"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider"]]},"metadata":{"externalID":"c:@M@ApphudSDK@E@ApphudAttributionProvider@ApphudAttributionProviderTiktok","role":"symbol","navigatorTitle":[{"text":"ApphudAttributionProviderTiktok","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","title":"ApphudAttributionProvider.tiktok","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tiktok"}],"modules":[{"name":"ApphudSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/tiktok"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider/tiktok":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider\/tiktok","navigatorTitle":[{"text":"ApphudAttributionProviderTiktok","kind":"identifier"}],"role":"symbol","title":"ApphudAttributionProvider.tiktok","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tiktok","kind":"identifier"}],"abstract":[],"url":"\/documentation\/apphudsdk\/apphudattributionprovider\/tiktok"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudAttributionProvider":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudAttributionProvider","url":"\/documentation\/apphudsdk\/apphudattributionprovider","abstract":[{"text":"List of available attribution providers","type":"text"},{"text":" ","type":"text"},{"text":"has to make Int in order to support Objective-C","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudAttributionProvider"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudAttributionProvider"}],"title":"ApphudAttributionProvider"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ApphudAttributionProviderTiktok","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ApphudAttributionProviderTiktok"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ApphudAttributionProviderTiktok"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1tiktok\/title","op":"replace","value":"ApphudAttributionProviderTiktok"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider~1tiktok\/fragments","op":"replace","value":[{"text":"ApphudAttributionProviderTiktok","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/title","op":"replace","value":"ApphudAttributionProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudAttributionProvider"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudAttributionProvider\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ApphudAttributionProvider"}]}]}]}