{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError\/networkIssue()"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkIssue","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphuderror\/networkissue()"]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkIssue"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"networkIssue()","symbolKind":"method","modules":[{"name":"ApphudSDK"}],"externalID":"s:9ApphudSDK0A5ErrorC12networkIssueSbyF"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudError/networkIssue()":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError\/networkIssue()","url":"\/documentation\/apphudsdk\/apphuderror\/networkissue()","role":"symbol","kind":"symbol","title":"networkIssue()","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkIssue"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudError":{"type":"topic","url":"\/documentation\/apphudsdk\/apphuderror","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ApphudError","kind":"identifier"}],"title":"ApphudError","navigatorTitle":[{"kind":"identifier","text":"ApphudError"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/title","value":"ApphudError","op":"replace"},{"value":[{"kind":"identifier","text":"ApphudError"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ApphudError"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/navigatorTitle"}]}]}