{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationVersion"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/applicationVersion"},"abstract":[{"text":"The app’s version number. The app’s version number corresponds to the value of CFBundleVersion (in iOS) or CFBundleShortVersionString (in macOS) in the Info.plist. In production, this value is the current version of the app on the device based on the receipt_creation_date_ms. In the sandbox, the value is always “1.0”.","type":"text"}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphudreceipt\/applicationversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudreceipt\/applicationversion"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"applicationVersion"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"applicationVersion","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"applicationVersion","modules":[{"name":"ApphudSDK"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ApphudSDK@objc(cs)ApphudReceipt(py)applicationVersion"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt/applicationVersion":{"type":"topic","url":"\/documentation\/apphudsdk\/apphudreceipt\/applicationversion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/applicationVersion","title":"applicationVersion","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"applicationVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"The app’s version number. The app’s version number corresponds to the value of CFBundleVersion (in iOS) or CFBundleShortVersionString (in macOS) in the Info.plist. In production, this value is the current version of the app on the device based on the receipt_creation_date_ms. In the sandbox, the value is always “1.0”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"applicationVersion"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt":{"role":"symbol","title":"ApphudReceipt","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudReceipt","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ApphudReceipt"},{"text":" is Apphud’s wrapper around StoreKit’s ","type":"text"},{"type":"codeVoice","code":"Receipt"},{"type":"text","text":"."}],"url":"\/documentation\/apphudsdk\/apphudreceipt","navigatorTitle":[{"text":"ApphudReceipt","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"applicationVersion","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"applicationVersion"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"applicationVersion"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1applicationVersion\/title","op":"replace","value":"applicationVersion"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1applicationVersion\/fragments","op":"replace","value":[{"text":"applicationVersion","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt\/title","op":"replace","value":"ApphudReceipt"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt\/fragments","value":[{"text":"ApphudReceipt","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}