{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"originalPurchaseDate","kind":"identifier"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","title":"originalPurchaseDate","modules":[{"name":"ApphudSDK"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ApphudSDK@objc(cs)ApphudReceipt(py)originalPurchaseDate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"originalPurchaseDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"originalPurchaseDate"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/originalPurchaseDate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudreceipt\/originalpurchasedate"]},{"paths":["\/documentation\/apphudsdk\/apphudreceipt\/originalpurchasedate"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The time of the original app purchase. Value is ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" in StoreKit Testing generated receipts."}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudReceipt"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudReceipt"}],"abstract":[{"type":"codeVoice","code":"ApphudReceipt"},{"text":" is Apphud’s wrapper around StoreKit’s ","type":"text"},{"type":"codeVoice","code":"Receipt"},{"text":".","type":"text"}],"url":"\/documentation\/apphudsdk\/apphudreceipt","kind":"symbol","title":"ApphudReceipt","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt/originalPurchaseDate":{"navigatorTitle":[{"text":"originalPurchaseDate","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphudreceipt\/originalpurchasedate","type":"topic","title":"originalPurchaseDate","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/originalPurchaseDate","abstract":[{"type":"text","text":"The time of the original app purchase. Value is "},{"code":"nil","type":"codeVoice"},{"text":" in StoreKit Testing generated receipts.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"originalPurchaseDate"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"originalPurchaseDate","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"originalPurchaseDate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"text":" * ","kind":"text"},{"text":"originalPurchaseDate","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"ApphudReceipt","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudReceipt"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1originalPurchaseDate\/title","value":"originalPurchaseDate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1originalPurchaseDate\/fragments","value":[{"text":"originalPurchaseDate","kind":"identifier"}]}]}]}