{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudreceipt\/originalapplicationversion"]},{"paths":["\/documentation\/apphudsdk\/apphudreceipt\/originalapplicationversion"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The version of the app that the user originally purchased. This value does not change, and corresponds to the value of CFBundleVersion (in iOS) or CFBundleShortVersionString (in macOS) in the Info.plist file of the original purchase. In the sandbox environment, the value is always “1.0”."},{"type":"text","text":" "},{"type":"text","text":"Value is "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" in StoreKit Testing generated receipts."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"originalApplicationVersion","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","externalID":"c:@M@ApphudSDK@objc(cs)ApphudReceipt(py)originalApplicationVersion","navigatorTitle":[{"text":"originalApplicationVersion","kind":"identifier"}],"title":"originalApplicationVersion","modules":[{"name":"ApphudSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"originalApplicationVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/originalApplicationVersion","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt/originalApplicationVersion":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"originalApplicationVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","title":"originalApplicationVersion","abstract":[{"type":"text","text":"The version of the app that the user originally purchased. This value does not change, and corresponds to the value of CFBundleVersion (in iOS) or CFBundleShortVersionString (in macOS) in the Info.plist file of the original purchase. In the sandbox environment, the value is always “1.0”."},{"text":" ","type":"text"},{"type":"text","text":"Value is "},{"code":"nil","type":"codeVoice"},{"text":" in StoreKit Testing generated receipts.","type":"text"}],"url":"\/documentation\/apphudsdk\/apphudreceipt\/originalapplicationversion","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"originalApplicationVersion"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt\/originalApplicationVersion"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","url":"\/documentation\/apphudsdk","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","abstract":[]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudReceipt":{"abstract":[{"code":"ApphudReceipt","type":"codeVoice"},{"text":" is Apphud’s wrapper around StoreKit’s ","type":"text"},{"code":"Receipt","type":"codeVoice"},{"text":".","type":"text"}],"title":"ApphudReceipt","url":"\/documentation\/apphudsdk\/apphudreceipt","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudReceipt","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudReceipt","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudReceipt"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"originalApplicationVersion","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"originalApplicationVersion","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"originalApplicationVersion"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"originalApplicationVersion","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1originalApplicationVersion\/title","op":"replace"},{"value":[{"text":"originalApplicationVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt~1originalApplicationVersion\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt\/title","op":"replace","value":"ApphudReceipt"},{"op":"replace","value":[{"kind":"identifier","text":"ApphudReceipt"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudReceipt\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}