{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiresDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphudsubscription\/expiresdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudsubscription\/expiresdate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscription\/expiresDate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Expiration date of subscription period. You shouldn’t use this property to detect if subscription is active because user can change system date in iOS settings. Check isActive() method instead."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiresDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"title":"expiresDate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ApphudSDK@objc(cs)ApphudSubscription(py)expiresDate","modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"expiresDate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscription"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudSubscription":{"role":"symbol","title":"ApphudSubscription","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudSubscription"}],"abstract":[{"type":"text","text":"Custom Apphud class containing all information about customer subscription."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudSubscription"}],"url":"\/documentation\/apphudsdk\/apphudsubscription"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudSubscription/expiresDate":{"role":"symbol","title":"expiresDate","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiresDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[{"type":"text","text":"Expiration date of subscription period. You shouldn’t use this property to detect if subscription is active because user can change system date in iOS settings. Check isActive() method instead."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscription\/expiresDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"expiresDate"}],"url":"\/documentation\/apphudsdk\/apphudsubscription\/expiresdate"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"expiresDate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"expiresDate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"expiresDate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscription\/title","value":"ApphudSubscription"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscription\/fragments","value":[{"kind":"identifier","text":"ApphudSubscription"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscription~1expiresDate\/title","value":"expiresDate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscription~1expiresDate\/fragments","value":[{"kind":"identifier","text":"expiresDate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}