{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"An error occurred while loading the paywall."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError","text":"ApphudError","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"error","content":[{"inlineContent":[{"text":"The error describing the failure.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"This state indicates that the content could not be loaded due to a network issue,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"invalid paywall URL, or another error. Developer should show default paywall instead."}],"type":"paragraph"}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/apphudsdk\/apphudpaywallscreenstate\/error(error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"ApphudError","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"ApphudPaywallScreenState.error(error:)","role":"symbol","roleHeading":"Case","externalID":"s:9ApphudSDK0A18PaywallScreenStateO5erroryAcA0A5ErrorC_tcACmF","symbolKind":"case","modules":[{"name":"ApphudSDK"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenState\/error(error:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenState"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenState/error(error:)":{"url":"\/documentation\/apphudsdk\/apphudpaywallscreenstate\/error(error:)","type":"topic","abstract":[{"text":"An error occurred while loading the paywall.","type":"text"}],"title":"ApphudPaywallScreenState.error(error:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudError","text":"ApphudError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenState\/error(error:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenState":{"type":"topic","abstract":[{"text":"Represents the current loading state of a paywall screen.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApphudPaywallScreenState","kind":"identifier"}],"title":"ApphudPaywallScreenState","kind":"symbol","url":"\/documentation\/apphudsdk\/apphudpaywallscreenstate","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenState","navigatorTitle":[{"kind":"identifier","text":"ApphudPaywallScreenState"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","role":"collection","url":"\/documentation\/apphudsdk","abstract":[{"type":"text","text":"Apphud is an all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams make the right decisions based on data and tools."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudError":{"abstract":[],"title":"ApphudError","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudError","kind":"symbol","navigatorTitle":[{"text":"ApphudError","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudError","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphuderror"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/title","value":"ApphudError","op":"replace"},{"value":[{"kind":"identifier","text":"ApphudError"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudError\/navigatorTitle","value":[{"kind":"identifier","text":"ApphudError"}]}]}]}