{"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/apphudViewHandlePurchase(index:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/apphudviewhandlepurchase(index:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudViewHandlePurchase"},{"text":"(","kind":"text"},{"text":"index","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"externalID":"s:9ApphudSDK0A23PaywallScreenControllerC24apphudViewHandlePurchase5indexySi_tF","title":"apphudViewHandlePurchase(index:)","symbolKind":"method","extendedModule":"ApphudSDK","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ApphudSDK"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"ApphudViewDelegate.apphudViewHandlePurchase(index:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apphudViewHandlePurchase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"index","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/ApphudViewDelegate-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/ApphudViewDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/ApphudViewDelegate-Implementations","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/apphudviewdelegate-implementations","kind":"article","title":"ApphudViewDelegate Implementations","role":"collectionGroup","type":"topic","abstract":[]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","role":"collection","url":"\/documentation\/apphudsdk","abstract":[{"type":"text","text":"Apphud is an all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams make the right decisions based on data and tools."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/apphudViewHandlePurchase(index:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/apphudViewHandlePurchase(index:)","role":"symbol","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/apphudviewhandlepurchase(index:)","title":"apphudViewHandlePurchase(index:)","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apphudViewHandlePurchase","kind":"identifier"},{"kind":"text","text":"("},{"text":"index","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPaywallScreenController"}],"url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller","kind":"symbol","title":"ApphudPaywallScreenController","role":"symbol","navigatorTitle":[{"text":"ApphudPaywallScreenController","kind":"identifier"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ApphudPaywallScreenController","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/fragments","value":[{"text":"ApphudPaywallScreenController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/navigatorTitle","value":[{"kind":"identifier","text":"ApphudPaywallScreenController"}],"op":"replace"}]}]}