{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTransactionStarted"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"ApphudProduct","type":"codeVoice"},{"text":" being purchased, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the user initiated a restore action.","type":"text"}],"type":"paragraph"}],"name":"product"}],"kind":"parameters"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"By default, if ","type":"text"},{"code":"useSystemLoadingIndicator","type":"codeVoice"},{"type":"text","text":" is "},{"type":"codeVoice","code":"true"},{"type":"text","text":", the SDK will automatically display a system loading indicator."},{"type":"text","text":" "},{"type":"text","text":"To use your own custom loading indicator, set "},{"code":"useSystemLoadingIndicator = false","type":"codeVoice"},{"type":"text","text":" and handle the UI in this callback."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/onTransactionStarted","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/ontransactionstarted"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController"]]},"abstract":[{"type":"text","text":"Called when the user initiates a purchase or starts restoring purchases."}],"kind":"symbol","metadata":{"modules":[{"name":"ApphudSDK"}],"symbolKind":"property","externalID":"s:9ApphudSDK0A23PaywallScreenControllerC20onTransactionStartedyAA0A7ProductCSgcSgvp","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTransactionStarted"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","kind":"typeIdentifier","text":"ApphudProduct"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"title":"onTransactionStarted"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct":{"title":"ApphudProduct","navigatorTitle":[{"kind":"identifier","text":"ApphudProduct"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudProduct"}],"kind":"symbol","url":"\/documentation\/apphudsdk\/apphudproduct","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","type":"topic","abstract":[{"type":"text","text":"Apphud’s wrapper around "},{"type":"codeVoice","code":"SKProduct"},{"type":"text","text":"."}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/onTransactionStarted":{"title":"onTransactionStarted","type":"topic","abstract":[{"text":"Called when the user initiates a purchase or starts restoring purchases.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onTransactionStarted","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"ApphudProduct","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/onTransactionStarted","kind":"symbol","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/ontransactionstarted","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController","navigatorTitle":[{"kind":"identifier","text":"ApphudPaywallScreenController"}],"url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller","kind":"symbol","abstract":[],"title":"ApphudPaywallScreenController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPaywallScreenController"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/title","op":"replace","value":"ApphudProduct"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/fragments","value":[{"kind":"identifier","text":"ApphudProduct"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/navigatorTitle","value":[{"kind":"identifier","text":"ApphudProduct"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/title","value":"ApphudPaywallScreenController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/fragments","value":[{"kind":"identifier","text":"ApphudPaywallScreenController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/navigatorTitle","value":[{"text":"ApphudPaywallScreenController","kind":"identifier"}]}]}]}