{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onTransactionCompleted","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"ApphudPurchaseResult","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"ApphudPurchaseResult"},{"type":"text","text":" containing details of the purchase, including the product, the error (if any),"},{"type":"text","text":" "},{"type":"text","text":"the underlying "},{"code":"SKPaymentTransaction","type":"codeVoice"},{"type":"text","text":", and the "},{"code":"userCanceled","type":"codeVoice"},{"type":"text","text":" flag."}]}],"name":"result"}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"By default, if "},{"type":"codeVoice","code":"useSystemLoadingIndicator"},{"type":"text","text":" is "},{"code":"true","type":"codeVoice"},{"text":", the SDK will automatically hide the system loading indicator.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"To use your own custom loading indicator, set "},{"code":"useSystemLoadingIndicator = false","type":"codeVoice"},{"text":" and handle the UI in this callback.","type":"text"},{"type":"text","text":" "},{"text":"If the purchase or restoration succeeds, the controller will be automatically dismissed if ","type":"text"},{"code":"shouldAutoDismiss","type":"codeVoice"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/ontransactioncompleted"]}],"metadata":{"title":"onTransactionCompleted","roleHeading":"Instance Property","externalID":"s:9ApphudSDK0A23PaywallScreenControllerC22onTransactionCompletedyAA0A14PurchaseResultCcSgvp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onTransactionCompleted","kind":"identifier"},{"kind":"text","text":": (("},{"text":"ApphudPurchaseResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"role":"symbol","symbolKind":"property","modules":[{"name":"ApphudSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController"]]},"kind":"symbol","sections":[],"abstract":[{"text":"Called when a purchase or restoration completes, either successfully or with a failure due to user cancellation or another error.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/onTransactionCompleted","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPaywallScreenController"}],"url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller","kind":"symbol","title":"ApphudPaywallScreenController","role":"symbol","navigatorTitle":[{"text":"ApphudPaywallScreenController","kind":"identifier"}],"type":"topic","abstract":[]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/onTransactionCompleted":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/onTransactionCompleted","role":"symbol","type":"topic","title":"onTransactionCompleted","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/ontransactioncompleted","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onTransactionCompleted","kind":"identifier"},{"kind":"text","text":": (("},{"text":"ApphudPurchaseResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Called when a purchase or restoration completes, either successfully or with a failure due to user cancellation or another error."}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"type":"topic","title":"ApphudPurchaseResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPurchaseResult"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","navigatorTitle":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"kind":"symbol","abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","role":"collection","url":"\/documentation\/apphudsdk","abstract":[{"type":"text","text":"Apphud is an all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams make the right decisions based on data and tools."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/title","value":"ApphudPaywallScreenController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/fragments","value":[{"text":"ApphudPaywallScreenController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/navigatorTitle","value":[{"text":"ApphudPaywallScreenController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ApphudPurchaseResult","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title"},{"value":[{"text":"ApphudPurchaseResult","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments","op":"replace"},{"value":[{"text":"ApphudPurchaseResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/navigatorTitle"}]}]}