{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Indicated whether controller should dismiss automatically on close button tap or on successful purchase or restoration. Default is "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/shouldautodismiss"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldAutoDismiss","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"externalID":"s:9ApphudSDK0A23PaywallScreenControllerC17shouldAutoDismissSbvp","modules":[{"name":"ApphudSDK"}],"symbolKind":"property","title":"shouldAutoDismiss"},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/shouldAutoDismiss"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldAutoDismiss","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/shouldAutoDismiss":{"role":"symbol","abstract":[{"type":"text","text":"Indicated whether controller should dismiss automatically on close button tap or on successful purchase or restoration. Default is "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldAutoDismiss","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/shouldAutoDismiss","type":"topic","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/shouldautodismiss","title":"shouldAutoDismiss"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ApphudPaywallScreenController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudPaywallScreenController"}],"url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller","abstract":[],"title":"ApphudPaywallScreenController","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ApphudPaywallScreenController","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/fragments","value":[{"text":"ApphudPaywallScreenController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/navigatorTitle","value":[{"text":"ApphudPaywallScreenController","kind":"identifier"}]}]}]}