{"metadata":{"symbolKind":"method","title":"webView(_:createWebViewWith:for:windowFeatures:)","extendedModule":"ApphudSDK","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createWebViewWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebViewConfiguration","text":"WKWebViewConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"windowFeatures"},{"text":": ","kind":"text"},{"text":"WKWindowFeatures","preciseIdentifier":"c:objc(cs)WKWindowFeatures","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@CM@ApphudSDK@objc(cs)ApphudPaywallScreenController(im)webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:","modules":[{"name":"ApphudSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/webview(_:createwebviewwith:for:windowfeatures:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/webview(_:createwebviewwith:for:windowfeatures:)"]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WKUIDelegate.webView(_:createWebViewWith:for:windowFeatures:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/webView(_:createWebViewWith:for:windowFeatures:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"text":"createWebViewWith","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKWebViewConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebViewConfiguration"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"navigationAction","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKNavigationAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"text":", ","kind":"text"},{"text":"windowFeatures","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKWindowFeatures","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWindowFeatures"},{"text":") -> ","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController","navigatorTitle":[{"kind":"identifier","text":"ApphudPaywallScreenController"}],"url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller","kind":"symbol","abstract":[],"title":"ApphudPaywallScreenController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPaywallScreenController"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/webView(_:createWebViewWith:for:windowFeatures:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/webView(_:createWebViewWith:for:windowFeatures:)","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/webview(_:createwebviewwith:for:windowfeatures:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"webView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createWebViewWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebViewConfiguration","preciseIdentifier":"c:objc(cs)WKWebViewConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"windowFeatures"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWindowFeatures","text":"WKWindowFeatures"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:"}],"title":"webView(_:createWebViewWith:for:windowFeatures:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"webView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":" "},{"kind":"identifier","text":"createWebViewWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebViewConfiguration","text":"WKWebViewConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"forNavigationAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigationAction","text":"WKNavigationAction"},{"text":" *) ","kind":"text"},{"text":"navigationAction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"windowFeatures:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWindowFeatures","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWindowFeatures"},{"text":" *) ","kind":"text"},{"text":"windowFeatures","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"ApphudPaywallScreenController","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/title"},{"op":"replace","value":[{"text":"ApphudPaywallScreenController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ApphudPaywallScreenController"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/navigatorTitle"},{"op":"replace","value":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController~1webView(_:createWebViewWith:for:windowFeatures:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController~1webView(_:createWebViewWith:for:windowFeatures:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}