{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController"]]},"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/webView(_:createWebViewWith:for:windowFeatures:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/WKUIDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","title":"WKUIDelegate Implementations","role":"collectionGroup","modules":[{"name":"ApphudSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/wkuidelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/wkuidelegate-implementations"]}],"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","role":"collection","url":"\/documentation\/apphudsdk","abstract":[{"type":"text","text":"Apphud is an all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams make the right decisions based on data and tools."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudPaywallScreenController"}],"url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller","kind":"symbol","title":"ApphudPaywallScreenController","role":"symbol","navigatorTitle":[{"text":"ApphudPaywallScreenController","kind":"identifier"}],"type":"topic","abstract":[]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywallScreenController/webView(_:createWebViewWith:for:windowFeatures:)":{"title":"webView(_:createWebViewWith:for:windowFeatures:)","abstract":[],"navigatorTitle":[{"text":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/webView(_:createWebViewWith:for:windowFeatures:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/apphudsdk\/apphudpaywallscreencontroller\/webview(_:createwebviewwith:for:windowfeatures:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"createWebViewWith"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WKWebViewConfiguration","preciseIdentifier":"c:objc(cs)WKWebViewConfiguration"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKNavigationAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"windowFeatures"},{"kind":"text","text":": "},{"text":"WKWindowFeatures","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWindowFeatures"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywallScreenController\/webView(_:createWebViewWith:for:windowFeatures:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/title","value":"ApphudPaywallScreenController"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudPaywallScreenController"}]},{"op":"replace","value":[{"text":"ApphudPaywallScreenController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController\/navigatorTitle"},{"value":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController~1webView(_:createWebViewWith:for:windowFeatures:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywallScreenController~1webView(_:createWebViewWith:for:windowFeatures:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}