{"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidObservePurchase(result:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate"]]},"metadata":{"externalID":"s:9ApphudSDK0A8DelegateP24apphudDidObservePurchase6resultSbAA0aG6ResultC_tF","required":true,"platforms":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false,"introducedAt":"10.14.4"}],"modules":[{"name":"ApphudSDK"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apphudDidObservePurchase"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"text":"ApphudPurchaseResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Method","role":"symbol","title":"apphudDidObservePurchase(result:)"},"seeAlsoSections":[{"title":"ApphudDelegate main methods","generated":true,"anchor":"ApphudDelegate-main-methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudSubscriptionsUpdated(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudNonRenewingPurchasesUpdated(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidChangeUserID(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/userDidLoad(user:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/paywallsDidFullyLoad(paywalls:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/placementsDidFullyLoad(placements:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudShouldStartAppStoreDirectPurchase(_:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/handleDeferredTransaction(transaction:)"]}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/apphuddidobservepurchase(result:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Called when the Apphud SDK detects a purchase made outside of its standard purchase methods. This is particularly useful for handling purchases made with Promo Codes."}],"sections":[],"kind":"symbol","defaultImplementationsSections":[{"title":"ApphudDelegate Implementations","anchor":"ApphudDelegate-Implementations","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidObservePurchase(result:)-57k7y"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"apphudDidObservePurchase","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"name":"result","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"code":"ApphudPurchaseResult","type":"codeVoice"},{"type":"text","text":" object containing details of the purchase."}]}]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if you want the Apphud SDK to finish the transaction. If you return "},{"type":"codeVoice","code":"false"},{"type":"text","text":", you must manually call "},{"type":"codeVoice","code":"SKPaymentQueue.default().finishTransaction(transaction)"},{"type":"text","text":" on the transaction."}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"This method allows you to intercept and process purchases that occur through mechanisms like promo code redemption.","type":"text"}]}],"style":"note"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudSubscriptionsUpdated(_:)":{"abstract":[{"text":"Called when there is an update to the user’s subscriptions. This includes new purchases, updates to existing subscriptions (e.g., status change from ","type":"text"},{"code":"trial","type":"codeVoice"},{"text":" to ","type":"text"},{"code":"expired","type":"codeVoice"},{"text":", or change in ","type":"text"},{"code":"isAutorenewEnabled","type":"codeVoice"},{"text":").","type":"text"}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudSubscriptionsUpdated"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ApphudSubscription","preciseIdentifier":"s:9ApphudSDK0A12SubscriptionC"},{"kind":"text","text":"])"}],"defaultImplementations":1,"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudsubscriptionsupdated(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudSubscriptionsUpdated(_:)","title":"apphudSubscriptionsUpdated(_:)","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudDidObservePurchase(result:)":{"abstract":[{"type":"text","text":"Called when the Apphud SDK detects a purchase made outside of its standard purchase methods. This is particularly useful for handling purchases made with Promo Codes."}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apphudDidObservePurchase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"result","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","text":"ApphudPurchaseResult"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"defaultImplementations":1,"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphuddidobservepurchase(result:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidObservePurchase(result:)","title":"apphudDidObservePurchase(result:)","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/paywallsDidFullyLoad(paywalls:)":{"kind":"symbol","role":"symbol","defaultImplementations":1,"abstract":[{"text":"Called when paywalls are fully loaded with their associated ","type":"text"},{"code":"SKProducts","type":"codeVoice"},{"text":". This method serves a similar purpose to the ","type":"text"},{"code":"Apphud.paywallsDidLoadCallback {}","type":"codeVoice"},{"text":" method.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/paywallsDidFullyLoad(paywalls:)","title":"paywallsDidFullyLoad(paywalls:)","url":"\/documentation\/apphudsdk\/apphuddelegate\/paywallsdidfullyload(paywalls:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paywallsDidFullyLoad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paywalls"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":"])","kind":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","navigatorTitle":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult","kind":"symbol","abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"title":"ApphudPurchaseResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPurchaseResult"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudNonRenewingPurchasesUpdated(_:)":{"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudnonrenewingpurchasesupdated(_:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Called when there is a change in the user’s non-renewing purchases. This can occur when a new purchase is made or if a purchase is refunded."}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A19NonRenewingPurchaseC","text":"ApphudNonRenewingPurchase"},{"kind":"text","text":"])"}],"defaultImplementations":1,"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudNonRenewingPurchasesUpdated(_:)","title":"apphudNonRenewingPurchasesUpdated(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/placementsDidFullyLoad(placements:)":{"title":"placementsDidFullyLoad(placements:)","kind":"symbol","role":"symbol","abstract":[{"text":"Called when placements are fully loaded with their associated Paywalls and StoreKit products.","type":"text"}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"placementsDidFullyLoad"},{"kind":"text","text":"("},{"text":"placements","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A9PlacementC","text":"ApphudPlacement","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"defaultImplementations":1,"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/placementsDidFullyLoad(placements:)","url":"\/documentation\/apphudsdk\/apphuddelegate\/placementsdidfullyload(placements:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/userDidLoad(user:)":{"kind":"symbol","role":"symbol","defaultImplementations":1,"abstract":[{"type":"text","text":"Called once per app lifecycle when the user is registered in Apphud or retrieved from cache. The "},{"code":"user","type":"codeVoice"},{"type":"text","text":" parameter contains a record of all purchases tracked by Apphud and associated raw placements and paywalls for that user."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/userDidLoad(user:)","title":"userDidLoad(user:)","url":"\/documentation\/apphudsdk\/apphuddelegate\/userdidload(user:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userDidLoad","kind":"identifier"},{"text":"(","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ApphudUser","preciseIdentifier":"s:9ApphudSDK0A4UserV","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudDidObservePurchase(result:)-57k7y":{"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphuddidobservepurchase(result:)-57k7y","kind":"symbol","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudDidObservePurchase"},{"kind":"text","text":"("},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","text":"ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidObservePurchase(result:)-57k7y","title":"apphudDidObservePurchase(result:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudShouldStartAppStoreDirectPurchase(_:)":{"abstract":[{"type":"text","text":"Implements the mechanism for handling In-App Purchases initiated directly from the App Store page."}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct"},{"text":") -> ((","kind":"text"},{"text":"ApphudPurchaseResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"defaultImplementations":1,"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudshouldstartappstoredirectpurchase(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudShouldStartAppStoreDirectPurchase(_:)","title":"apphudShouldStartAppStoreDirectPurchase(_:)","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/handleDeferredTransaction(transaction:)":{"kind":"symbol","role":"symbol","defaultImplementations":1,"abstract":[{"type":"text","text":"Called when the Apphud SDK detects a deferred or interrupted purchase. This can happen in scenarios like required Strong Customer Authentication (SCA), parental control approvals, etc."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/handleDeferredTransaction(transaction:)","type":"topic","title":"handleDeferredTransaction(transaction:)","url":"\/documentation\/apphudsdk\/apphuddelegate\/handledeferredtransaction(transaction:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleDeferredTransaction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"transaction","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKPaymentTransaction","kind":"typeIdentifier","text":"SKPaymentTransaction"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate":{"url":"\/documentation\/apphudsdk\/apphuddelegate","title":"ApphudDelegate","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate","abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the user and the state of his subscriptions."}],"navigatorTitle":[{"text":"ApphudDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ApphudDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudDidChangeUserID(_:)":{"required":true,"abstract":[{"type":"text","text":"Called when the user’s ID in Apphud changes. This is important for maintaining continuity in integrations with analytics services."}],"kind":"symbol","role":"symbol","url":"\/documentation\/apphudsdk\/apphuddelegate\/apphuddidchangeuserid(_:)","title":"apphudDidChangeUserID(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudDidChangeUserID"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"defaultImplementations":1,"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidChangeUserID(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title","value":"ApphudPurchaseResult"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments","value":[{"text":"ApphudPurchaseResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/navigatorTitle","value":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"op":"replace"}]}]}