{"metadata":{"modules":[{"name":"ApphudSDK"}],"symbolKind":"method","title":"apphudShouldStartAppStoreDirectPurchase(_:)","extendedModule":"ApphudSDK","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier","text":"SKProduct"},{"kind":"text","text":") -> (("},{"text":"ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"role":"symbol","roleHeading":"Instance Method","externalID":"s:9ApphudSDK0A8DelegatePAAE39apphudShouldStartAppStoreDirectPurchaseyyAA0aJ6ResultCcSgSo9SKProductCF","platforms":[{"beta":false,"deprecated":false,"introducedAt":"10.14.4","name":"macOS","unavailable":false}]},"variants":[{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/apphudshouldstartappstoredirectpurchase(_:)-2mv8h"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"ApphudDelegate.apphudShouldStartAppStoreDirectPurchase(_:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudShouldStartAppStoreDirectPurchase(_:)-2mv8h"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"product"},{"kind":"text","text":": "},{"text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier"},{"kind":"text","text":") -> (("},{"kind":"typeIdentifier","text":"ApphudPurchaseResult","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate":{"url":"\/documentation\/apphudsdk\/apphuddelegate","title":"ApphudDelegate","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate","abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the user and the state of his subscriptions."}],"navigatorTitle":[{"text":"ApphudDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ApphudDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","navigatorTitle":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult","kind":"symbol","abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"title":"ApphudPurchaseResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPurchaseResult"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudShouldStartAppStoreDirectPurchase(_:)-2mv8h":{"role":"symbol","url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudshouldstartappstoredirectpurchase(_:)-2mv8h","title":"apphudShouldStartAppStoreDirectPurchase(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apphudShouldStartAppStoreDirectPurchase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":") -> ((","kind":"text"},{"text":"ApphudPurchaseResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudShouldStartAppStoreDirectPurchase(_:)-2mv8h","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title","op":"replace","value":"ApphudPurchaseResult"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments","op":"replace","value":[{"text":"ApphudPurchaseResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ApphudPurchaseResult"}]}]}]}