{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudDidChangeUserID"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Please read following if you implement integrations: "},{"type":"codeVoice","code":"https:\/\/docs.apphud.com\/docs\/initialization"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This delegate method is called in 2 cases:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When Apphud has merged two users into a single user (for example, after user has restored purchases from his another device)."},{"type":"text","text":" "},{"type":"text","text":"Merging users is done in the following way: after App Store receipt has been sent to Apphud, server tries to find the same receipt in the database."},{"type":"text","text":" "},{"type":"text","text":"If the same App Store receipt has been found, Apphud merges two users into a single user with two devices and then returns an original userID."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Note"}]},{"type":"text","text":": Only subscriber devices are mergable. If non-premium user uses the app from two different devices, Apphud won’t be able to know that these devices belong to the same user."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"After manual call of "},{"type":"codeVoice","code":"updateUserID(userID : String)"},{"type":"text","text":" method."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/apphuddidchangeuserid(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/apphuddidchangeuserid(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidChangeUserID(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when user ID has been changed. Use this if you implement integrations with Analytics services."}],"kind":"symbol","metadata":{"modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"apphudDidChangeUserID:"}],"role":"symbol","title":"apphudDidChangeUserID(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudDidChangeUserID"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(pl)ApphudDelegate(im)apphudDidChangeUserID:","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.14.4","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate":{"role":"symbol","title":"ApphudDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudDelegate"}],"abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the user and the state of his subscriptions."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudDelegate"}],"url":"\/documentation\/apphudsdk\/apphuddelegate"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudDidChangeUserID(_:)":{"navigatorTitle":[{"kind":"identifier","text":"apphudDidChangeUserID:"}],"role":"symbol","title":"apphudDidChangeUserID(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudDidChangeUserID"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when user ID has been changed. Use this if you implement integrations with Analytics services."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidChangeUserID(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/apphudsdk\/apphuddelegate\/apphuddidchangeuserid(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"apphudDidChangeUserID:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudDidChangeUserID:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"apphudDidChangeUserID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userID"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate\/title","value":"ApphudDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate\/fragments","value":[{"kind":"identifier","text":"ApphudDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudDidChangeUserID(_:)\/title","value":"apphudDidChangeUserID:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudDidChangeUserID(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudDidChangeUserID:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}