{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"product"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":") -> (("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","text":"ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You must return a callback block which will be called when a payment is finished. If you don’t implement this method or return "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" then a payment will not start; you can also save the product and return "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" to initiate a payment later by yourself. Read Apple documentation for details: https:\/\/developer.apple.com\/documentation\/storekit\/in-app_purchase\/promoting_in-app_purchases"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/apphudshouldstartappstoredirectpurchase(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/apphudshouldstartappstoredirectpurchase(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudShouldStartAppStoreDirectPurchase(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Implements mechanism of purchasing In-App Purchase initiated directly from the App Store page."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase:"}],"role":"symbol","title":"apphudShouldStartAppStoreDirectPurchase(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":") -> (("},{"kind":"typeIdentifier","text":"ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(pl)ApphudDelegate(im)apphudShouldStartAppStoreDirectPurchase:","modules":[{"name":"ApphudSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.14.4","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate":{"role":"symbol","title":"ApphudDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudDelegate"}],"abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the user and the state of his subscriptions."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudDelegate"}],"url":"\/documentation\/apphudsdk\/apphuddelegate"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudShouldStartAppStoreDirectPurchase(_:)":{"role":"symbol","title":"apphudShouldStartAppStoreDirectPurchase(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":") -> (("},{"kind":"typeIdentifier","text":"ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Implements mechanism of purchasing In-App Purchase initiated directly from the App Store page."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudShouldStartAppStoreDirectPurchase(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase:"}],"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudshouldstartappstoredirectpurchase(_:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPurchaseResult":{"role":"symbol","title":"ApphudPurchaseResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPurchaseResult"}],"abstract":[{"type":"text","text":"General class that is returned in purchase block."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPurchaseResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudPurchaseResult"}],"url":"\/documentation\/apphudsdk\/apphudpurchaseresult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"apphudShouldStartAppStoreDirectPurchase:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void (^)(ApphudPurchaseResult *)","preciseIdentifier":"c:BFv(#*$@M@ApphudSDK@objc(cs)ApphudPurchaseResult)"},{"kind":"text","text":") "},{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"product"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate\/title","value":"ApphudDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate\/fragments","value":[{"kind":"identifier","text":"ApphudDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudShouldStartAppStoreDirectPurchase(_:)\/title","value":"apphudShouldStartAppStoreDirectPurchase:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudShouldStartAppStoreDirectPurchase(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/title","value":"ApphudPurchaseResult"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPurchaseResult\/fragments","value":[{"kind":"identifier","text":"ApphudPurchaseResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}