{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudSubscriptionsUpdated"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"subscriptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscription","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudSubscription","text":"ApphudSubscription"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is called when subscription is purchased or updated (for example, status changed from "},{"type":"codeVoice","code":"trial"},{"type":"text","text":" to "},{"type":"codeVoice","code":"expired"},{"type":"text","text":" or "},{"type":"codeVoice","code":"isAutorenewEnabled"},{"type":"text","text":" changed to "},{"type":"codeVoice","code":"false"},{"type":"text","text":"). SDK also checks for subscription updates when app becomes active."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/apphudsubscriptionsupdated(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/apphudsubscriptionsupdated(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudSubscriptionsUpdated(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns array of subscriptions that user ever purchased. Empty array means user never purchased a subscription. If you have just one subscription group in your app, you will always receive just one subscription in an array."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"apphudSubscriptionsUpdated:"}],"role":"symbol","title":"apphudSubscriptionsUpdated(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudSubscriptionsUpdated"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ApphudSubscription","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudSubscription"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(pl)ApphudDelegate(im)apphudSubscriptionsUpdated:","modules":[{"name":"ApphudSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.14.4","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate":{"role":"symbol","title":"ApphudDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudDelegate"}],"abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the user and the state of his subscriptions."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudDelegate"}],"url":"\/documentation\/apphudsdk\/apphuddelegate"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudSubscription":{"role":"symbol","title":"ApphudSubscription","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudSubscription"}],"abstract":[{"type":"text","text":"Custom Apphud class containing all information about customer subscription."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudSubscription"}],"url":"\/documentation\/apphudsdk\/apphudsubscription"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudSubscriptionsUpdated(_:)":{"role":"symbol","title":"apphudSubscriptionsUpdated(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudSubscriptionsUpdated"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ApphudSubscription","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudSubscription"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Returns array of subscriptions that user ever purchased. Empty array means user never purchased a subscription. If you have just one subscription group in your app, you will always receive just one subscription in an array."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudSubscriptionsUpdated(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"apphudSubscriptionsUpdated:"}],"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudsubscriptionsupdated(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"apphudSubscriptionsUpdated:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudSubscriptionsUpdated:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"apphudSubscriptionsUpdated:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<ApphudSubscription *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"subscriptions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate\/title","value":"ApphudDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate\/fragments","value":[{"kind":"identifier","text":"ApphudDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscription\/title","value":"ApphudSubscription"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscription\/fragments","value":[{"kind":"identifier","text":"ApphudSubscription"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudSubscriptionsUpdated(_:)\/title","value":"apphudSubscriptionsUpdated:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudSubscriptionsUpdated(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudSubscriptionsUpdated:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}