{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"purchases"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudNonRenewingPurchase","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudNonRenewingPurchase","text":"ApphudNonRenewingPurchase"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/apphudnonrenewingpurchasesupdated(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/apphudnonrenewingpurchasesupdated(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudNonRenewingPurchasesUpdated(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when any of non renewing purchases changes. Called when purchase is made or has been refunded."}],"kind":"symbol","metadata":{"modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated:"}],"role":"symbol","title":"apphudNonRenewingPurchasesUpdated(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ApphudNonRenewingPurchase","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudNonRenewingPurchase"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(pl)ApphudDelegate(im)apphudNonRenewingPurchasesUpdated:","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.14.4","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudNonRenewingPurchase":{"role":"symbol","title":"ApphudNonRenewingPurchase","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudNonRenewingPurchase"}],"abstract":[{"type":"text","text":"Custom Apphud class containing all information about customer non-renewing purchase"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudNonRenewingPurchase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudNonRenewingPurchase"}],"url":"\/documentation\/apphudsdk\/apphudnonrenewingpurchase"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate":{"role":"symbol","title":"ApphudDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudDelegate"}],"abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the user and the state of his subscriptions."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudDelegate"}],"url":"\/documentation\/apphudsdk\/apphuddelegate"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudNonRenewingPurchasesUpdated(_:)":{"navigatorTitle":[{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated:"}],"role":"symbol","title":"apphudNonRenewingPurchasesUpdated(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ApphudNonRenewingPurchase","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudNonRenewingPurchase"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Called when any of non renewing purchases changes. Called when purchase is made or has been refunded."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudNonRenewingPurchasesUpdated(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudnonrenewingpurchasesupdated(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"apphudNonRenewingPurchasesUpdated:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<ApphudNonRenewingPurchase *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"purchases"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudNonRenewingPurchase\/title","value":"ApphudNonRenewingPurchase"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudNonRenewingPurchase\/fragments","value":[{"kind":"identifier","text":"ApphudNonRenewingPurchase"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate\/title","value":"ApphudDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate\/fragments","value":[{"kind":"identifier","text":"ApphudDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudNonRenewingPurchasesUpdated(_:)\/title","value":"apphudNonRenewingPurchasesUpdated:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1apphudNonRenewingPurchasesUpdated(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}