{"metadata":{"role":"symbol","title":"paywallsDidFullyLoad(paywalls:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paywallsDidFullyLoad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paywalls"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"extendedModule":"ApphudSDK","platforms":[{"unavailable":false,"name":"macOS","beta":false,"introducedAt":"10.14.4","deprecated":false}],"externalID":"s:9ApphudSDK0A8DelegatePAAE20paywallsDidFullyLoad0D0ySayAA0A7PaywallCG_tF","symbolKind":"method","modules":[{"name":"ApphudSDK"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ApphudDelegate.paywallsDidFullyLoad(paywalls:)"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/paywallsDidFullyLoad(paywalls:)-3kcab","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paywallsDidFullyLoad","kind":"identifier"},{"text":"(","kind":"text"},{"text":"paywalls","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ApphudPaywall","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":"])","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphuddelegate\/paywallsdidfullyload(paywalls:)-3kcab"]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/paywallsDidFullyLoad(paywalls:)-3kcab":{"kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"paywallsDidFullyLoad(paywalls:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/paywallsDidFullyLoad(paywalls:)-3kcab","url":"\/documentation\/apphudsdk\/apphuddelegate\/paywallsdidfullyload(paywalls:)-3kcab","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paywallsDidFullyLoad"},{"kind":"text","text":"("},{"text":"paywalls","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"ApphudPaywall","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"text":"])","kind":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate":{"url":"\/documentation\/apphudsdk\/apphuddelegate","title":"ApphudDelegate","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate","abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the user and the state of his subscriptions."}],"navigatorTitle":[{"text":"ApphudDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ApphudDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","kind":"symbol","abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"navigatorTitle":[{"text":"ApphudPaywall","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphudpaywall","title":"ApphudPaywall","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudPaywall","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","value":"ApphudPaywall","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","value":[{"text":"ApphudPaywall","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/navigatorTitle","value":[{"text":"ApphudPaywall","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}