{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paywallsDidFullyLoad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paywalls"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier","text":"ApphudPaywall"},{"kind":"text","text":"])"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"type":"codeVoice","code":"ApphudPaywall"},{"type":"text","text":" objects, now fully loaded with their respective "},{"type":"codeVoice","code":"SKProducts"},{"type":"text","text":"."}]}],"name":"paywalls"}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"Use this method to update your UI or logic once all paywall data, including "},{"type":"codeVoice","code":"SKProduct"},{"text":" details, are fully loaded.","type":"text"}],"type":"paragraph"}],"name":"Note","style":"note"}],"kind":"content"}],"abstract":[{"type":"text","text":"Called when paywalls are fully loaded with their associated "},{"code":"SKProducts","type":"codeVoice"},{"type":"text","text":". This method serves a similar purpose to the "},{"code":"Apphud.paywallsDidLoadCallback {}","type":"codeVoice"},{"type":"text","text":" method."}],"defaultImplementationsSections":[{"anchor":"ApphudDelegate-Implementations","title":"ApphudDelegate Implementations","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/paywallsDidFullyLoad(paywalls:)-3kcab"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphuddelegate\/paywallsdidfullyload(paywalls:)-6z8g8"]}],"seeAlsoSections":[{"anchor":"ApphudDelegate-main-methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudSubscriptionsUpdated(_:)-3dnhb","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudNonRenewingPurchasesUpdated(_:)-7sfe7","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidChangeUserID(_:)-1dyji","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/userDidLoad(user:)-4qpvb","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/placementsDidFullyLoad(placements:)-27ou4","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudShouldStartAppStoreDirectPurchase(_:)-2ek16","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidObservePurchase(result:)-1ym71","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/handleDeferredTransaction(transaction:)-856ot"],"generated":true,"title":"ApphudDelegate main methods"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/paywallsDidFullyLoad(paywalls:)-6z8g8","interfaceLanguage":"swift"},"metadata":{"required":true,"externalID":"s:9ApphudSDK0A8DelegateP20paywallsDidFullyLoad0D0ySayAA0A7PaywallCG_tF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paywallsDidFullyLoad","kind":"identifier"},{"kind":"text","text":"("},{"text":"paywalls","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall"},{"text":"])","kind":"text"}],"roleHeading":"Instance Method","platforms":[{"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.14.4","beta":false}],"modules":[{"name":"ApphudSDK"}],"role":"symbol","title":"paywallsDidFullyLoad(paywalls:)"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"navigatorTitle":[{"kind":"identifier","text":"ApphudPaywall"}],"url":"\/documentation\/apphudsdk\/apphudpaywall","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ApphudPaywall","kind":"identifier"}],"abstract":[{"text":"An object associated with purchases container (Paywall).","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","kind":"symbol","title":"ApphudPaywall","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudSubscriptionsUpdated(_:)-3dnhb":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudSubscriptionsUpdated(_:)-3dnhb","url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudsubscriptionsupdated(_:)-3dnhb","required":true,"type":"topic","defaultImplementations":1,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudSubscriptionsUpdated","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:9ApphudSDK0A12SubscriptionC","kind":"typeIdentifier","text":"ApphudSubscription"},{"text":"])","kind":"text"}],"title":"apphudSubscriptionsUpdated(_:)","kind":"symbol","abstract":[{"type":"text","text":"Called when there is an update to the user’s subscriptions. This includes new purchases, updates to existing subscriptions (e.g., status change from "},{"type":"codeVoice","code":"trial"},{"type":"text","text":" to "},{"code":"expired","type":"codeVoice"},{"type":"text","text":", or change in "},{"type":"codeVoice","code":"isAutorenewEnabled"},{"text":").","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/handleDeferredTransaction(transaction:)-856ot":{"role":"symbol","type":"topic","title":"handleDeferredTransaction(transaction:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleDeferredTransaction"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"transaction"},{"kind":"text","text":": "},{"text":"SKPaymentTransaction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKPaymentTransaction"},{"text":")","kind":"text"}],"defaultImplementations":1,"required":true,"url":"\/documentation\/apphudsdk\/apphuddelegate\/handledeferredtransaction(transaction:)-856ot","abstract":[{"type":"text","text":"Called when the Apphud SDK detects a deferred or interrupted purchase. This can happen in scenarios like required Strong Customer Authentication (SCA), parental control approvals, etc."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/handleDeferredTransaction(transaction:)-856ot","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/placementsDidFullyLoad(placements:)-27ou4":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/placementsDidFullyLoad(placements:)-27ou4","url":"\/documentation\/apphudsdk\/apphuddelegate\/placementsdidfullyload(placements:)-27ou4","required":true,"type":"topic","defaultImplementations":1,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"placementsDidFullyLoad","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"placements"},{"text":": [","kind":"text"},{"text":"ApphudPlacement","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A9PlacementC"},{"kind":"text","text":"])"}],"title":"placementsDidFullyLoad(placements:)","kind":"symbol","abstract":[{"text":"Called when placements are fully loaded with their associated Paywalls and StoreKit products.","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/paywallsDidFullyLoad(paywalls:)-6z8g8":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/paywallsDidFullyLoad(paywalls:)-6z8g8","url":"\/documentation\/apphudsdk\/apphuddelegate\/paywallsdidfullyload(paywalls:)-6z8g8","required":true,"type":"topic","defaultImplementations":1,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paywallsDidFullyLoad","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paywalls"},{"text":": [","kind":"text"},{"text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"paywallsDidFullyLoad(paywalls:)","kind":"symbol","abstract":[{"text":"Called when paywalls are fully loaded with their associated ","type":"text"},{"type":"codeVoice","code":"SKProducts"},{"text":". This method serves a similar purpose to the ","type":"text"},{"type":"codeVoice","code":"Apphud.paywallsDidLoadCallback {}"},{"text":" method.","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudShouldStartAppStoreDirectPurchase(_:)-2ek16":{"role":"symbol","type":"topic","title":"apphudShouldStartAppStoreDirectPurchase(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudShouldStartAppStoreDirectPurchase"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct","kind":"typeIdentifier"},{"text":") -> ((","kind":"text"},{"text":"ApphudPurchaseResult","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"defaultImplementations":1,"required":true,"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudshouldstartappstoredirectpurchase(_:)-2ek16","abstract":[{"text":"Implements the mechanism for handling In-App Purchases initiated directly from the App Store page.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudShouldStartAppStoreDirectPurchase(_:)-2ek16","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/paywallsDidFullyLoad(paywalls:)-3kcab":{"kind":"symbol","title":"paywallsDidFullyLoad(paywalls:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/paywallsDidFullyLoad(paywalls:)-3kcab","abstract":[{"text":"Called when paywalls are fully loaded with their associated ","type":"text"},{"type":"codeVoice","code":"SKProducts"},{"type":"text","text":". This method serves a similar purpose to the "},{"code":"Apphud.paywallsDidLoadCallback {}","type":"codeVoice"},{"type":"text","text":" method."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paywallsDidFullyLoad","kind":"identifier"},{"kind":"text","text":"("},{"text":"paywalls","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall"},{"text":"])","kind":"text"}],"type":"topic","url":"\/documentation\/apphudsdk\/apphuddelegate\/paywallsdidfullyload(paywalls:)-3kcab","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudDidChangeUserID(_:)-1dyji":{"role":"symbol","type":"topic","title":"apphudDidChangeUserID(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudDidChangeUserID"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"defaultImplementations":1,"required":true,"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphuddidchangeuserid(_:)-1dyji","abstract":[{"text":"Called when the user’s ID in Apphud changes. This is important for maintaining continuity in integrations with analytics services.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidChangeUserID(_:)-1dyji","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudDidObservePurchase(result:)-1ym71":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudDidObservePurchase(result:)-1ym71","abstract":[{"text":"Called when the Apphud SDK detects a purchase made outside of its standard purchase methods. This is particularly useful for handling purchases made with Promo Codes.","type":"text"}],"defaultImplementations":1,"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphuddidobservepurchase(result:)-1ym71","title":"apphudDidObservePurchase(result:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apphudDidObservePurchase"},{"text":"(","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPurchaseResult","text":"ApphudPurchaseResult"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"required":true},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/userDidLoad(user:)-4qpvb":{"role":"symbol","type":"topic","title":"userDidLoad(user:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidLoad"},{"text":"(","kind":"text"},{"text":"user","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ApphudUser","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A4UserV"},{"text":")","kind":"text"}],"defaultImplementations":1,"required":true,"url":"\/documentation\/apphudsdk\/apphuddelegate\/userdidload(user:)-4qpvb","abstract":[{"text":"Called once per app lifecycle when the user is registered in Apphud or retrieved from cache. The ","type":"text"},{"type":"codeVoice","code":"user"},{"text":" parameter contains a record of all purchases tracked by Apphud and associated raw placements and paywalls for that user.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/userDidLoad(user:)-4qpvb","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","role":"collection","url":"\/documentation\/apphudsdk","abstract":[{"type":"text","text":"Apphud is an all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams make the right decisions based on data and tools."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/apphudNonRenewingPurchasesUpdated(_:)-7sfe7":{"role":"symbol","type":"topic","title":"apphudNonRenewingPurchasesUpdated(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apphudNonRenewingPurchasesUpdated"},{"kind":"text","text":"(["},{"text":"ApphudNonRenewingPurchase","kind":"typeIdentifier","preciseIdentifier":"s:9ApphudSDK0A19NonRenewingPurchaseC"},{"text":"])","kind":"text"}],"defaultImplementations":1,"required":true,"url":"\/documentation\/apphudsdk\/apphuddelegate\/apphudnonrenewingpurchasesupdated(_:)-7sfe7","abstract":[{"text":"Called when there is a change in the user’s non-renewing purchases. This can occur when a new purchase is made or if a purchase is refunded.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/apphudNonRenewingPurchasesUpdated(_:)-7sfe7","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","op":"replace","value":"ApphudPaywall"},{"value":[{"text":"ApphudPaywall","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments"},{"value":[{"text":"ApphudPaywall","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/navigatorTitle","op":"replace"}]}]}