{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidLoad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawPaywalls"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall","text":"ApphudPaywall"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"However, if using A\/B Testing, "},{"type":"codeVoice","code":"rawPaywalls"},{"type":"text","text":" can be used to fetch "},{"type":"codeVoice","code":"experimentName"},{"type":"text","text":", "},{"type":"codeVoice","code":"variationName"},{"type":"text","text":" or other parameters like "},{"type":"codeVoice","code":"json"},{"type":"text","text":" from your experimental paywall."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/userdidload(rawpaywalls:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphuddelegate\/userdidload(rawpaywalls:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/userDidLoad(rawPaywalls:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when user is registered in Apphud [or used from cache]. This method is called once per app lifecycle."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"rawPaywalls"},{"type":"text","text":" array may not yet have "},{"type":"codeVoice","code":"SKProducts"},{"type":"text","text":", so this method should not be used for paywalls management."}],"kind":"symbol","metadata":{"modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"userDidLoadWithRawPaywalls:"}],"role":"symbol","title":"userDidLoad(rawPaywalls:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidLoad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawPaywalls"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(pl)ApphudDelegate(im)userDidLoadWithRawPaywalls:","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.14.4","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate":{"role":"symbol","title":"ApphudDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudDelegate"}],"abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the user and the state of his subscriptions."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudDelegate"}],"url":"\/documentation\/apphudsdk\/apphuddelegate"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudDelegate/userDidLoad(rawPaywalls:)":{"navigatorTitle":[{"kind":"identifier","text":"userDidLoadWithRawPaywalls:"}],"role":"symbol","title":"userDidLoad(rawPaywalls:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidLoad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawPaywalls"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ApphudPaywall","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudPaywall"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Called when user is registered in Apphud [or used from cache]. This method is called once per app lifecycle."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"rawPaywalls"},{"type":"text","text":" array may not yet have "},{"type":"codeVoice","code":"SKProducts"},{"type":"text","text":", so this method should not be used for paywalls management."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudDelegate\/userDidLoad(rawPaywalls:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/apphudsdk\/apphuddelegate\/userdidload(rawpaywalls:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[{"type":"text","text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudPaywall":{"role":"symbol","title":"ApphudPaywall","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudPaywall"}],"abstract":[{"type":"text","text":"An object associated with purchases container (Paywall)."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudPaywall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudPaywall"}],"url":"\/documentation\/apphudsdk\/apphudpaywall"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userDidLoadWithRawPaywalls:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidLoadWithRawPaywalls:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userDidLoadWithRawPaywalls:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<ApphudPaywall *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"rawPaywalls"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate\/title","value":"ApphudDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate\/fragments","value":[{"kind":"identifier","text":"ApphudDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1userDidLoad(rawPaywalls:)\/title","value":"userDidLoadWithRawPaywalls:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudDelegate~1userDidLoad(rawPaywalls:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidLoadWithRawPaywalls:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/title","value":"ApphudPaywall"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudPaywall\/fragments","value":[{"kind":"identifier","text":"ApphudPaywall"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}