{"abstract":[{"type":"text","text":"You can return "},{"code":"false","type":"codeVoice"},{"type":"text","text":" to ignore this rule. You should only do this if you want to handle your rules by yourself. Default implementation is "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate"]]},"metadata":{"modules":[{"name":"ApphudSDK"}],"symbolKind":"method","title":"apphudShouldPerformRule(rule:)","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apphudShouldPerformRule"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rule"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudRule","text":"ApphudRule","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"apphudShouldPerformRuleWithRule:","kind":"identifier"}],"externalID":"c:@M@ApphudSDK@objc(pl)ApphudUIDelegate(im)apphudShouldPerformRuleWithRule:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudshouldperformrule(rule:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudshouldperformrule(rule:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudShouldPerformRule"},{"kind":"text","text":"("},{"text":"rule","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ApphudRule","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudRule","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudRule","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldPerformRule(rule:)"},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate":{"url":"\/documentation\/apphudsdk\/apphuduidelegate","title":"ApphudUIDelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudUIDelegate"}],"abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the Rules state and custom Rules view presentation"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudUIDelegate"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudShouldPerformRule(rule:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldPerformRule(rule:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apphudShouldPerformRule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rule"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudRule","text":"ApphudRule"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"apphudShouldPerformRuleWithRule:","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudshouldperformrule(rule:)","title":"apphudShouldPerformRule(rule:)","abstract":[{"type":"text","text":"You can return "},{"code":"false","type":"codeVoice"},{"text":" to ignore this rule. You should only do this if you want to handle your rules by yourself. Default implementation is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudRule":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudRule","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudRule","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudRule"}],"url":"\/documentation\/apphudsdk\/apphudrule","title":"ApphudRule","abstract":[{"text":"An object containing all incoming Rule information.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"apphudShouldPerformRuleWithRule:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"apphudShouldPerformRuleWithRule:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"apphudShouldPerformRuleWithRule:"},{"text":"(","kind":"text"},{"text":"ApphudRule","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudRule","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudRule","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rule","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ApphudUIDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/title"},{"value":[{"kind":"identifier","text":"ApphudUIDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudShouldPerformRule(rule:)\/title","value":"apphudShouldPerformRuleWithRule:"},{"value":[{"text":"- ","kind":"text"},{"text":"apphudShouldPerformRuleWithRule:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudShouldPerformRule(rule:)\/fragments"},{"value":"ApphudRule","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudRule\/title","op":"replace"},{"value":[{"text":"ApphudRule","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudRule\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}