{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudParentViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Note"}]},{"type":"text","text":": This delegate method is recommended for implementation when you have multiple windows in your app, because Apphud SDK may have issues while presenting screens in this case."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudparentviewcontroller(controller:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudparentviewcontroller(controller:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudParentViewController(controller:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Return "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" instance from which you want to present given Apphud controller. If you don’t implement this method, then top visible viewcontroller from key window will be used."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudParentViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"apphudParentViewController(controller:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ApphudSDK@objc(pl)ApphudUIDelegate(im)apphudParentViewControllerWithController:","modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"apphudParentViewControllerWithController:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate":{"role":"symbol","title":"ApphudUIDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudUIDelegate"}],"abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the Rules state and custom Rules view presentation"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudUIDelegate"}],"url":"\/documentation\/apphudsdk\/apphuduidelegate"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudParentViewController(controller:)":{"role":"symbol","title":"apphudParentViewController(controller:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudParentViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Return "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" instance from which you want to present given Apphud controller. If you don’t implement this method, then top visible viewcontroller from key window will be used."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudParentViewController(controller:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"apphudParentViewControllerWithController:"}],"url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudparentviewcontroller(controller:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"apphudParentViewControllerWithController:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudParentViewControllerWithController:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"apphudParentViewControllerWithController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/title","value":"ApphudUIDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/fragments","value":[{"kind":"identifier","text":"ApphudUIDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudParentViewController(controller:)\/title","value":"apphudParentViewControllerWithController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudParentViewController(controller:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudParentViewControllerWithController:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}