{"variants":[{"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreendismissaction(screenname:controller:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreendismissaction(screenname:controller:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ApphudSDK"}],"roleHeading":"Instance Method","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"apphudScreenDismissAction","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"screenName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"controller"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@E@ApphudScreenDismissAction","kind":"typeIdentifier","text":"ApphudScreenDismissAction"}],"title":"apphudScreenDismissAction(screenName:controller:)","role":"symbol","externalID":"c:@M@ApphudSDK@objc(pl)ApphudUIDelegate(im)apphudScreenDismissActionWithScreenName:controller:","navigatorTitle":[{"text":"apphudScreenDismissActionWithScreenName:controller:","kind":"identifier"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apphudScreenDismissAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"screenName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":") -> "},{"text":"ApphudScreenDismissAction","preciseIdentifier":"c:@M@ApphudSDK@E@ApphudScreenDismissAction","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction","kind":"typeIdentifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenDismissAction(screenName:controller:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"]]},"abstract":[{"type":"text","text":"(New) Overrides action after survey option is selected or feeback sent is tapped. Default is “thankAndClose”."},{"text":" ","type":"text"},{"type":"text","text":"This delegate method is only called if no other screen is selected as button action in Apphud Screens editor."},{"text":" ","type":"text"},{"text":"You can return ","type":"text"},{"code":"noAction","type":"codeVoice"},{"type":"text","text":" value and use "},{"type":"codeVoice","code":"navigationController"},{"text":" property of ","type":"text"},{"code":"controller","type":"codeVoice"},{"text":" variable to push your own view controller into hierarchy.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldPerformRule(rule:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldShowScreen(screenName:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudParentViewController(controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenPresentationStyle(controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudParentViewController(controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudWillPurchase(product:offerID:screenName:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidPurchase(product:offerID:screenName:)"],"generated":true,"title":"ApphudUIDelegate main methods"}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudScreenDismissAction":{"navigatorTitle":[{"kind":"identifier","text":"ApphudScreenDismissAction"}],"abstract":[{"text":"These are three types of actions that are returned in ","type":"text"},{"code":"apphudScreenDismissAction(screenName: String, controller: UIViewController)","type":"codeVoice"},{"text":" delegate method","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction","url":"\/documentation\/apphudsdk\/apphudscreendismissaction","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudScreenDismissAction"}],"title":"ApphudScreenDismissAction","role":"symbol","type":"topic","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudScreenPresentationStyle(controller:)":{"abstract":[{"type":"text","text":"Pass your own modal presentation style to Apphud Screens. This is useful since iOS 13 presents in page sheet style by default."}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudScreenPresentationStyle"},{"text":"(","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@UIModalPresentationStyle","text":"UIModalPresentationStyle","kind":"typeIdentifier"}],"title":"apphudScreenPresentationStyle(controller:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenPresentationStyle(controller:)","type":"topic","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreenpresentationstyle(controller:)","navigatorTitle":[{"kind":"identifier","text":"apphudScreenPresentationStyleWithController:"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudShouldPerformRule(rule:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudShouldPerformRule"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rule"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudRule","text":"ApphudRule","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"You can return "},{"type":"codeVoice","code":"false"},{"text":" to ignore this rule. You should only do this if you want to handle your rules by yourself. Default implementation is ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldPerformRule(rule:)","title":"apphudShouldPerformRule(rule:)","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudshouldperformrule(rule:)","required":true,"navigatorTitle":[{"text":"apphudShouldPerformRuleWithRule:","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudShouldShowScreen(screenName:)":{"abstract":[{"type":"text","text":"You can return "},{"type":"codeVoice","code":"false"},{"type":"text","text":" to this delegate method if you want to delay Apphud Screen presentation."}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudShouldShowScreen","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"screenName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"apphudShouldShowScreen(screenName:)","required":true,"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldShowScreen(screenName:)","type":"topic","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudshouldshowscreen(screenname:)","navigatorTitle":[{"kind":"identifier","text":"apphudShouldShowScreenWithScreenName:"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudWillPurchase(product:offerID:screenName:)":{"abstract":[{"text":"Called when user tapped on purchase button in Apphud purchase screen.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudWillPurchase","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"product"},{"text":": ","kind":"text"},{"text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"offerID","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"screenName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"title":"apphudWillPurchase(product:offerID:screenName:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudWillPurchase(product:offerID:screenName:)","type":"topic","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudwillpurchase(product:offerid:screenname:)","navigatorTitle":[{"text":"apphudWillPurchaseWithProduct:offerID:screenName:","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","url":"\/documentation\/apphudsdk","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"title":"ApphudSDK","type":"topic","role":"collection","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudScreenDismissAction(screenName:controller:)":{"abstract":[{"type":"text","text":"(New) Overrides action after survey option is selected or feeback sent is tapped. Default is “thankAndClose”."},{"type":"text","text":" "},{"type":"text","text":"This delegate method is only called if no other screen is selected as button action in Apphud Screens editor."},{"text":" ","type":"text"},{"type":"text","text":"You can return "},{"type":"codeVoice","code":"noAction"},{"type":"text","text":" value and use "},{"type":"codeVoice","code":"navigationController"},{"text":" property of ","type":"text"},{"type":"codeVoice","code":"controller"},{"text":" variable to push your own view controller into hierarchy.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudScreenDismissAction"},{"text":"(","kind":"text"},{"text":"screenName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@E@ApphudScreenDismissAction","text":"ApphudScreenDismissAction"}],"title":"apphudScreenDismissAction(screenName:controller:)","required":true,"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenDismissAction(screenName:controller:)","type":"topic","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreendismissaction(screenname:controller:)","navigatorTitle":[{"kind":"identifier","text":"apphudScreenDismissActionWithScreenName:controller:"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudParentViewController(controller:)":{"abstract":[{"type":"text","text":"Return "},{"type":"codeVoice","code":"UIViewController"},{"text":" instance from which you want to present given Apphud controller. If you don’t implement this method, then top visible viewcontroller from key window will be used.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apphudParentViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"controller"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}],"title":"apphudParentViewController(controller:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudParentViewController(controller:)","type":"topic","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudparentviewcontroller(controller:)","navigatorTitle":[{"kind":"identifier","text":"apphudParentViewControllerWithController:"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudDidPurchase(product:offerID:screenName:)":{"abstract":[{"type":"text","text":"Called when user successfully purchased product in Apphud purchase screen."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apphudDidPurchase","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"product"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"offerID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"screenName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"apphudDidPurchase(product:offerID:screenName:)","required":true,"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidPurchase(product:offerID:screenName:)","type":"topic","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphuddidpurchase(product:offerid:screenname:)","navigatorTitle":[{"kind":"identifier","text":"apphudDidPurchaseWithProduct:offerID:screenName:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"apphudScreenDismissActionWithScreenName:controller:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudScreenDismissActionWithScreenName:controller:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldPerformRule(rule:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldShowScreen(screenName:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudParentViewController(controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenPresentationStyle(controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudParentViewController(controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudWillPurchase(product:offerID:screenName:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidPurchase(product:offerID:screenName:)"],"generated":true,"title":"ApphudUIDelegate main methods"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudScreenDismissAction","preciseIdentifier":"c:@M@ApphudSDK@E@ApphudScreenDismissAction","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudScreenDismissAction","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"apphudScreenDismissActionWithScreenName:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"screenName","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"controller:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ApphudScreenDismissAction","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudScreenDismissAction\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudScreenDismissAction"}]},{"value":"apphudScreenPresentationStyleWithController:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenPresentationStyle(controller:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"apphudScreenPresentationStyleWithController:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenPresentationStyle(controller:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudShouldPerformRule(rule:)\/title","value":"apphudShouldPerformRuleWithRule:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"apphudShouldPerformRuleWithRule:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudShouldPerformRule(rule:)\/fragments"},{"op":"replace","value":"apphudShouldShowScreenWithScreenName:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudShouldShowScreen(screenName:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudShouldShowScreen(screenName:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"apphudShouldShowScreenWithScreenName:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudWillPurchase(product:offerID:screenName:)\/title","op":"replace","value":"apphudWillPurchaseWithProduct:offerID:screenName:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"apphudWillPurchaseWithProduct:offerID:screenName:"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudWillPurchase(product:offerID:screenName:)\/fragments","op":"replace"},{"value":"apphudScreenDismissActionWithScreenName:controller:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenDismissAction(screenName:controller:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenDismissAction(screenName:controller:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"apphudScreenDismissActionWithScreenName:controller:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudParentViewController(controller:)\/title","value":"apphudParentViewControllerWithController:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudParentViewController(controller:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"apphudParentViewControllerWithController:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidPurchase(product:offerID:screenName:)\/title","value":"apphudDidPurchaseWithProduct:offerID:screenName:"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidPurchase(product:offerID:screenName:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"apphudDidPurchaseWithProduct:offerID:screenName:"}],"op":"replace"}]}]}