{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudScreenWillDismiss","kind":"identifier"},{"kind":"text","text":"("},{"text":"screenName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"apphudScreenWillDismissWithScreenName:error:"}],"modules":[{"name":"ApphudSDK"}],"title":"apphudScreenWillDismiss(screenName:error:)","externalID":"c:@M@ApphudSDK@objc(pl)ApphudUIDelegate(im)apphudScreenWillDismissWithScreenName:error:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudScreenWillDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"screenName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreenwilldismiss(screenname:error:)"]},{"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreenwilldismiss(screenname:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenWillDismiss(screenName:error:)"},"abstract":[{"type":"text","text":"Called when screen is about to dismiss."}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate":{"title":"ApphudUIDelegate","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudUIDelegate"}],"abstract":[{"text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the Rules state and custom Rules view presentation","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudUIDelegate"}],"url":"\/documentation\/apphudsdk\/apphuduidelegate"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudScreenWillDismiss(screenName:error:)":{"navigatorTitle":[{"kind":"identifier","text":"apphudScreenWillDismissWithScreenName:error:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenWillDismiss(screenName:error:)","type":"topic","title":"apphudScreenWillDismiss(screenName:error:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudScreenWillDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"screenName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called when screen is about to dismiss."}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreenwilldismiss(screenname:error:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"title":"ApphudSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"apphudScreenWillDismissWithScreenName:error:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudScreenWillDismissWithScreenName:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"apphudScreenWillDismissWithScreenName:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"screenName"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/title","value":"ApphudUIDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/fragments","value":[{"text":"ApphudUIDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ApphudUIDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenWillDismiss(screenName:error:)\/title","value":"apphudScreenWillDismissWithScreenName:error:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudScreenWillDismissWithScreenName:error:"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenWillDismiss(screenName:error:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}