{"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidPurchase(product:offerID:screenName:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apphudDidPurchase"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"product"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier","text":"SKProduct"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"offerID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"screenName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate"]]},"variants":[{"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphuddidpurchase(product:offerid:screenname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphuddidpurchase(product:offerid:screenname:)"]}],"metadata":{"required":true,"externalID":"c:@M@ApphudSDK@objc(pl)ApphudUIDelegate(im)apphudDidPurchaseWithProduct:offerID:screenName:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"apphudDidPurchase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"offerID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"screenName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"apphudDidPurchaseWithProduct:offerID:screenName:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"apphudDidPurchase(product:offerID:screenName:)","modules":[{"name":"ApphudSDK"}]},"abstract":[{"text":"Called when user successfully purchased product in Apphud purchase screen.","type":"text"}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the Rules state and custom Rules view presentation"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudUIDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudUIDelegate"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate","title":"ApphudUIDelegate","url":"\/documentation\/apphudsdk\/apphuduidelegate"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","url":"\/documentation\/apphudsdk","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","abstract":[]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudDidPurchase(product:offerID:screenName:)":{"required":true,"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidPurchase(product:offerID:screenName:)","abstract":[{"text":"Called when user successfully purchased product in Apphud purchase screen.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"apphudDidPurchase","kind":"identifier"},{"kind":"text","text":"("},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"offerID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"screenName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphuddidpurchase(product:offerid:screenname:)","kind":"symbol","role":"symbol","title":"apphudDidPurchase(product:offerID:screenName:)","navigatorTitle":[{"kind":"identifier","text":"apphudDidPurchaseWithProduct:offerID:screenName:"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"apphudDidPurchaseWithProduct:offerID:screenName:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"apphudDidPurchaseWithProduct:offerID:screenName:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"apphudDidPurchaseWithProduct:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"product"},{"kind":"text","text":" "},{"text":"offerID:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"offerID","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"screenName:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"screenName","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/title","op":"replace","value":"ApphudUIDelegate"},{"op":"replace","value":[{"text":"ApphudUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidPurchase(product:offerID:screenName:)\/title","op":"replace","value":"apphudDidPurchaseWithProduct:offerID:screenName:"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidPurchase(product:offerID:screenName:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"apphudDidPurchaseWithProduct:offerID:screenName:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}