{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidFailPurchase(product:offerID:errorCode:screenName:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apphudDidFailPurchase"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"product"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offerID"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"errorCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SKError","preciseIdentifier":"s:SC11SKErrorCodeLeV"},{"kind":"text","text":"."},{"text":"Code","kind":"typeIdentifier","preciseIdentifier":"c:@E@SKErrorCode"},{"kind":"text","text":", "},{"text":"screenName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"See error code for details. For example, ","type":"text"},{"code":".paymentCancelled","type":"codeVoice"},{"text":" error code is when user canceled the purchase by himself.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"externalID":"c:@M@ApphudSDK@objc(pl)ApphudUIDelegate(im)apphudDidFailPurchaseWithProduct:offerID:errorCode:screenName:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"apphudDidFailPurchaseWithProduct:offerID:errorCode:screenName:"}],"modules":[{"name":"ApphudSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"apphudDidFailPurchase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offerID"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"errorCode"},{"text":": ","kind":"text"},{"text":"SKError","kind":"typeIdentifier","preciseIdentifier":"s:SC11SKErrorCodeLeV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SKErrorCode","text":"Code"},{"text":", ","kind":"text"},{"text":"screenName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","title":"apphudDidFailPurchase(product:offerID:errorCode:screenName:)","roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphuddidfailpurchase(product:offerid:errorcode:screenname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphuddidfailpurchase(product:offerid:errorcode:screenname:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate"]]},"abstract":[{"text":"Called when purchase failed in Apphud purchase screen.","type":"text"}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the Rules state and custom Rules view presentation"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudUIDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudUIDelegate"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate","title":"ApphudUIDelegate","url":"\/documentation\/apphudsdk\/apphuduidelegate"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudDidFailPurchase(product:offerID:errorCode:screenName:)":{"type":"topic","abstract":[{"type":"text","text":"Called when purchase failed in Apphud purchase screen."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"apphudDidFailPurchase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"product","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"offerID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"errorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SKError","kind":"typeIdentifier","preciseIdentifier":"s:SC11SKErrorCodeLeV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Code","preciseIdentifier":"c:@E@SKErrorCode"},{"text":", ","kind":"text"},{"text":"screenName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphuddidfailpurchase(product:offerid:errorcode:screenname:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidFailPurchase(product:offerID:errorCode:screenName:)","title":"apphudDidFailPurchase(product:offerID:errorCode:screenName:)","navigatorTitle":[{"kind":"identifier","text":"apphudDidFailPurchaseWithProduct:offerID:errorCode:screenName:"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","url":"\/documentation\/apphudsdk","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"apphudDidFailPurchaseWithProduct:offerID:errorCode:screenName:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"apphudDidFailPurchaseWithProduct:offerID:errorCode:screenName:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"apphudDidFailPurchaseWithProduct:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier","text":"SKProduct"},{"text":" *) ","kind":"text"},{"text":"product","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offerID:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"offerID","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"errorCode:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@E@SKErrorCode","text":"SKErrorCode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"errorCode","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"screenName:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"screenName","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/title","value":"ApphudUIDelegate"},{"op":"replace","value":[{"text":"ApphudUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidFailPurchase(product:offerID:errorCode:screenName:)\/title","value":"apphudDidFailPurchaseWithProduct:offerID:errorCode:screenName:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"apphudDidFailPurchaseWithProduct:offerID:errorCode:screenName:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidFailPurchase(product:offerID:errorCode:screenName:)\/fragments"}]}]}