{"seeAlsoSections":[{"title":"ApphudUIDelegate main methods","generated":true,"anchor":"ApphudUIDelegate-main-methods","identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldPerformRule(rule:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldShowScreen(screenName:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudParentViewController(controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenPresentationStyle(controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidPurchase(product:offerID:screenName:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidFailPurchase(product:offerID:errorCode:screenName:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenDidAppear(screenName:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenWillDismiss(screenName:error:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidDismissScreen(controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenDismissAction(screenName:controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidSelectSurveyAnswer(question:answer:screenName:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudWillPurchase","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"product"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"offerID"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"screenName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudWillPurchase(product:offerID:screenName:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudwillpurchase(product:offerid:screenname:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudwillpurchase(product:offerid:screenname:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate"]]},"abstract":[{"type":"text","text":"Called when user tapped on purchase button in Apphud purchase screen."}],"kind":"symbol","metadata":{"modules":[{"name":"ApphudSDK"}],"title":"apphudWillPurchase(product:offerID:screenName:)","roleHeading":"Instance Method","externalID":"c:@M@ApphudSDK@objc(pl)ApphudUIDelegate(im)apphudWillPurchaseWithProduct:offerID:screenName:","navigatorTitle":[{"kind":"text","text":"- "},{"text":"apphudWillPurchaseWithProduct:offerID:screenName:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudWillPurchase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SKProduct","preciseIdentifier":"c:objc(cs)SKProduct","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"offerID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"screenName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudDidPurchase(product:offerID:screenName:)":{"abstract":[{"type":"text","text":"Called when user successfully purchased product in Apphud purchase screen."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apphudDidPurchase","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"product"},{"kind":"text","text":": "},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":", ","kind":"text"},{"text":"offerID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"screenName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"apphudDidPurchaseWithProduct:offerID:screenName:","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphuddidpurchase(product:offerid:screenname:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidPurchase(product:offerID:screenName:)","title":"apphudDidPurchase(product:offerID:screenName:)","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudParentViewController(controller:)":{"kind":"symbol","title":"apphudParentViewController(controller:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudParentViewController(controller:)","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudparentviewcontroller(controller:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudParentViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudParentViewControllerWithController:"}],"abstract":[{"type":"text","text":"Return "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" instance from which you want to present given Apphud controller. If you don’t implement this method, then top visible viewcontroller from key window will be used."}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudShouldPerformRule(rule:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldPerformRule(rule:)","abstract":[{"type":"text","text":"You can return "},{"type":"codeVoice","code":"false"},{"type":"text","text":" to ignore this rule. You should only do this if you want to handle your rules by yourself. Default implementation is "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"apphudShouldPerformRule","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rule"},{"kind":"text","text":": "},{"text":"ApphudRule","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudRule"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"apphudShouldPerformRule(rule:)","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"apphudShouldPerformRuleWithRule:","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudshouldperformrule(rule:)"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudDidFailPurchase(product:offerID:errorCode:screenName:)":{"title":"apphudDidFailPurchase(product:offerID:errorCode:screenName:)","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"apphudDidFailPurchaseWithProduct:offerID:errorCode:screenName:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudDidFailPurchase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"product","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":", ","kind":"text"},{"text":"offerID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SKErrorCode","text":"SKError"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@SKErrorCode","text":"Code","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"screenName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidFailPurchase(product:offerID:errorCode:screenName:)","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphuddidfailpurchase(product:offerid:errorcode:screenname:)","type":"topic","abstract":[{"text":"Called when purchase failed in Apphud purchase screen.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudDidSelectSurveyAnswer(question:answer:screenName:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidSelectSurveyAnswer(question:answer:screenName:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudDidSelectSurveyAnswerWithQuestion:answer:screenName:"}],"title":"apphudDidSelectSurveyAnswer(question:answer:screenName:)","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphuddidselectsurveyanswer(question:answer:screenname:)","abstract":[{"text":"(New) Called after survey answer is selected.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apphudDidSelectSurveyAnswer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"question","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"answer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"screenName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudScreenDidAppear(screenName:)":{"kind":"symbol","title":"apphudScreenDidAppear(screenName:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenDidAppear(screenName:)","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreendidappear(screenname:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudScreenDidAppear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"screenName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudScreenDidAppearWithScreenName:"}],"abstract":[{"text":"Called when screen succesfully loaded and is visible to user.","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudShouldShowScreen(screenName:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldShowScreen(screenName:)","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"apphudShouldShowScreenWithScreenName:","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudshouldshowscreen(screenname:)","kind":"symbol","abstract":[{"text":"You can return ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" to this delegate method if you want to delay Apphud Screen presentation.","type":"text"}],"title":"apphudShouldShowScreen(screenName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"apphudShouldShowScreen","kind":"identifier"},{"kind":"text","text":"("},{"text":"screenName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudScreenDismissAction(screenName:controller:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenDismissAction(screenName:controller:)","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"apphudScreenDismissActionWithScreenName:controller:","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreendismissaction(screenname:controller:)","kind":"symbol","abstract":[{"text":"(New) Overrides action after survey option is selected or feeback sent is tapped. Default is “thankAndClose”.","type":"text"},{"text":" ","type":"text"},{"text":"This delegate method is only called if no other screen is selected as button action in Apphud Screens editor.","type":"text"},{"type":"text","text":" "},{"text":"You can return ","type":"text"},{"type":"codeVoice","code":"noAction"},{"type":"text","text":" value and use "},{"type":"codeVoice","code":"navigationController"},{"type":"text","text":" property of "},{"type":"codeVoice","code":"controller"},{"type":"text","text":" variable to push your own view controller into hierarchy."}],"title":"apphudScreenDismissAction(screenName:controller:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apphudScreenDismissAction"},{"kind":"text","text":"("},{"text":"screenName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ApphudSDK@E@ApphudScreenDismissAction","kind":"typeIdentifier","text":"ApphudScreenDismissAction"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudScreenWillDismiss(screenName:error:)":{"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudScreenWillDismissWithScreenName:error:"}],"type":"topic","kind":"symbol","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreenwilldismiss(screenname:error:)","abstract":[{"text":"Called when screen is about to dismiss.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"apphudScreenWillDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"screenName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"title":"apphudScreenWillDismiss(screenName:error:)","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenWillDismiss(screenName:error:)","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudScreenPresentationStyle(controller:)":{"role":"symbol","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreenpresentationstyle(controller:)","title":"apphudScreenPresentationStyle(controller:)","abstract":[{"type":"text","text":"Pass your own modal presentation style to Apphud Screens. This is useful since iOS 13 presents in page sheet style by default."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"apphudScreenPresentationStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIModalPresentationStyle","preciseIdentifier":"c:@E@UIModalPresentationStyle"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenPresentationStyle(controller:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"apphudScreenPresentationStyleWithController:","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudDidDismissScreen(controller:)":{"abstract":[{"text":"Notifies that Apphud Screen did dismiss","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"text","text":"- "},{"text":"apphudDidDismissScreenWithController:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidDismissScreen(controller:)","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphuddiddismissscreen(controller:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apphudDidDismissScreen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"controller","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"apphudDidDismissScreen(controller:)","kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate","url":"\/documentation\/apphudsdk\/apphuduidelegate","abstract":[{"text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the Rules state and custom Rules view presentation","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudUIDelegate"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudUIDelegate"}],"title":"ApphudUIDelegate"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudWillPurchase(product:offerID:screenName:)":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudWillPurchase(product:offerID:screenName:)","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudWillPurchaseWithProduct:offerID:screenName:"}],"url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudwillpurchase(product:offerid:screenname:)","kind":"symbol","abstract":[{"type":"text","text":"Called when user tapped on purchase button in Apphud purchase screen."}],"title":"apphudWillPurchase(product:offerID:screenName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"apphudWillPurchase","kind":"identifier"},{"text":"(","kind":"text"},{"text":"product","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"offerID","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"screenName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"apphudWillPurchaseWithProduct:offerID:screenName:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudWillPurchaseWithProduct:offerID:screenName:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldPerformRule(rule:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldShowScreen(screenName:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudParentViewController(controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenPresentationStyle(controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidPurchase(product:offerID:screenName:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidFailPurchase(product:offerID:errorCode:screenName:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenDidAppear(screenName:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenWillDismiss(screenName:error:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidDismissScreen(controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenDismissAction(screenName:controller:)","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudDidSelectSurveyAnswer(question:answer:screenName:)"],"title":"ApphudUIDelegate main methods","generated":true,"anchor":"ApphudUIDelegate-main-methods"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"apphudWillPurchaseWithProduct:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":" *) ","kind":"text"},{"text":"product","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"offerID:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"offerID"},{"text":" ","kind":"text"},{"text":"screenName:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"screenName","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"apphudDidPurchaseWithProduct:offerID:screenName:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidPurchase(product:offerID:screenName:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidPurchase(product:offerID:screenName:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudDidPurchaseWithProduct:offerID:screenName:"}]},{"value":"apphudParentViewControllerWithController:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudParentViewController(controller:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudParentViewController(controller:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"apphudParentViewControllerWithController:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"apphudShouldPerformRuleWithRule:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudShouldPerformRule(rule:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudShouldPerformRule(rule:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"apphudShouldPerformRuleWithRule:","kind":"identifier"}]},{"value":"apphudDidFailPurchaseWithProduct:offerID:errorCode:screenName:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidFailPurchase(product:offerID:errorCode:screenName:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"apphudDidFailPurchaseWithProduct:offerID:errorCode:screenName:"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidFailPurchase(product:offerID:errorCode:screenName:)\/fragments","op":"replace"},{"value":"apphudDidSelectSurveyAnswerWithQuestion:answer:screenName:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidSelectSurveyAnswer(question:answer:screenName:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"apphudDidSelectSurveyAnswerWithQuestion:answer:screenName:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidSelectSurveyAnswer(question:answer:screenName:)\/fragments"},{"value":"apphudScreenDidAppearWithScreenName:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenDidAppear(screenName:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudScreenDidAppearWithScreenName:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenDidAppear(screenName:)\/fragments"},{"op":"replace","value":"apphudShouldShowScreenWithScreenName:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudShouldShowScreen(screenName:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"apphudShouldShowScreenWithScreenName:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudShouldShowScreen(screenName:)\/fragments"},{"value":"apphudScreenDismissActionWithScreenName:controller:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenDismissAction(screenName:controller:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"apphudScreenDismissActionWithScreenName:controller:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenDismissAction(screenName:controller:)\/fragments"},{"value":"apphudScreenWillDismissWithScreenName:error:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenWillDismiss(screenName:error:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"apphudScreenWillDismissWithScreenName:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenWillDismiss(screenName:error:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenPresentationStyle(controller:)\/title","op":"replace","value":"apphudScreenPresentationStyleWithController:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudScreenPresentationStyleWithController:"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenPresentationStyle(controller:)\/fragments","op":"replace"},{"value":"apphudDidDismissScreenWithController:","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidDismissScreen(controller:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"apphudDidDismissScreenWithController:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudDidDismissScreen(controller:)\/fragments"},{"value":"ApphudUIDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/title"},{"value":[{"kind":"identifier","text":"ApphudUIDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/fragments"},{"value":[{"kind":"identifier","text":"ApphudUIDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/navigatorTitle"},{"value":"apphudWillPurchaseWithProduct:offerID:screenName:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudWillPurchase(product:offerID:screenName:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"apphudWillPurchaseWithProduct:offerID:screenName:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudWillPurchase(product:offerID:screenName:)\/fragments"}]}]}