{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"You can return "},{"code":"false","type":"codeVoice"},{"text":" to this delegate method if you want to delay Apphud Screen presentation.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apphudShouldShowScreen"},{"text":"(","kind":"text"},{"text":"screenName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Controller will be kept in memory until you present it via ","type":"text"},{"type":"codeVoice","code":"Apphud.showPendingScreen()"},{"text":" method. If you don’t want to show screen at all, you should check ","type":"text"},{"code":"apphudShouldPerformRule","type":"codeVoice"},{"text":" delegate method.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudshouldshowscreen(screenname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudshouldshowscreen(screenname:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldShowScreen(screenName:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudShouldShowScreen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"screenName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"apphudShouldShowScreenWithScreenName:","kind":"identifier"}],"externalID":"c:@M@ApphudSDK@objc(pl)ApphudUIDelegate(im)apphudShouldShowScreenWithScreenName:","modules":[{"name":"ApphudSDK"}],"title":"apphudShouldShowScreen(screenName:)","role":"symbol"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudShouldShowScreen(screenName:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudShouldShowScreen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"screenName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"apphudShouldShowScreenWithScreenName:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudShouldShowScreen(screenName:)","title":"apphudShouldShowScreen(screenName:)","abstract":[{"text":"You can return ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" to this delegate method if you want to delay Apphud Screen presentation."}],"url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudshouldshowscreen(screenname:)","type":"topic","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate":{"url":"\/documentation\/apphudsdk\/apphuduidelegate","title":"ApphudUIDelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudUIDelegate"}],"abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the Rules state and custom Rules view presentation"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudUIDelegate"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"apphudShouldShowScreenWithScreenName:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"apphudShouldShowScreenWithScreenName:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"apphudShouldShowScreenWithScreenName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"screenName"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudShouldShowScreen(screenName:)\/title","value":"apphudShouldShowScreenWithScreenName:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudShouldShowScreen(screenName:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"apphudShouldShowScreenWithScreenName:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/title","value":"ApphudUIDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/fragments","op":"replace","value":[{"text":"ApphudUIDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}