{"kind":"symbol","metadata":{"modules":[{"name":"ApphudSDK"}],"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apphudScreenPresentationStyle","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"controller"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIModalPresentationStyle","preciseIdentifier":"c:@E@UIModalPresentationStyle"}],"navigatorTitle":[{"text":"apphudScreenPresentationStyleWithController:","kind":"identifier"}],"required":true,"title":"apphudScreenPresentationStyle(controller:)","roleHeading":"Instance Method","externalID":"c:@M@ApphudSDK@objc(pl)ApphudUIDelegate(im)apphudScreenPresentationStyleWithController:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenPresentationStyle(controller:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apphudScreenPresentationStyle","kind":"identifier"},{"kind":"text","text":"("},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UIModalPresentationStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIModalPresentationStyle"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"To get full screen style you should pass "},{"type":"codeVoice","code":".fullScreen"},{"type":"text","text":" or "},{"code":".overFullScreen","type":"codeVoice"},{"text":".","type":"text"}]}]}],"abstract":[{"text":"Pass your own modal presentation style to Apphud Screens. This is useful since iOS 13 presents in page sheet style by default.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreenpresentationstyle(controller:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreenpresentationstyle(controller:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate":{"url":"\/documentation\/apphudsdk\/apphuduidelegate","title":"ApphudUIDelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudUIDelegate"}],"abstract":[{"type":"text","text":"A public protocol that provides access to Apphud’s main public methods, describing the behavior of the Rules state and custom Rules view presentation"}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApphudUIDelegate"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","abstract":[],"kind":"symbol","url":"\/documentation\/apphudsdk","role":"collection","title":"ApphudSDK","type":"topic"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUIDelegate/apphudScreenPresentationStyle(controller:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUIDelegate\/apphudScreenPresentationStyle(controller:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apphudScreenPresentationStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIModalPresentationStyle","text":"UIModalPresentationStyle"}],"navigatorTitle":[{"kind":"identifier","text":"apphudScreenPresentationStyleWithController:"}],"type":"topic","required":true,"title":"apphudScreenPresentationStyle(controller:)","url":"\/documentation\/apphudsdk\/apphuduidelegate\/apphudscreenpresentationstyle(controller:)","abstract":[{"type":"text","text":"Pass your own modal presentation style to Apphud Screens. This is useful since iOS 13 presents in page sheet style by default."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"apphudScreenPresentationStyleWithController:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"apphudScreenPresentationStyleWithController:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@E@UIModalPresentationStyle","kind":"typeIdentifier","text":"UIModalPresentationStyle"},{"text":") ","kind":"text"},{"kind":"identifier","text":"apphudScreenPresentationStyleWithController:"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/title","value":"ApphudUIDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate\/fragments","value":[{"text":"ApphudUIDelegate","kind":"identifier"}]},{"value":"apphudScreenPresentationStyleWithController:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenPresentationStyle(controller:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUIDelegate~1apphudScreenPresentationStyle(controller:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"apphudScreenPresentationStyleWithController:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}