platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ApphudSDKDemo' do
pod 'ApphudSDK', :path => '../../'
end

target 'ApphudSDKTests' do
pod 'ApphudSDK', :path => '../../'
end
