{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphudgroup\/products"]}],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"products"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"role":"symbol","modules":[{"name":"ApphudSDK"}],"title":"products","roleHeading":"Instance Property","externalID":"s:9ApphudSDK0A5GroupC8productsSayAA0A7ProductCGvp"},"sections":[],"abstract":[{"text":"You should not operate with products from ApphudGroup directly. Use Paywalls or Paywalls within Placements.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup\/products","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"products","kind":"identifier"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","kind":"typeIdentifier","text":"ApphudProduct","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct"},{"kind":"text","text":"]"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Products that belong to this permission group."}],"type":"paragraph"}]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudProduct":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ApphudProduct","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphudproduct","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApphudProduct"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudProduct","title":"ApphudProduct","abstract":[{"text":"Apphud’s wrapper around ","type":"text"},{"type":"codeVoice","code":"SKProduct"},{"text":".","type":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudGroup/products":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"products","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudProduct","text":"ApphudProduct"},{"kind":"text","text":"]"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"You should not operate with products from ApphudGroup directly. Use Paywalls or Paywalls within Placements.","type":"text"}],"title":"products","url":"\/documentation\/apphudsdk\/apphudgroup\/products","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup\/products"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudGroup":{"type":"topic","url":"\/documentation\/apphudsdk\/apphudgroup","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudGroup","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ApphudGroup","kind":"identifier"}],"abstract":[{"text":"Apphud class which describes products permission groups","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudGroup"}],"kind":"symbol","title":"ApphudGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ApphudProduct","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/title"},{"value":[{"kind":"identifier","text":"ApphudProduct"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudProduct\/fragments"},{"op":"replace","value":"ApphudGroup","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudGroup\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudGroup\/fragments","op":"replace","value":[{"kind":"identifier","text":"ApphudGroup"}]}]}]}