{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"grace"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphudsubscriptionstatus\/grace"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudsubscriptionstatus\/grace"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscriptionStatus\/grace","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"grace"}],"title":"ApphudSubscriptionStatus.grace","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ApphudSDK@E@ApphudSubscriptionStatus@ApphudSubscriptionStatusGrace","modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudSubscriptionStatusGrace"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscriptionStatus"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudSubscriptionStatus":{"role":"symbol","title":"ApphudSubscriptionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudSubscriptionStatus"}],"abstract":[{"type":"text","text":"Status of the subscription. It can only be in one state at any moment."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscriptionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudSubscriptionStatus"}],"url":"\/documentation\/apphudsdk\/apphudsubscriptionstatus"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudSubscriptionStatus/grace":{"role":"symbol","title":"ApphudSubscriptionStatus.grace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"grace"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscriptionStatus\/grace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudSubscriptionStatusGrace"}],"url":"\/documentation\/apphudsdk\/apphudsubscriptionstatus\/grace"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ApphudSubscriptionStatusGrace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ApphudSubscriptionStatusGrace"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ApphudSubscriptionStatusGrace"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscriptionStatus\/title","value":"ApphudSubscriptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscriptionStatus\/fragments","value":[{"kind":"identifier","text":"ApphudSubscriptionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscriptionStatus~1grace\/title","value":"ApphudSubscriptionStatusGrace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscriptionStatus~1grace\/fragments","value":[{"kind":"identifier","text":"ApphudSubscriptionStatusGrace"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}