{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"promo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apphudsdk\/apphudsubscriptionstatus\/promo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/apphudsdk\/apphudsubscriptionstatus\/promo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscriptionStatus\/promo","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"promo"}],"title":"ApphudSubscriptionStatus.promo","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ApphudSDK@E@ApphudSubscriptionStatus@ApphudSubscriptionStatusPromo","modules":[{"name":"ApphudSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ApphudSubscriptionStatusPromo"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscriptionStatus"]]},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","title":"ApphudSDK","abstract":[{"type":"text","text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","kind":"symbol","type":"topic","url":"\/documentation\/apphudsdk"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudSubscriptionStatus/promo":{"role":"symbol","title":"ApphudSubscriptionStatus.promo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"promo"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscriptionStatus\/promo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudSubscriptionStatusPromo"}],"url":"\/documentation\/apphudsdk\/apphudsubscriptionstatus\/promo"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudSubscriptionStatus":{"role":"symbol","title":"ApphudSubscriptionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudSubscriptionStatus"}],"abstract":[{"type":"text","text":"Status of the subscription. It can only be in one state at any moment."}],"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudSubscriptionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApphudSubscriptionStatus"}],"url":"\/documentation\/apphudsdk\/apphudsubscriptionstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ApphudSubscriptionStatusPromo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ApphudSubscriptionStatusPromo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ApphudSubscriptionStatusPromo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscriptionStatus~1promo\/title","value":"ApphudSubscriptionStatusPromo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscriptionStatus~1promo\/fragments","value":[{"kind":"identifier","text":"ApphudSubscriptionStatusPromo"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscriptionStatus\/title","value":"ApphudSubscriptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudSubscriptionStatus\/fragments","value":[{"kind":"identifier","text":"ApphudSubscriptionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}