{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/age","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"ApphudSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"age"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","kind":"typeIdentifier","text":"ApphudUserPropertyKey"}],"role":"symbol","roleHeading":"Type Property","externalID":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey(cpy)age","title":"age","navigatorTitle":[{"kind":"identifier","text":"age"}],"symbolKind":"property"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/apphudsdk\/apphuduserpropertykey\/age"]},{"paths":["\/documentation\/apphudsdk\/apphuduserpropertykey\/age"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"age","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ApphudUserPropertyKey","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey/age":{"title":"age","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/age","role":"symbol","navigatorTitle":[{"text":"age","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphuduserpropertykey\/age","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"age"},{"text":": ","kind":"text"},{"text":"ApphudUserPropertyKey","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","kind":"typeIdentifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey":{"type":"topic","abstract":[{"type":"text","text":"User property initializer class with reserved property names."}],"url":"\/documentation\/apphudsdk\/apphuduserpropertykey","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudUserPropertyKey"}],"navigatorTitle":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"role":"symbol","title":"ApphudUserPropertyKey"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"age","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"age","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"ApphudUserPropertyKey","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"age"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1age\/title","value":"age"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1age\/fragments","value":[{"kind":"identifier","text":"age"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/title","value":"ApphudUserPropertyKey"},{"op":"replace","value":[{"kind":"identifier","text":"ApphudUserPropertyKey"}],"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}