{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ApphudUserPropertyKey","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/email"},"variants":[{"paths":["\/documentation\/apphudsdk\/apphuduserpropertykey\/email"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphuduserpropertykey\/email"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey"]]},"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"ApphudSDK"}],"externalID":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey(cpy)email","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ApphudUserPropertyKey","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","kind":"typeIdentifier"}],"roleHeading":"Type Property","role":"symbol","navigatorTitle":[{"text":"email","kind":"identifier"}],"title":"email"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey/email":{"navigatorTitle":[{"kind":"identifier","text":"email"}],"type":"topic","kind":"symbol","url":"\/documentation\/apphudsdk\/apphuduserpropertykey\/email","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApphudUserPropertyKey","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"}],"title":"email","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/email","role":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"abstract":[{"text":"User property initializer class with reserved property names.","type":"text"}],"type":"topic","title":"ApphudUserPropertyKey","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","url":"\/documentation\/apphudsdk\/apphuduserpropertykey","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudUserPropertyKey","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"email"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"email"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","text":"ApphudUserPropertyKey"},{"kind":"text","text":" * "},{"kind":"identifier","text":"email"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1email\/title","value":"email","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1email\/fragments","value":[{"text":"email","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/title","op":"replace","value":"ApphudUserPropertyKey"},{"value":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ApphudUserPropertyKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}