{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/init(_:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey"]]},"kind":"symbol","metadata":{"title":"init(_:)","externalID":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey(im)init:","modules":[{"name":"ApphudSDK"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"init:","kind":"identifier"}],"roleHeading":"Initializer"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"key","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"syntax":null,"type":"codeListing","code":["Apphud.setUserProperty(key: .init(\"custom_prop_1\"), value: 0.5)"]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphuduserpropertykey\/init(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphuduserpropertykey\/init(_:)"]}],"abstract":[{"type":"text","text":"Initialize with custom property key string."},{"text":" ","type":"text"},{"text":"Example:","type":"text"}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey/init(_:)":{"title":"init(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/init(_:)","role":"symbol","navigatorTitle":[{"text":"init:","kind":"identifier"}],"url":"\/documentation\/apphudsdk\/apphuduserpropertykey\/init(_:)","abstract":[{"text":"Initialize with custom property key string.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Example:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"role":"collection","type":"topic","kind":"symbol","title":"ApphudSDK","abstract":[{"text":"Apphud is all-in-one infrastructure for your app growth. Apphud helps marketing and product management teams to make right decisions based on the data and tools.","type":"text"}],"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK"},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey":{"type":"topic","abstract":[{"type":"text","text":"User property initializer class with reserved property names."}],"url":"\/documentation\/apphudsdk\/apphuduserpropertykey","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApphudUserPropertyKey"}],"navigatorTitle":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"role":"symbol","title":"ApphudUserPropertyKey"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"init:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"key"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1init(_:)\/title","value":"init:"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1init(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"init:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/title","value":"ApphudUserPropertyKey"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/fragments","value":[{"kind":"identifier","text":"ApphudUserPropertyKey"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}