{"metadata":{"externalID":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey(cpy)phone","navigatorTitle":[{"text":"phone","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"ApphudSDK"}],"title":"phone","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"phone","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ApphudUserPropertyKey","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","kind":"typeIdentifier"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/phone","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"text":"ApphudUserPropertyKey","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"variants":[{"paths":["\/documentation\/apphudsdk\/apphuduserpropertykey\/phone"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/apphudsdk\/apphuduserpropertykey\/phone"]}],"references":{"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"abstract":[{"text":"User property initializer class with reserved property names.","type":"text"}],"type":"topic","title":"ApphudUserPropertyKey","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","url":"\/documentation\/apphudsdk\/apphuduserpropertykey","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApphudUserPropertyKey","kind":"identifier"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK/ApphudUserPropertyKey/phone":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"phone","kind":"identifier"}],"abstract":[],"type":"topic","title":"phone","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey\/phone","url":"\/documentation\/apphudsdk\/apphuduserpropertykey\/phone","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"phone","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ApphudUserPropertyKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey"}]},"doc://org.cocoapods.ApphudSDK/documentation/ApphudSDK":{"url":"\/documentation\/apphudsdk","identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK","title":"ApphudSDK","type":"topic","role":"collection","abstract":[{"text":"Apphud is an all-in-one growth infrastructure for subscription apps, giving marketing and product teams the data and tools they need to make better decisions.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"phone","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"phone","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.ApphudSDK\/documentation\/ApphudSDK\/ApphudUserPropertyKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@ApphudSDK@objc(cs)ApphudUserPropertyKey","text":"ApphudUserPropertyKey"},{"kind":"text","text":" * "},{"kind":"identifier","text":"phone"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/title","value":"ApphudUserPropertyKey","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/fragments","value":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey\/navigatorTitle","value":[{"text":"ApphudUserPropertyKey","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1phone\/title","value":"phone","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ApphudSDK~1documentation~1ApphudSDK~1ApphudUserPropertyKey~1phone\/fragments","value":[{"kind":"identifier","text":"phone"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}