platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ApphudDemoSwiftUI' do
  pod 'AppMetricaAnalytics', '5.8.2'
  pod 'AppMetricaApphudAdapter', '1.0.0'
end
